### PR TITLE
reverseproxy: Mask the WS close message when we're the client

### PR DESCRIPTION
**Pull request by francislavoie**
While testing a NodeJS app of mine, I noticed that since our changes to the proxy to send a WebSocket close frame, when Caddy would close first, we would see `RangeError: Invalid WebSocket frame: MASK must be set` in our logs from https://github.com/websockets/ws.

After some investigation, it looks like when we're the "client" (i.e. the upstream half of the proxy, whereas for the downstream half we act as the "server"), we need to mask the message according to https://www.rfc-editor.org/rfc/rfc6455#section-5.3.

I copied the `maskKey` and `maskBytes` code from https://github.com/websockets/ws as noted in code comments.

Needs some testing to make sure this still works correctly.

### CODE REVIEW

**Comment by francislavoie** [comment]
Tested it with my NodeJS app, seems to work! I see both the client and server closing the connection when I stop Caddy, and the error went away on the server.

**Comment by climba03003** [comment]
I just notice the same on my server. It crashed the whole application is require hard restart to resume the upstream.

**Comment by francislavoie** [comment]
@climba03003 could you try out a build with this PR to confirm the fix works for you too?

What made you find this issue, is this just an insane coincidence??

**Comment by climba03003** [comment]
> What made you find this issue, is this just an insane coincidence??

I am migrating my company from `nginx` to `caddy` in this few days. I notice it from one of my reporter that the application is down without any reason (e.g. no restart of server, no code changes).
So, I search a bit today and see this fix.

**Comment by francislavoie** [comment]
> I am using container for the application, it will be a bit hard to use a custom build.

No, it should be super easy, actually.

```Dockerfile
FROM caddy:2.6.2-builder AS builder

# TODO: Temporarily using a commit from https://github.com/caddyserver/caddy/pull/5199
# until that pull request is merged.
RUN xcaddy build 775e352b6feb6f85f2066a8933d3e0e9751b32a0

FROM caddy:2.6.2-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by climba03003** [comment]
Good to know that, I will report back after the reporter test.

**Comment by climba03003** [comment]
Seems it is not fixed in my end. I might need to patch the outside `caddy` as well.

```mermaid
stateDiagram
  [*] --> Caddy(2.6.2)
  state Container {
    Caddy(775e352b6feb6f85f2066a8933d3e0e9751b32a0) --> Node.JS
    Node.JS --> [*]
  }
  Caddy(2.6.2) --> Container
```

**Comment by francislavoie** [comment]
Probably. It depends which one is reloaded or restarted, as that's the one the close frame will be sent from.

**Comment by climba03003** [comment]
After running of 3 days, it does solve the issue. Thanks.

**Review by mholt — APPROVED** [review]
LGTM. Thanks for figuring this out, Francis! :grin:

**Pull request merged**
