### PR TITLE
caddyhttp: Added `is_verified` placeholder for client cert

### PR DESCRIPTION
**Pull request by gdhameeja**
Uses x509.Verify for verification.
For #3585 

Question: In the test, the certificate is not verified (expected value is `false`) because I'm assuming certificate used here is actually not verified right?

### CODE REVIEW

**Comment by francislavoie** [comment]
If you could add another cert that would be - verified for the purposes of tests, that'd be good. Please also document somewhere the commands you used to generate it so it can be regenerated later if need be.

I just thought - we should make sure the expiry on these certs is very very long because we don't want to suddenly get hit by failing tests because ⏳

**Comment by gdhameeja** [comment]
> If you could add another cert that would be - verified for the purposes of tests, that'd be good. Please also document somewhere the commands you used to generate it so it can be regenerated later if need be.
> 
> I just thought - we should make sure the expiry on these certs is very very long because we don't want to suddenly get hit by failing tests because

Added the test. Could you please review this again.

**Comment by francislavoie** [comment]
Could you add a comment in the test with the command you used to generate that test cert, in case it needs to be re-generated later?

Also, please add this new placeholder to the godoc comment in `modules/caddyhttp/app.go` along with the rest.

**Comment by gdhameeja** [comment]
> Could you add a comment in the test with the command you used to generate that test cert, in case it needs to be re-generated later?
> 
> Also, please add this new placeholder to the godoc comment in `modules/caddyhttp/app.go` along with the rest.
> 
> You could also add a new Caddyfile shortcut in `caddyconfig/httpcaddyfile/httptype.go` around line 100ish.

Added. Could you please review this again?

**Comment by mholt** [comment]
Thanks for the PR.

As I understand it, this is re-verifying the certificate independently of whether it was already verified during client authentication. Is that really the right logic? I feel like we shouldn't be doing the verification a second time.

**Comment by gdhameeja** [comment]
> Thanks for the PR.
> 
> As I understand it, this is re-verifying the certificate independently of whether it was already verified during client authentication. Is that really the right logic? I feel like we shouldn't be doing the verification a second time.

I will get around this fixing this PR over the weekend. Any suggestions if we're storing the result somewhere if certificate was verified during client authentication? Or if there is some other way to check the same? And I suppose, if the cert is not verified, we can use the function in the current PR and store the result?

**Comment by francislavoie** [comment]
The replacer has a `Set()` function, I think we could set the verified result that way when verification actually happens, instead of re-validating when the placeholder is used.

**Comment by gdhameeja** [comment]
This can be closed as the issue is now closed.

**Comment by francislavoie** [comment]
Actually @gdhameeja this PR still has a couple things we'd still want, i.e. the godoc comments for the `certificate_pem` placeholder. if you want to strip the rest out of the PR, we can merge that part.

**Pull request closed without merging**
