### PR TITLE
fix: delete intermediate cert if blank cert was created due to storage space

### LINKED ISSUE #4897: Ignore / Overwrite blank certificate files
## Intro
When a disk storage source lacks space, Caddy can potentially create a certificate file but fail to write the contents of the PEM to the file, so you're left with a blank file. This will throw errors similar to the one below and the hosted site will be down.

```json
{
   "level":"error",
   "ts":1657557563.517728,
   "msg":"running dynamically-loaded config failed",
   "error":"loading http app module: provision http: getting tls app: loading tls app module: provision tls: provisioning automation policy 1: loading TLS automation management module: position 0: loading module 'internal': provision tls.issuance.internal: loading pki app module: provision pki: provisioning CA 'local': decoding intermediate certificate PEM: no PEM block found"
}
```
## Proposed Behavior
Caddy should perhaps treat the empty file as if it doesn't exist. Whether the blank file should be removed / overwritten, I'll defer to your judgement. If the storage issue hasn't been addressed, then a new error could be thrown indicating that the attempt was made.

## Context
In my use case, we saw the following error indicating that the key file wasn't written to because of a lack of storage

```bash
Jul 11 12:04:57 m08296 caddy[443]: {"level":"info","ts":1657541097.5037012,"logger":"pki","msg":"intermediate expires soon; renewing","ca":"local","time_remaining":65337.496346244}
Jul 11 12:04:57 m08296 caddy[443]: {"level":"error","ts":1657541097.513083,"logger":"pki","msg":"renewing intermediate certificates","error":"generating new certificate: saving intermediate certificate: write /var/lib/caddy/.local/share/c
addy/pki/authorities/local/intermediate.crt: no space left on device","ca":"local"}
Jul 11 12:14:57 m08296 caddy[443]: {"level":"info","ts":1657541697.5043483,"logger":"pki","msg":"intermediate expires soon; renewing","ca":"local","time_remaining":64737.49569013}
Jul 11 12:14:57 m08296 caddy[443]: {"level":"error","ts":1657541697.5119374,"logger":"pki","msg":"renewing intermediate certificates","error":"generating new certificate: saving intermediate certificate: write /var/lib/caddy/.local/share/
caddy/pki/authorities/local/intermediate.crt: no space left on device","ca":"local"}
Jul 11 12:20:06 m08296 caddy[443]: {"level":"info","ts":1657542006.4763057,"logger":"tls.on_demand","msg":"attempting certificate renewal","server_name":"<redacted IP Address>","subjects":["<redacted IP Address>"],"expiration":1657410949,"remaining":-1
31057.47625807}
Jul 11 12:20:06 m08296 caddy[443]: {"level":"error","ts":1657542006.484299,"logger":"tls.on_demand","msg":"renewing certificate on-demand failed","subjects":["<redacted IP Address>"],"not_after":1657410949,"error":"failed storage check: open /va
r/lib/caddy/.local/share/caddy/rw_test_5993988438453682016: no space left on device - storage is probably misconfigured"}
Jul 11 12:21:29 m08296 caddy[443]: {"level":"info","ts":1657542089.1113331,"logger":"tls.on_demand","msg":"attempting certificate renewal","server_name":"<redacted IP Address>","subjects":["<redacted IP Address>"],"expiration":1657410949,"remaining":-1
31140.111243954}
Jul 11 12:21:29 m08296 caddy[443]: {"level":"error","ts":1657542089.1183534,"logger":"tls.on_demand","msg":"renewing certificate on-demand failed","subjects":["<redacted IP Address>"],"not_after":1657410949,"error":"failed storage check: open /v
ar/lib/caddy/.local/share/caddy/rw_test_9127296058851621699: no space left on device - storage is probably misconfigured"}
Jul 11 12:21:41 m08296 caddy[443]: {"level":"info","ts":1657542101.2605202,"logger":"tls.on_demand","msg":"attempting certificate renewal","server_name":"<redacted IP Address>","subjects":["<redacted IP Address>"],"expiration":1657410949,"remaining":-1
31152.260509214}
Jul 11 12:21:41 m08296 caddy[443]: {"level":"error","ts":1657542101.2636528,"logger":"tls.on_demand","msg":"renewing certificate on-demand failed","subjects":["<redacted IP Address>"],"not_after":1657410949,"error":"failed storage check: open /v
ar/lib/caddy/.local/share/caddy/rw_test_6185278676679082887: no space left on device - storage is probably misconfigured"}
Jul 11 12:24:57 m08296 caddy[443]: {"level":"info","ts":1657542297.5031638,"logger":"pki","msg":"intermediate expires soon; renewing","ca":"local","time_remaining":64137.496844947}
Jul 11 12:24:57 m08296 caddy[443]: {"level":"error","ts":1657542297.5078547,"logger":"pki","msg":"renewing intermediate certificates","error":"generating new certificate: saving intermediate certificate: write /var/lib/caddy/.local/share/
caddy/pki/authorities/local/intermediate.crt: no space left on device","ca":"local"}
Jul 11 12:29:17 m08296 caddy[443]: {"level":"info","ts":1657542557.5471196,"logger":"tls.on_demand","msg":"attempting certificate renewal","server_name":"<redacted IP Address>","subjects":["<redacted IP Address>"],"expiration":1657410949,"remaining":-1
31608.547068464}
Jul 11 12:29:17 m08296 caddy[443]: {"level":"error","ts":1657542557.5580342,"logger":"tls.on_demand","msg":"renewing certificate on-demand failed","subjects":["<redacted IP Address>"],"not_after":1657410949,"error":"failed storage check: open /v
ar/lib/caddy/.local/share/caddy/rw_test_2617158143528752081: no space left on device - storage is probably misconfigured"}
Jul 11 12:34:57 m08296 caddy[443]: {"level":"info","ts":1657542897.5044258,"logger":"pki","msg":"intermediate expires soon; renewing","ca":"local","time_remaining":63537.49562478}
Jul 11 12:34:57 m08296 caddy[443]: {"level":"error","ts":1657542897.516758,"logger":"pki","msg":"renewing intermediate certificates","error":"generating new certificate: saving intermediate certificate: write /var/lib/caddy/.local/share/c
addy/pki/authorities/local/intermediate.crt: no space left on device","ca":"local"}
Jul 11 12:36:50 m08296 caddy[443]: {"level":"info","ts":1657543010.710098,"logger":"tls.on_demand","msg":"attempting certificate renewal","server_name":"<redacted IP Address>","subjects":["<redacted IP Address>"],"expiration":1657410949,"remaining":-13
2061.710078924}
Jul 11 12:36:50 m08296 caddy[443]: {"level":"error","ts":1657543010.712878,"logger":"tls.on_demand","msg":"renewing certificate on-demand failed","subjects":["<redacted IP Address>"],"not_after":1657410949,"error":"failed storage check: open /va
r/lib/caddy/.local/share/caddy/rw_test_500958991974222029: no space left on device - storage is probably misconfigured"}
Jul 11 12:44:57 m08296 caddy[443]: {"level":"info","ts":1657543497.50362,"logger":"pki","msg":"intermediate expires soon; renewing","ca":"local","time_remaining":62937.496416332}
Jul 11 12:44:57 m08296 caddy[443]: {"level":"error","ts":1657543497.5116303,"logger":"pki","msg":"renewing intermediate certificates","error":"generating new certificate: saving intermediate certificate: write /var/lib/caddy/.local/share/
caddy/pki/authorities/local/intermediate.crt: no space left on device","ca":"local"}
Jul 11 12:54:08 m08296 caddy[443]: {"level":"info","ts":1657544048.851557,"logger":"tls.on_demand","msg":"attempting certificate renewal","server_name":"<redacted IP Address>","subjects":["<redacted IP Address>"],"expiration":1657410949,"remaining":-13
3099.851503154}
Jul 11 12:54:08 m08296 caddy[443]: {"level":"error","ts":1657544048.85698,"logger":"tls.on_demand","msg":"renewing certificate on-demand failed","subjects":["<redacted IP Address>"],"not_after":1657410949,"error":"failed storage check: open /var
/lib/caddy/.local/share/caddy/rw_test_3527028469984628230: no space left on device - storage is probably misconfigured"}
```

These blank files and failing site were noticed after the lack of storage space was already resolved:
```bash
root@m08296:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            992M     0  992M   0% /dev
tmpfs           201M   21M  180M  11% /run
/dev/vda1        52G   11G   39G  23% /
tmpfs          1003M     0 1003M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs          1003M     0 1003M   0% /sys/fs/cgroup
root@m08296:~# 
```

This was a local-pki intermediate cert, so there was no associated JSON file - just {root,intermediate}.{crt,key}.
Intermediate.key was missing, but root.{crt,key} were both fine.

### PR DESCRIPTION
**Pull request by Botelho31**
For #4897

### CODE REVIEW

**Comment by francislavoie** [comment]
Thanks!

It doesn't fully close https://github.com/caddyserver/caddy/issues/4897 actually, because this only fixes the `acme_server` PKI usecase, it doesn't resolve the case where Caddy failed to store data from Let's Encrypt.

**Comment by Botelho31** [comment]
Ok, i will try to add the Let`s encrypt use case

**Comment by Botelho31** [comment]
After looking more closely ( apologizing in advance if im wrong ), the error in the issue is pertaining to the intermediate certificate on PKI only, the actual leaf certificate creation and storage is all in `certmagic` and couldn`t be actually fixed in this codebase. The second error is happening on purpose as the user actually ran out of storage before the storage check for the leaf certificate.

**Comment by mholt** [comment]
I think a more general solution would be preferred.

I'm surprised an error is not returned when storage is full? Are there nothing in the logs when that happens? If not, that's concerning indeed, since it means we can't easily detect when storage is full. I would expect a failed write to give an error.

If an error is returned, we can probably delete the file that is empty/corrupt.

**Comment by Botelho31** [comment]
The error returned in the certmagic.storage.Store function if the disk is full isn't very informative. It returns an os.PathError i believe with only 'write [CERT PATH]' in the log. I could give the general solution a try if you have a suggestion.

**Comment by mholt** [comment]
PathError? That's weird. Do you have any actual logs from this happening?

But in any case, I wonder if _any_ error on `Write()` (in `Store()`) should necessitate a deletion of the file... :thinking:

**Comment by Botelho31** [comment]
The problem in Store i believe is that if there isn`t enought space it cancels the writing of the file, but as the file was created beforehand it leaves an empty file ( in this case a cert ). In any case all of these problems occur as we don`t have knowledge of storage space in PKI module during creation.

**Comment by mholt** [comment]
Oh, and after looking closer, `PathError` is just a container for a path + error. So a "path error" isn't the error itself, but it should contain an actual error with more information.

I'm not suggesting we leave a blank or corrupted file. When Write has an error, maybe we should delete the file so as not to give Caddy the wrong idea (that the file is valid).

What was the full error / log?

**Comment by Botelho31** [comment]
I have created a minimal setup that errors at the initial setup of the PKI, here is the error that is actually thrown then:

`Error: loading initial config: loading new config: loading http app module: provision http: getting tls app: loading tls app module: provision tls: provisioning automation policy 0: loading TLS automation management module: position 0: loading module 'internal': provision tls.issuance.internal: loading pki app module: provision pki: provisioning CA 'local': generating new intermediate cert: saving intermediate key: write /data/caddy/pki/authorities/local/intermediate.key: no space left on device`

**Comment by mholt** [comment]
Ah, perfect: `no space left on device` - thanks for the effort!

That log gives us a good trace of the error to be able to implement a failover where we delete the file when a write fails, if it did not exist before.

Although... @elee1766 question for you: does the new way of writing to the file storage make this a non-issue? i.e. writing the new payload would fail, the temporary file would get cleaned up, and the existing file would continue to exist without corruption, right?

**Comment by elee1766** [comment]
> Ah, perfect: `no space left on device` - thanks for the effort!
> 
> That log gives us a good trace of the error to be able to implement a failover where we delete the file when a write fails, if it did not exist before.
> 
> Although... @elee1766 question for you: does the new way of writing to the file storage make this a non-issue? i.e. writing the new payload would fail, the temporary file would get cleaned up, and the existing file would continue to exist without corruption, right?

yeah. it should fail on syncing the temp file, and then never run the rename, therefore leaving the existing cert as is

**Comment by Botelho31** [comment]
I was using 2.8.4 as it was latest in docker ( i believe ). I will try to check latest master version today, but if the exchange of intermediate certificates doesn't leave a blank file anymore ( as it does the whole renaming process ) then i guess the actual problem is fixed.

**Comment by mholt** [comment]
Yep, I'm guessing that @elee1766's upstream enhancement for how files are written (which master is now using) is probably the fix for this.

**Comment by Botelho31** [comment]
I have just tested the master changes, this doesn`t appear to be happening anymore! Should the original issue be closed too?

**Comment by francislavoie** [comment]
Guess so! Thanks for confirming!

**Pull request closed without merging**
