### PR TITLE
chore: Upgrade smallstep libs

### PR DESCRIPTION
**Pull request by francislavoie**
See https://github.com/smallstep/nosql/issues/12 for context.

/cc @ThinkChaos regarding https://github.com/caddyserver/caddy/issues/3525#issuecomment-899869317

There's a surprising amount of `go.sum` changes from this, but I don't think we need to worry about that. It's a side effect of Go not pruning the graph in Go 1.16, I think once we bump to Go 1.17, it should get shrunken down significantly. See https://golang.org/ref/mod#graph-pruning

### CODE REVIEW

**Comment by mholt** [comment]
So to be sure I follow, this removes the pb.proto warning and removes the CGO dependency?

**Comment by francislavoie** [comment]
Doesn't remove the CGO dependency _yet_. That's gonna require https://github.com/dgraph-io/badger/pull/1736 first, because `smallstep/nosql` seems to not be able to safely upgrade to badger v3 without breaking changes, so I'm trying to get badger to backport the fix for that to their v2 branch.

But AFAIK yeah it should solve the pb.proto issue and some other random problems that have shown up since.

**Comment by ThinkChaos** [comment]
I can confirm it fixes the pb.proto warning for me.

**Review by mholt — APPROVED** [review]
Thanks for helping push this along! Looking forward to getting rid of that cgo dependency too.

**Pull request merged**
