### PR TITLE
cmd: fix auto-detetction of .caddyfile extension

### LINKED ISSUE #6355: using the file ext caddyfile for a config file does not work
```
./caddy run  -c test.caddyfile
2024/05/31 14:25:55.237 INFO    using config from file  {"file": "test.caddyfile"}
Error: config is not valid JSON: invalid character ':' looking for beginning of value; did you mean to use a config adapter (the --adapter flag)?
```

test.caddyfile
```
:2015
respond "Hello, world!"
```

### PR DESCRIPTION
**Pull request by mohammed90**
Fix #6355

### CODE REVIEW

**Comment by francislavoie** [comment]
I think this existed to deal with https://github.com/caddyserver/caddy/pull/5919#discussion_r1425560197 i.e. `Caddyfile.yaml` if `yaml` is loaded as an adapter, should use that instead of the Caddyfile adapter.

**Comment by mohammed90** [comment]
> I think this existed to deal with [#5919 (comment)](https://github.com/caddyserver/caddy/pull/5919#discussion_r1425560197) i.e. `Caddyfile.yaml` if `yaml` is loaded as an adapter, should use that instead of the Caddyfile adapter.

They would have specified the `--adapter` flag. I've moved the conditions around and added a comment.

**Comment by mholt** [comment]
Are you sure though? The point of this is to presume when the Caddyfile is being used: `Caddyfile.yaml` is clearly ambiguous (and incorrect, since a yaml file isn't Caddyfile, and a Caddyfile isn't yaml) -- what happens if they _don't_ use the `--adapter` flag? Do we presume Caddyfile or YAML?

**Comment by mohammed90** [comment]
> what happens if they _don't_ use the `--adapter` flag? Do we presume Caddyfile or YAML?

I can add a condition for such pesky scenarios 🙂 

```
if adapterName == "" && startsOrEndsInCaddyfile {
    return nil, "", fmt.Error("ambiguous... blablabbla")
}
```

**Comment by mholt** [comment]
Ok, yeah, that sounds better. Maybe an error is better than ignoring it like we were doing. (But yeah, it's still important that we don't proceed, either way.)

**Review by mholt — APPROVED** [review]
Thanks Mohammed!

**Comment by graphixillusion** [comment]
With this new modification, in version 2.8.2 my Caddyfile isn't recognized anymore. I need to force it using -c Caddyfile --adapter caddyfile. If not i get ambigous config message error. Same Caddyfile works without problems in 2.8.1

**Comment by mohammed90** [comment]
> With this new modification, in version 2.8.2 my Caddyfile isn't recognized anymore. I need to force it using -c Caddyfile --adapter caddyfile. If not i get ambigous config message error. Same Caddyfile works without problems in 2.8.1

My bad. Let me work on the fix. I'm sorry.

**Comment by mohammed90** [comment]
> You may need to modify the documents of your official website

That's not necessary. It's a regression. Please see the linked PR.

**Comment by avluis** [comment]
Aha! I knew it; appreciate the very quick fix!

**Pull request merged**
