### PR TITLE
V2: Implement UDP writer

### PR DESCRIPTION
**Pull request by AbdelmalekIhdene**
---
name: V2: Implement UDP writer
about: Implement a UDP writer to the logging interface
---

## 1. What does this change do, exactly?
It implements a basic UDP writer for the logging interface. This is useful for sending logs directly to syslog servers such as GrayLog. I am curious, however, does changing the options of the writer call OpenWriter again? I believe it would since without that, filewriter would be broken. One issue that seems to happen is that when caddy closes. The few last messages are not sent to the UDP server since a connection refused error happens instead.
Tl;dr: The change was done to have a way to set up log aggregation through Caddy.

## 3. Which documentation changes (if any) need to be made because of this PR?

Well, "caddy.logging.writers.udp" writer information should be added to the documentation.

## 4. Checklist
* Does Caddy have integration testing yet? I feel like testing UDP communication would be hard.
- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by AbdelmalekIhdene** [comment]
I wonder if there's a way to send UDP packets without dialing a UDP server, just like in C. It's also kind of weird since I'm pretty sure UDP is a connection-less protocol.

**Comment by mholt** [comment]
Thanks for the PR! Sorry it took a while for me to get to this.

This is looking good. Any particular reason it's IPv4-only? Any reason we need to specify which network type it is at all? You can `net.Dial("udp", ...)` and it should just work, I think.

> I am curious, however, does changing the options of the writer call OpenWriter again? 

If a new config is loaded and a different UDP address is in the new config, the old one will be closed and the new one will take effect. If the address is the same, it will be reused. This is taken care of for you.

> One issue that seems to happen is that when caddy closes. The few last messages are not sent to the UDP server since a connection refused error happens instead.

Hm, can you provide more detail? This might be expected since if Caddy is shutting down, it needs to shut down its log writers too.

**Comment by AbdelmalekIhdene** [comment]
@mholt I have generalized the net writer for any protocol or IP address. It was dummy dumb dumb to sanitize the IP address since net.Dial(...) handles that either ways. I'm not really good at Github so I don't know how to combine the older commits with the newer ones :/

**Comment by mholt** [comment]
@AbdelmalekIhdene Can you give me permission to push to your branch? I have a few revisions to push before merging but I'm getting permission denied.

**Comment by mholt** [comment]
Oh, weird... it looks like the push succeeded... nevermind! I got a big red error but apparently it did work.

Can you try it out, @AbdelmalekIhdene, and let me know what you think? It now uses Caddy's standard network address syntax, which is described here: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httpserverslisten

**Comment by AbdelmalekIhdene** [comment]
Well, this is the curl command I used to test my net writer and it worked fine, but it seems that there were changes done to caddy after my pull and it doesn't seem to work anymore...
```
curl localhost:2019/config/logging -X PUT -H "Content-Type: application/json" --data-binary @- << EOF
{
   "logs":{
      "default":{
         "level":"info",
         "writer":{
            "output":"net",
            "address":"127.0.0.1:8080"
         }
      }
   }
}
EOF
```
I get this error now:
```
2019/12/13 02:08:47.850	INFO	admin.api	received request	{"method": "PUT", "uri": "/config/logging", "remote_addr": "127.0.0.1:39540", "headers": {"Accept":["*/*"],"Content-Length":["170"],"Content-Type":["application/json"],"User-Agent":["curl/7.58.0"]}}
2019/12/13 02:08:47.850	ERROR	admin.api	request error	{"error": "invalid traversal path at: config/logging", "status_code": 500}
{"error":"invalid traversal path at: config/logging"}
```

**Comment by AbdelmalekIhdene** [comment]
The net writer works fine and so does switching net logging hosts on the fly. I can redirect the logging from one server to another without a problem. However, I found one issue.
Whenever I try to establish a connection to an endpoint that does not exist, I get this message:
```
2019/12/13 02:27:29.428	ERROR	admin.api	request error	{"error": "loading new config: setting up default log: opening log writer using &logging.NetWriter{Address:\"tcp/localhost:8081\", addr:caddy.ParsedAddress{Network:\"tcp\", Host:\"localhost\", StartPort:0x1f91, EndPort:0x1f91}}: dial tcp 127.0.0.1:8081: connect: connection refused", "status_code": 500}
{"error":"loading new config: setting up default log: opening log writer using \u0026logging.NetWriter{Address:\"tcp/localhost:8081\", addr:caddy.ParsedAddress{Network:\"tcp\", Host:\"localhost\", StartPort:0x1f91, EndPort:0x1f91}}: dial tcp 127.0.0.1:8081: connect: connection refused"}
```
And then, whenever I try connecting to another server. Caddy panics
```
2019/12/12 21:28:36 http: panic serving 127.0.0.1:40026: interface conversion: interface is nil, not io.WriteCloser
goroutine 45 [running]:
net/http.(*conn).serve.func1(0xc0001faa00)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xd1ca20, 0xc0002fa780)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/caddyserver/caddy/v2.(*Logging).openWriter(0xc00011bd10, 0x7f4e71ba5128, 0xc00007f680, 0x7f4e71ba5128, 0xc00007f680, 0x1, 0x1, 0xd44440)
	/home/malek/caddy/logging.go:231 +0x12a
github.com/caddyserver/caddy/v2.(*CustomLog).provision(0xc0002cc410, 0xf7d980, 0xc00007f640, 0xc0002fa600, 0xc0002a0640, 0xc0000100b0, 0x1, 0x1, 0xc00011bd10, 0xc00006c9e0, ...)
	/home/malek/caddy/logging.go:416 +0x432
github.com/caddyserver/caddy/v2.(*Logging).setupNewDefault(0xc00011bd10, 0xf7d980, 0xc00007f640, 0xc0002fa600, 0xc0002a0640, 0xc0000100b0, 0x1, 0x1, 0x15d23c0, 0x7f4e71c75008)
	/home/malek/caddy/logging.go:152 +0x118
github.com/caddyserver/caddy/v2.(*Logging).openLogs(0xc00011bd10, 0xf7d980, 0xc00007f640, 0xc0002fa600, 0xc0002a0640, 0xc0000100b0, 0x1, 0x1, 0xc00007f640, 0xc0002fa600)
	/home/malek/caddy/logging.go:99 +0xf9
github.com/caddyserver/caddy/v2.run(0xc0002a0640, 0x1, 0x0, 0x0)
	/home/malek/caddy/caddy.go:338 +0x263
github.com/caddyserver/caddy/v2.unsyncedDecodeAndRun(0xc0002e0380, 0xd3, 0xe0, 0xe0, 0xe60a10)
	/home/malek/caddy/caddy.go:258 +0x97
github.com/caddyserver/caddy/v2.changeConfig(0xc00003a660, 0x4, 0xc00003a665, 0xf, 0xc0002d2000, 0xae, 0x200, 0x0, 0x0, 0x0)
	/home/malek/caddy/caddy.go:169 +0x520
github.com/caddyserver/caddy/v2.handleConfig(0xf7aa40, 0xc0002c61c0, 0xc0002a2300, 0x0, 0x0)
	/home/malek/caddy/admin.go:521 +0x40e
github.com/caddyserver/caddy/v2.AdminHandlerFunc.ServeHTTP(0xe60a38, 0xf7aa40, 0xc0002c61c0, 0xc0002a2300, 0x10, 0x0)
	/home/malek/caddy/admin.go:750 +0x44
github.com/caddyserver/caddy/v2.AdminConfig.newAdminHandler.func1.1(0xf7aa40, 0xc0002c61c0, 0xc0002a2300)
	/home/malek/caddy/admin.go:101 +0x6d
net/http.HandlerFunc.ServeHTTP(0xc00007e340, 0xf7aa40, 0xc0002c61c0, 0xc0002a2300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00007e2c0, 0xf7aa40, 0xc0002c61c0, 0xc0002a2300)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
github.com/caddyserver/caddy/v2.adminHandler.serveHTTP(0x0, 0xc00006c360, 0x1, 0x1, 0xc00007e2c0, 0xf7aa40, 0xc0002c61c0, 0xc0002a2300)
	/home/malek/caddy/admin.go:293 +0x71
github.com/caddyserver/caddy/v2.adminHandler.ServeHTTP(0x0, 0xc00006c360, 0x1, 0x1, 0xc00007e2c0, 0xf7aa40, 0xc0002c61c0, 0xc0002a2300)
	/home/malek/caddy/admin.go:263 +0x4f6
net/http.serverHandler.ServeHTTP(0xc0002c60e0, 0xf7aa40, 0xc0002c61c0, 0xc0002a2300)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0001faa00, 0xf7d980, 0xc00007ecc0)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
curl: (52) Empty reply from server
```
I'll look into it, but it shouldn't do this...
Oh yeah, these are the messages that do not get sent to the UDP endpoint:
```
2019/12/12 21:24:09 [INFO][cache:0xc000133680] Stopped certificate maintenance routine
2019/12/13 02:24:09.936	WARN	unable to use API to stop instance; will try to signal the process	{"endpoint": "http://localhost:2019/stop", "error": "performing request: Post http://localhost:2019/stop: EOF"}
stop: Caddy is not running
```
And these are the last messages it receives:
```
": "POST", "uri": "/stop", "remote_addr": "127.0.0.1:39956", "headers": {"Accept-Encoding":["gzip"],"Content-Length":["0"],"Origin":["localhost:2019"],"User-Agent":["Go-http-client/1.1"]}}
2019/12/13 02:24:09.935	INFO	admin.api	unloading
2019/12/13 02:24:09.935	INFO	admin.api	unloading completed
2019/12/13 02:24:09.935	INFO	admin.api	stopping now, bye!! 👋
```

**Comment by mholt** [comment]
Can you please post your config so I can reproduce the error? Otherwise only you can fix it :+1:

**Comment by mholt** [comment]
@AbdelmalekIhdene 

Thanks for the details.

This part:

> And then, whenever I try connecting to another server. 

Is ambiguous so I wasn't able to reproduce that, but I've pushed up a couple fixes. Please pull and try again. If you still see a panic please tell me exactly how to get the same thing.

**Comment by AbdelmalekIhdene** [comment]
1. `cd caddy/cmd/caddy && echo :1234 > Caddyfile`
2. `go build && `./caddy start --config Caddyfile --adapter caddyfile`
3. Without anything listening on `tcp/localhost:8081`:
```
curl localhost:2019/config/logging -X POST -H "Content-Type: application/json" --data-binary @- << EOF
{
   "logs":{
      "default":{
         "level":"info",
         "writer":{
            "output":"net",
            "address":"tcp/localhost:8081"
         }
      }
   }
}
EOF
```
And it returns...
```
2019/12/14 17:45:30.863	INFO	admin.api	received request	{"method": "POST", "uri": "/config/logging", "remote_addr": "127.0.0.1:43216", "headers": {"Accept":["*/*"],"Content-Length":["174"],"Content-Type":["application/json"],"User-Agent":["curl/7.58.0"]}}
2019/12/14 17:45:30.863	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
2019/12/14 17:45:30.864	ERROR	admin.api	request error	{"error": "loading new config: setting up default log: opening log writer using &logging.NetWriter{Address:\"tcp/localhost:8081\", addr:caddy.ParsedAddress{Network:\"tcp\", Host:\"localhost\", StartPort:0x1f91, EndPort:0x1f91}}: dial tcp 127.0.0.1:8081: connect: connection refused", "status_code": 500}
{"error":"loading new config: setting up default log: opening log writer using \u0026logging.NetWriter{Address:\"tcp/localhost:8081\", addr:caddy.ParsedAddress{Network:\"tcp\", Host:\"localhost\", StartPort:0x1f91, EndPort:0x1f91}}: dial tcp 127.0.0.1:8081: connect: connection refused"}
2019/12/14 17:45:31.364	INFO	admin	stopped previous server
```
Upon doing that again, it seems like the error is fixed, and also you get... 
```
2019/12/14 17:47:00.897	INFO	admin.api	received request	{"method": "POST", "uri": "/config/logging", "remote_addr": "127.0.0.1:43224", "headers": {"Accept":["*/*"],"Content-Length":["174"],"Content-Type":["application/json"],"User-Agent":["curl/7.58.0"]}}
2019/12/14 17:47:00.897	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
2019/12/14 17:47:00.897	ERROR	admin.api	request error	{"error": "loading new config: setting up default log: opening log writer using &logging.NetWriter{Address:\"tcp/localhost:8081\", addr:caddy.ParsedAddress{Network:\"tcp\", Host:\"localhost\", StartPort:0x1f91, EndPort:0x1f91}}: dial tcp 127.0.0.1:8081: connect: connection refused", "status_code": 500}
{"error":"loading new config: setting up default log: opening log writer using \u0026logging.NetWriter{Address:\"tcp/localhost:8081\", addr:caddy.ParsedAddress{Network:\"tcp\", Host:\"localhost\", StartPort:0x1f91, EndPort:0x1f91}}: dial tcp 127.0.0.1:8081: connect: connection refused"}
2019/12/14 17:47:00.897	INFO	admin	stopped previous server
```

**Comment by mholt** [comment]
Cool, so it is working as expected?

**Comment by AbdelmalekIhdene** [comment]
It works for my specific purpose as far as of today (1 week in production). Time and other users will tell. :)

**Pull request merged**
