### PR TITLE
chore: Use slices package where possible

### PR DESCRIPTION
**Pull request by francislavoie**
Just a simple cleanup, we can use `slices.Contains()` in a bunch of spots now instead of helper functions to do the simple loop.

### CODE REVIEW

**Comment by francislavoie** [comment]
2nd commit is potentially more controversial, using `ContainsFunc` (5 lines -> 3 lines).

**Review by mohammed90 — APPROVED** [review]
I like it, even the controversial one!

**Comment by francislavoie** [comment]
Added even more.

FWIW, I was using regexp searches like this to find them :joy: might've missed some, did the ones I could find.

```
	*for [a-zA-Z_\.]*, [a-zA-Z_\.]* := range [a-zA-Z_\.]* \{
	*if [a-zA-Z_\.]* == [a-zA-Z_\.]* \{
```

**Comment by mohammed90** [comment]
> FWIW, I was using regexp searches like this to find them :joy: might've missed some, did the ones I could find.
> 
> ```
> 	*for [a-zA-Z_\.]*, [a-zA-Z_\.]* := range [a-zA-Z_\.]* \{
> 	*if [a-zA-Z_\.]* == [a-zA-Z_\.]* \{
> ```

I was going to suggest semgrep, but apparently they went all proprietary 😕

**Review by mholt — APPROVED** [review]
Finally got through all 21 files. I think they are correct changes, if I understand the functions correctly. Thank you for the improvements!

**Pull request merged**
