### PR TITLE
listeners: embed `net.UDPConn` to allow automatic optimization by quic-go

### PR DESCRIPTION
**Pull request by WeidiDeng**
…tic optimization by quic-go

Fix [5605](https://github.com/caddyserver/caddy/issues/5605), [3932](https://github.com/quic-go/quic-go/issues/3932).

As a side effect, less code for interface implementation.

### CODE REVIEW

**Review by mholt — APPROVED** [review]
Oh, this is even better than I was working on locally!

Thanks :blush:

**Comment by mholt** [comment]
Interesting, goreleaser-check is failing. https://github.com/caddyserver/caddy/actions/runs/5420166639/jobs/9866067348

@mohammed90 Looks like we are using deprecated properties :monocle_face:

**Comment by mohammed90** [comment]
> Interesting, goreleaser-check is failing. https://github.com/caddyserver/caddy/actions/runs/5420166639/jobs/9866067348
> 
> @mohammed90 Looks like we are using deprecated properties 🧐

On it!

**Comment by mholt** [comment]
Awesome, thanks Mohammed! Retesting.

**Pull request merged**
