### PR TITLE
cmd: add ability to read config from stdin

### PR DESCRIPTION
**Pull request by masipcat**
Close https://github.com/caddyserver/caddy/issues/3897

### CODE REVIEW

**Review by francislavoie — APPROVED** [review]
Cool! I don't see why not! :+1:

**Comment by mholt** [comment]
Thanks, it's a nice enhancement and elegant enough, but this affects all functions that call `loadConfig()` including `run` and `reload`. Have you tested how this works with `caddy start`, which utilizes stdin to run `caddy run`?

**Comment by masipcat** [comment]
> Thanks, it's a nice enhancement and elegant enough, but this affects all functions that call `loadConfig()` including `run` and `reload`. Have you tested how this works with `caddy start`, which utilizes stdin to run `caddy run`?

Nope, tomorrow I'll test and report the results!

**Comment by masipcat** [comment]
It doesn't work :( The load config is reading this bytes: https://github.com/caddyserver/caddy/blob/master/cmd/commandfuncs.go#L88-L101

**Comment by mholt** [comment]
Thanks for checking! That's good to know.

It means that `caddy start --config -` won't work, but `caddy run --config -` will. I think we'll have to be OK with that, and mention it in the documentation.

We could probably _make_ it work, but it'll require some hoop-jumping.

**Review by mholt — APPROVED** [review]
If you get a chance would you mind submitting a patch to [the docs](https://github.com/caddyserver/website) mentioning this feature? With the caveat that it won't work for `caddy start`.

**Pull request merged**
