### PR TITLE
ci: Improve build artifact file names

### PR DESCRIPTION
**Pull request by francislavoie**
As requested by @mholt https://github.com/caddyserver/caddy/pull/3166#discussion_r396000650

As described in https://stackoverflow.com/a/59819441

Edit:

```
caddy_v2_Linux_38997b3
caddy_v2_macOS_38997b3
caddy_v2_Windows_38997b3
```

### CODE REVIEW

**Comment by francislavoie** [comment]
Whoops, looks like the short_sha is broken on windows... :/

**Comment by francislavoie** [comment]
Oh, missing quotes `"` 🤦‍♂

**Comment by mholt** [comment]
Ah this is much better!

Pending the SHA on Windows, I love it. (Or rather, I already love it, and I just hate Windows?)

**Comment by francislavoie** [comment]
Alright done, looks good 👍

**Pull request merged**
