### PR TITLE
reverseproxy: Add duration/latency placeholders (close #4012)

### LINKED ISSUE #4012: Feature Request: Placeholders (at header time) for request time & upstream time.
Hello all,

This feature request is stemming from [Any equivalent of $request_time and $upstream_header_time from nginx?](https://caddy.community/t/any-equivalent-of-request-time-and-upstream-header-time-from-nginx/11418). To summarize, there are two placeholders that I'm using in nginx now that would be very useful to me in caddy:

1) [request_time](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_time):

> request processing time in seconds with a milliseconds resolution; time elapsed since the first bytes were read from the client.

2) [upstream_header_time](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_header_time):

> keeps time spent on receiving the response header from the upstream server; the time is kept in seconds with millisecond resolution.

Note that nginx does have an [upstream_response_time](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_response_time), but this isn't available at header time because nginx forwards the headers returned by upstream before it receives the response body. I don't know if Caddy does this, or if it instead buffers the response and only computes headers after response is fully received (and fully timed), but for this feature request, `upstream_header_time` and `upstream_response_time` are close enough where a port of either one would be great.

I would use these placeholders to signify to our client how much of the latency they observed was due to their upload speeds vs. our processing speeds. For example, if I returned `X-Trip-Time == 5` (where 5 is the equivalent of `request_time`) and `X-Process-Time == 3` (where 3 is the equivalent of `upstream_header_time` / `upstream_response_time`), then they would know that they spent roughly 2 seconds uploading.

If this is a feature request that the maintainers are okay with and it's a good first issue, I might be able to take a shot at this. Just would need a pointer on where to start.

### PR DESCRIPTION
**Pull request by mholt**
Adds 4 placeholders, one is actually outside reverse proxy though:

`{http.request.duration}` is how long since the server decoded the HTTP request (headers).
`{http.reverse_proxy.upstream.latency}` is how long it took a proxy upstream to write the response header.
`{http.reverse_proxy.upstream.duration}` is total time proxying to the upstream, including writing response body to client.
`{http.reverse_proxy.duration}` is total time spent proxying, including selecting an upstream and retries.

Obviously, most of these are only useful at the end of a request, like when writing response headers or logs.

See also: https://caddy.community/t/any-equivalent-of-request-time-and-upstream-header-time-from-nginx/11418

Closes #4012

### CODE REVIEW

**Comment by francislavoie** [comment]
Should add these the godocs, right?

**Comment by mholt** [comment]
Yeah, good point. Doing that now.

**Review by francislavoie — APPROVED** [review]

**Comment by MarioIshac** [comment]
Alright this is looking great, given [this caddy.json](https://gist.github.com/MarioIshac/268d7f62bae47580529648401a4d9b20) I've successfully received `{http.request.duration}` and `{http.reverse_proxy.upstream.latency}` as headers. And, as expected, `{http.reverse_proxy.upstream.duration}` and `{http.reverse_proxy.duration}` are not available at header-time because Caddy has already sent the response by then.

Note that `"buffer_requests": true` was required to make `{http.reverse_proxy.upstream.latency}` independent of file uploading time from the client. When Caddy doesn't buffer a request (by default), it streams the request bytes to upstream, meaning that upstream is contacted (and `{http.reverse_proxy.upstream.latency}` starts going) before a client finished sending the request. In my case, this caused the upstream latency to look big (and actually roughly equal the request duration) even though my client was a slow uploader.

What if `{http.reverse.proxy.upstream.*}` started going after the last byte of the request finished streaming, instead of the first byte? Would this make it independent from `buffer_requests`?

**Comment by mholt** [comment]
@MarioIshac Great, thanks for trying it out.

> What if {http.reverse.proxy.upstream.*} started going after the last byte of the request finished being sent upstream, instead of the first byte?

I'm not sure that's a reasonable assumption we can make: AFAIK there's no reason a backend can't start sending the response before it has finished reading the request, and in fact I'm pretty sure quite a few servers work this way (and has been the cause of some bugs in the Go standard library in the past).

> In my case, this caused the upstream latency to look big (and actually roughly equal the request duration) even though it was my client's fault for being slow uploader.

I think that's actually good information from these placeholders -- the small difference makes it easy to show that the client uploading is the bulk of the request time, _but this deduction requires knowing how your backend works._ A backend will either wait to download the entire body before writing a response, or it will start writing a response before the body has been fully read.

**Comment by francislavoie** [comment]
I figure we can merge this?

**Comment by mholt** [comment]
Is the implementation of `{http.reverse_proxy.upstream.latency}` satisfactory though?

**Comment by MarioIshac** [comment]
Currently using the build artifact from this PR in prod, been working well. Let me know if there's anything more I can do to help get this merged, but don't have the expertise to comment on the implementation itself though.

**Comment by francislavoie** [comment]
I think the only open question was whether we agree how `.latency` behaves, but if Matt's answer is satisfactory I think we can merge it.

Thanks!

**Comment by MarioIshac** [comment]
Matt's answer makes sense to me, especially after I looked into what types of servers would send response back before request is complete (sending "unauthorized" instead of waiting for file upload to complete, for example). Because this is an implementation detail of the backend, the backend can send the time it received the last byte of the request if desired outside of Caddy.

**Comment by francislavoie** [comment]
I think this might resolve some of the concerns in https://github.com/caddyserver/caddy/issues/2268 as well @mholt?

**Comment by mholt** [comment]
@francislavoie Hmm, yes I believe it does. Between these 4 placeholders, they should be able to get the info they need. Thanks for linking that up.

I'll go ahead and merge this then. Thank you both!

**Pull request merged**
