### PR TITLE
v2: speed up some of powershell's processes

### PR DESCRIPTION
**Pull request by Mohammed90**
## 1. What does this change do, exactly?

Downloading the latest Go and extracting the archive is slow on Windows. According to PowerShell/PowerShell#2138 this is due to PowerShell attempting to update the progress. Since this is running on CI, the progress isn't important.

## 2. Please link to the relevant issues.

PowerShell/PowerShell#2138

## 3. Which documentation changes (if any) need to be made because of this PR?

N/A

## 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by Mohammed90** [comment]
According to the [build of this PR](https://dev.azure.com/mholt-dev/Caddy/_build/results?buildId=284), downloading and expanding the latest Go took 1m2s versus [an old builds](https://dev.azure.com/mholt-dev/Caddy/_build/results?buildId=277) which took 3m30s 😃 

Now `Expand-Archive` still has [performance issue](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/32).

**Comment by mholt** [comment]
Wow! You're a wizard, @Mohammed90! Looking forward to this :+1:

**Comment by mholt** [comment]
Do you think https://github.com/mholt/archiver would be any faster at unzipping than 7z? (It's unlikely, since I haven't done any optimizations on it, but worth a try maybe?)

**Comment by Mohammed90** [comment]
Maybe 🤔 but now the question becomes whether the combination of downloading and calling `arc` is faster than 7z on its own.

I would benchmark it, but I have a Mac. The last time I tried accessing a Windows VM on Azure was nothing but unresolved pain.

**Comment by Mohammed90** [comment]
We're down to only 46s for both downloading latest Go and extracting!! I have nothing more to add to this PR.

For next time, I'll check if it's fine to cache `GOCACHE` with [CacheBeta](https://devblogs.microsoft.com/devops/caching-and-faster-artifacts-in-azure-pipelines/). This should speed up downloading the deps.

**Pull request merged**
