### PR TITLE
Update quic-go to v0.37.0, bump to Go 1.20 minimum

### PR DESCRIPTION
**Pull request by marten-seemann**
See https://github.com/quic-go/quic-go/releases/tag/v0.37.0 for release notes.

### CODE REVIEW

**Comment by marten-seemann** [comment]
As far as I can tell, CI is failing because it's still using Go 1.19 for a number of jobs. quic-go v0.37.0 only support Go 1.20 and 1.21.

**Comment by mholt** [comment]
We typically ensure support for the previous major Go release for Debian packaging purposes. But I'm 100% OK with upgrading to Go 1.20 now (Go 1.21 is in RC phase) especially given the benefits of this upgrade.

Thanks for the PR! :)

PS. I am subscribed to new releases on your repo too, you always just beat me to it :smile:

**Comment by mholt** [comment]
Made Go 1.20 required instead of Go 1.19, but the CI tests are still the same after re-running. I'll try closing and re-opening the PR...

**Comment by francislavoie** [comment]
I pushed a commit to bump the minimum to Go 1.20.

**Comment by mholt** [comment]
Hang on, now the linter's drunk. Re-running

**Comment by francislavoie** [comment]
Linter wasn't working because we were on an older golangci-lint version which didn't support 1.20.

**Comment by francislavoie** [comment]
Welp. It's still not working and I don't know why :sob: 

I have to go afk to do something else but I'll try again later.

**Comment by mholt** [comment]
I wonder if we could get away with not changing the CI at all? Even if the 1.19 tests fail we could still merge this now that 1.19 is no longer required to succeed.

**Comment by marten-seemann** [comment]
None of my business, but why keep 1.19 now that’s it’s guaranteed to fail?

**Comment by francislavoie** [comment]
We're not :thinking: where are you seeing that

**Comment by francislavoie** [comment]
Okay, this should be good to go now :+1:

**Comment by marten-seemann** [comment]
I was just replying to @mholt’s comment:
> I wonder if we could get away with not changing the CI at all? Even if the 1.19 tests fail we could still merge this now that 1.19 is no longer required to succeed.

**Comment by mholt** [comment]
Awesome, thanks for the CI fixes Francis!

Re: my comment -- I was just suggesting a quick-and-dirty way to get this mergeable. But I appreciate the effort to fix the problem with CI instead :blush:

We got approval from the RHEL maintainer Carl to go ahead and bump up to Go 1.20 a little early.

Thank you everyone!

**Review by mholt — APPROVED** [review]

**Pull request merged**
