### PR TITLE
caddyhttp: Add `{?query}` placeholder

### PR DESCRIPTION
**Pull request by francislavoie**
This is a two in one:
- Closes https://github.com/caddyserver/caddy/issues/6705, adds `{http.request.uri.prefixed_query}` as the long-form and `{?query}` as the Caddyfile shorthand.
- Fixes a bug found in https://caddy.community/t/preserving-query-string-during-rewrite/26538/4 where the `php_fastcgi` canonicalization redirect doesn't preserve the query :grimacing:

### CODE REVIEW

**Review by whitestrake — COMMENTED** [review]
Built and tested real quick - looks like this has handily fixed the repro I found in https://caddy.community/t/preserving-query-string-during-rewrite/26538/4

LGTM!

**Review by gingerbeardman — APPROVED** [review]

**Comment by gingerbeardman** [comment]
Thanks all!

**Comment by mholt** [comment]
Hear me out for a sec, what if it was named `{?query}`?

**Comment by francislavoie** [comment]
Hmmmmmmmmmmmmmm... well nothing else we have currently has special chars in the placeholder. Maybe we do that only for the Caddyfile shortcut?

**Comment by mholt** [comment]
Yeah, for the Caddyfile shortcut at least would be nice :+1:

**Comment by francislavoie** [comment]
Yep already done @mholt :sweat_smile:

**Review by mholt — APPROVED** [review]

**Pull request merged**
