### PR TITLE
caddytls: Add Caddyfile support for key_type global option

### PR DESCRIPTION
**Pull request by francislavoie**
As per https://caddy.community/t/how-do-i-use-rsa-instead-of-ec-certificates/7448/3?u=francislavoie

```
{
    key_type rsa4096
}
```

### CODE REVIEW

**Comment by mholt** [comment]
Thanks -- I think this looks good, but any reason this is a global option instead of a `tls` subdirective?

I'm OK with the global option, but people might want to customize it per-site...

(PS. Merge conflict. Sorry!)

**Comment by francislavoie** [comment]
Rebased 👍 

Global seemed like the easiest option, couldn't really see how to wire it up if it was in `tls` since it's an option on AutomationPolicy which currently is only configured globally as far as I can tell?

**Comment by tracker1** [comment]
Tried adding the directive in the following, but getting an error...

```
run: loading initial config: loading new config: loading http app module: provision http: getting tls app: loading tls app module: tls: invalid configuration: automation policy 1 is the second policy that acts as default/catch-all, but will never be used
```

Caddyfile

```
{
  key_type rsa4096
}

roughneckbbs.com {
  log {
    # level DEBUG
  }

  # @websockets {
  #   header Connection *Upgrade*
  #   header Upgrade websocket
  # }
  # reverse_proxy @websockets sbbs:1123 {
  #   header_up Connection "Upgrade"
  #   header_up Upgrade "websocket"
  #   header_up Host {host}
  #   header_up X-Real-IP {remote_host}
  #   header_up X-Forwarded-For {remote_host}
  #   header_up X-Forwarded-Proto {scheme}
  # }

  reverse_proxy * sbbs {
    header_up Host {host}
    header_up X-Real-IP {remote_host}
    header_up X-Forwarded-For {remote_host}
    header_up X-Forwarded-Proto {scheme}
  }
}

https://roughneckbbs.com:11235 {
  reverse_proxy * sbbs:1123
}

www.roughneckbbs.com {
  redir https://roughneckbbs.com{uri}
}
theroughnecks.net {
  redir https://roughneckbbs.com{uri}
}
www.theroughnecks.net {
  redir https://roughneckbbs.com{uri}
}
roughneck.bbs.io {
  redir https://roughneckbbs.com{uri}
}

# Default http redirect to roughneckbbs.com https
:80 {
  redir https://roughneckbbs.com{uri}
}
```

**Comment by coolaj86** [comment]
What's the context here?

Is that part of the tls object? or policies? or what?

I'm assuming it's something like this?

```Caddyfile
example.com {
    tls {
        key_type rsa4096
    }
}
```

**Comment by coolaj86** [comment]
Found it: https://caddyserver.com/docs/caddyfile/directives/tls#key_type

(yes, my guess was correct)

I just wish search engines knew how to index Caddy documentation. I always end up here on the issues from the forums...

**Comment by mohammed90** [comment]
> Found it: https://caddyserver.com/docs/caddyfile/directives/tls#key_type
> 
> (yes, my guess was correct)
> 
> I just wish search engines knew how to index Caddy documentation. I always end up here on the issues from the forums...

The search field on the website (caddyserver.com/docs) is pretty good

**Pull request merged**
