### PR TITLE
reverseproxy: Pull latest proxy changes from stdlib

### PR DESCRIPTION
**Pull request by francislavoie**
I went through the commits that touched stdlib's `reverseproxy.go` file in the past couple of years (only a dozen or so), and copied over all the changes that are to code that was copied into Caddy.

The commits I pulled changes from (hopefully apparent from looking at those commits what the changes in this PR are doing):

- https://github.com/golang/go/commit/2cc347382f4df3fb40d8d81ec9331f0748b1c394
- https://github.com/golang/go/commit/a5cea062b305c8502bdc959c0eec279dbcd4391f
- https://github.com/golang/go/commit/ecdbffd4ec68b509998792f120868fec319de59b
- https://github.com/golang/go/commit/21898524f66c075d7cfb64a38f17684140e57675
- https://github.com/golang/go/commit/ca3c0df1f8e07337ba4048b191bf905118ebe251
- https://github.com/golang/go/commit/9c017ff30dd21bbdcdb11f39458d3944db530d7e

This may also fix https://github.com/caddyserver/caddy/issues/4247 because of the change to `copyResponse` to set `mlw.flushPending = true` right away. /cc @leafac if you'd be willing to try out this PR (you can grab a build from the CI artifacts, or build from this commit with `xcaddy`) to see if it fixes your usecase.

### CODE REVIEW

**Comment by leafac** [comment]
Oh, nice. I’ll give it a try. Thank you very much!

**Comment by mholt** [comment]
These changes look great, thanks Francis. The divergence from bugfixes upstream was something I was worried about. I'll wait to approve this until @leafac reports back whether it resolves his issue.

**Comment by mholt** [comment]
Should we wait for you, @leafac? (Thanks for trying it out, btw)

**Comment by leafac** [comment]
Yeah, sorry about taking too long to answer. I’ll test this first thing when I get to work. 😃

**Comment by leafac** [comment]
👍 I tested and I believe it’s working now 🙌

Thank you everyone for your work. You’re awesome!

---

Here’s what I did in more detail:

1. I went to [this page](https://github.com/caddyserver/caddy/pull/4266/checks?check_run_id=3233996581) which includes an artifact called ` caddy_macOS_go1.16_9c0cd66…`. I downloaded it.
2. I ran this version using my https://github.com/leafac/caddy-express-sse. This is the output I got

```
$ curl -Nv https://localhost    
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: [NONE]
*  start date: Aug 12 08:37:31 2021 GMT
*  expire date: Aug 12 20:37:31 2021 GMT
*  subjectAltName: host "localhost" matched cert's "localhost"
*  issuer: CN=Caddy Local Authority - ECC Intermediate
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x15300f800)
> GET / HTTP/2
> Host: localhost
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200 
< content-type: text/event-stream; charset=utf-8
< date: Thu, 12 Aug 2021 08:37:59 GMT
< server: Caddy
< x-powered-by: Express
< 
```

Note how the headers came right away.

**Comment by francislavoie** [comment]
Excellent! Thanks for confirming @leafac :tada:

**Review by mholt — APPROVED** [review]
Thanks for doing this, Francis!

**Pull request merged**
