### PR TITLE
this commit fixes the issue #6224

### LINKED ISSUE #6224: why not change the type map[string]bool to map[string]struct{} in importgraph.go file
i would like to propose a tiny code improvement, where we can change the **map[string]bool** type inside importgraph.go file to **map[string]struct{}** type and treat the nodes field of the **importGraph** struct just like a set.
caddy

### PR DESCRIPTION
**Pull request by danish-mehmood**
this fixes #6224

### CODE REVIEW

**Review by mholt — APPROVED** [review]
Thanks!

**Comment by mholt** [comment]
@danish-mehmood Can you please sign the CLA and then I can merge this in

**Comment by danish-mehmood** [comment]
@mholt done sir.

**Comment by danish-mehmood** [comment]
@mholt done

**Review by mholt — APPROVED** [review]
Thank you!

**Pull request merged**
