### PR TITLE
caddyhttp: Add content type to metrics

### PR DESCRIPTION
**Pull request by dtelyukh**

### CODE REVIEW

**Comment by hairyhenderson** [comment]
Hi @dtelyukh, thanks for the contribution!

Can I get some background on your use-case for this? I've never seen a good use-case for providing `content-type` as a label in metrics. This may be something that's more appropriate to scrape with logs, or for our future plans to integrate a distributed tracing mechanism.

Also, similar to the discussion in #3784, `content-type` may be a source of unbounded high-cardinality, which will cause issues when scraping with Prometheus over long periods of time and with larger deployments.

Finally, it's best to log an issue before working on a PR, to make sure that the reason makes sense. I won't close this right away, but we do need to understand the full context for this.

**Comment by dtelyukh** [comment]
The goal is to separate dynmaic and static resources, and there are two reasons for this:

1) Dynamically generated resources usually have way bigger TTFB, and mixing such resources with static files we obscure actual peaks in data, because each dynamically generated HTML document also pulls 10 to 100 static files. Content-type is a good heuristic for dynamic content, because html is usually dynamically generated, and everything else is static in most cases

2) No matter if html is dynamic or static, its performance is more critical for overall page load time, because it's the root document for the page, and each millisecond of its load time is always added to overall page load time, which is not always the case for page resources.

We intended to create two extra grafana panels, to be able to see metrics subsets that represent:
- html documents only
- small static files (js/css)
- large static files (images)

> our future plans to integrate a distributed tracing mechanism.

Tracing is a very useful method, but it's even more likely to get bloated when collecting data from all requests. I'd rather use metrics here, though I'm also interested in looking at tracing options. Might be a powerful method to diagnose slow requests.
Could you please point me at the discussion about tracing feature?

> similar to the discussion in #3784, content-type may be a source of unbounded high-cardinality

Totally agree! And thanks for pointing at that issue, it's very helpful. It probably makes sense to add a toggle for this feature. Also, I had a discussion with my colleagues about per-host metrics too, and we're interested in that feature too. I'll create an issue and link it here.

**Comment by hairyhenderson** [comment]
Thanks for your explanation @dtelyukh, it makes sense! I'll add some further comments on #4016

**Comment by francislavoie** [comment]
For the reasons mentioned already, I don't think this is the approach we want to take, so I'll close this for now. Discussion continues in #4016.

**Pull request closed without merging**
