### PR TITLE
caddytest: internalize init config into '.go' file

### PR DESCRIPTION
**Pull request by mohammed90**
Go module distribution excludes files that are not of a specific list of types. In other words,`.go` files are retained in the downloaded modules, but others are not for sure[^1]. This causes pain, e.g. #5187. The workaround in this PR is to write the init config to a temp file, and set the cleanup func to delete the file at the end of the test run.

For the record, I tried passing the init config t o`os.Stdin` by creating a `os.Pipe`, writing to the writer end, and setting `os.Stdin = reader`. However, this seems to slow down the run to the extent of test timeouts. It did work sometimes when the timeout value is set for very long period. It's probably a race condition. I don't believe forcefully going down that route is worth it. Writing the init config to a temp file is much simpler and easier to maintain, unless I'm blind to some aspect.

Updates #5187 

[^1]: I couldn't find a definite list of excluded files. If any knows of a reference, please share it!

### CODE REVIEW

**Comment by mohammed90** [comment]
@greenpau can you check this PR by depending on the branch `robust-integration-test`?

**Comment by greenpau** [comment]
> can you check this PR by depending on the branch robust-integration-test?

@mohammed90 , thank you for looking into it.

Added the following to `go.mod`:

```
replace github.com/caddyserver/caddy/v2 v2.6.2 => github.com/caddyserver/caddy/v2 v2.6.3-0.20221202133426-861c5c8268b7
```

Ran:

```
make test
```

I could see the test itself succeeds, b/c it gets to lines 59-60. https://github.com/greenpau/caddy-security/blob/cfc03c5f47313f4b2d6699193659f41040511b49/app_test.go#L59-L60

```
    app_test.go:59: &{200 OK 200 HTTP/2.0 2 0 map[Alt-Svc:[h3=":8443"; ma=2592000] Content-Length:[5] Content-Type:[text/plain; charset=utf-8] Date:[Sat, 03 Dec 2022 18:22:52 GMT] Server:[Caddy]] 0xc0002a1d20 5 [] false false map[] 0xc000d63600 0xc001158630}
    app_test.go:60: 1.0.0
    caddytest.go:128: unable to read the current config
```

But then `caddytest.go` throws an error:

```
caddytest.go:128: unable to read the current config
```

The config I am using is here https://github.com/greenpau/caddy-security/blob/cfc03c5f47313f4b2d6699193659f41040511b49/assets/config/Caddyfile

**Comment by mohammed90** [comment]
> > can you check this PR by depending on the branch robust-integration-test?
> 
> @mohammed90 , thank you for looking into it.
> 
> Added the following to `go.mod`:
> 
> ```
> replace github.com/caddyserver/caddy/v2 v2.6.2 => github.com/caddyserver/caddy/v2 v2.6.3-0.20221202133426-861c5c8268b7
> ```
> 
> Ran:
> 
> ```
> make test
> ```
> 
> I could see the test itself succeeds, b/c it gets to lines 59-60. https://github.com/greenpau/caddy-security/blob/cfc03c5f47313f4b2d6699193659f41040511b49/app_test.go#L59-L60
> 
> ```
>     app_test.go:59: &{200 OK 200 HTTP/2.0 2 0 map[Alt-Svc:[h3=":8443"; ma=2592000] Content-Length:[5] Content-Type:[text/plain; charset=utf-8] Date:[Sat, 03 Dec 2022 18:22:52 GMT] Server:[Caddy]] 0xc0002a1d20 5 [] false false map[] 0xc000d63600 0xc001158630}
>     app_test.go:60: 1.0.0
>     caddytest.go:128: unable to read the current config
> ```
> 
> But then `caddytest.go` throws an error:
> 
> ```
> caddytest.go:128: unable to read the current config
> ```
> 
> The config I am using is here https://github.com/greenpau/caddy-security/blob/cfc03c5f47313f4b2d6699193659f41040511b49/assets/config/Caddyfile

Your Caddyfile overrides the admin address, changing it from 2999 on first POST to 2019. That issue did occur to me, but I didn't figure out a solution to how to inject the correct admin port in client config. For now, just include `admin localhost:2999` in your global options.

**Comment by greenpau** [comment]
> Your Caddyfile overrides the admin address, changing it from 2999 on first POST to 2019. That issue did occur to me, but I didn't figure out a solution to how to inject the correct admin port in client config. For now, just include admin localhost:2999 in your global options.

@mohammed90 , the test passes now! 👍

**Review by sarge — APPROVED** [review]
Great find! @mohammed90

**Review by mholt — APPROVED** [review]
Thank you @mohammed90, nice workaround!

**Pull request merged**
