### PR TITLE
tests: uses testing.TB interface

### PR DESCRIPTION
**Pull request by jcchavezs**
This would allow us to run the test server for benchmarks too.

### CODE REVIEW

**Comment by jcchavezs** [comment]
Ping @mholt

**Comment by jcchavezs** [comment]
Ping @mholt @francislavoie

**Comment by francislavoie** [comment]
This is a backwards compatible change, right? Because `TB` is a superset of `T`?

**Comment by jcchavezs** [comment]
Yes, it won't break anything because both *testing.T and *testing.B implements that interface.

**Comment by francislavoie** [comment]
Actually you did change it to not be a pointer. I think this might be a breaking change for plugin authors.

I'm not against it, I just want us to be knowingly making that break if it is breaking.

**Comment by jcchavezs** [comment]
testing.TB is an interface, whoever uses this would have called

```
var t *testing.T
NewTester(t)
```

which remains working as expected. I changed the parameter type of the function to a superset so not a breaking change.

**Comment by jcchavezs** [comment]
I wanted to run a benchmark using this and then eneded up not doing it because it does not accept testing.B

**Review by mohammed90 — APPROVED** [review]
I think this is fine. The interface TB contains the common methods of T, B, and F for this purpose. Also there's compile-time check in Go source code to ensure *T implements TB, so we have the guarantee there.

https://cs.opensource.google/go/go/+/refs/tags/go1.22.0:src/testing/testing.go;l=905-906

**Comment by jcchavezs** [comment]
any chance you will cut a patch release anytime soon?

José Carlos Chávez


tir. 20. feb. 2024 kl. 23:04 skrev Mohammed Al Sahaf <
***@***.***>:

**Comment by francislavoie** [comment]
We still have a lot of PRs we went to review and merge before 2.8.0. No planned release time right now. You can pin to the commit on master for now if you need.

**Pull request merged**
