### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by successgo**

### CODE REVIEW

**Comment by francislavoie** [comment]
You know what, let's leave this PR open for a few days just in case you find some more that you can add to this PR 😅

**Comment by Mohammed90** [comment]
I believe our configuration of golangci-lint includes catching misspellings. You can run it at the root to see a full report of lint issues, misspellings and otherwise. If you use VSCode, you should see it in the bottom panel.

**Comment by successgo** [comment]
Thanks for your @Mohammed90 tips, I'm running Goland before, but I can try vscode tomorrow to check that.

**Comment by mholt** [comment]
@Mohammed90 Woah, really? I'm totally not seeing any misspellings reported in my VS Code. Do I need to do something to enable it?

**Comment by successgo** [comment]
I think it is ready now after checking all the source files.

**Comment by mholt** [comment]
Thank you @successgo for your contribution!

**Comment by Mohammed90** [comment]
@mholt if you set the lint tool (in Settings -> Preferences -> search for `lint` then pick Go from the list on the left) as `golangci-lint`, it'll use it to list out the findings in the `PROBLEMS` section in the bottom panel.

**Comment by mholt** [comment]
@Mohammed90 Thanks! I never knew that. This changes everything!

**Pull request merged**
