### PR TITLE
close quic connections when server closes

### PR DESCRIPTION
**Pull request by WeidiDeng**
Fix [6195](https://github.com/caddyserver/caddy/issues/6195).

### CODE REVIEW

**Review by mholt — APPROVED** [review]
LGTM. This is a good temporary solution I think. Thank you @WeidiDeng!!

**Comment by francislavoie** [comment]
This means that h3 requests get cancelled non-gracefully on reload, right? Doesn't that differ from how we typically handle reloads? Does that ignore the grace config in global options?

**Comment by mholt** [comment]
Yeah, I think so. I believe it is a TODO, waiting for a graceful close method upstream in quic-go.

I believe what this does -- correct me if I'm wrong @WeidiDeng -- is when a new HTTP request comes in on a server that was just closed, it will close the QUIC connection with the client. The socket remains open, however.

@marten-seemann Does that sound about right? Once a graceful close is implemented we should be able to allow existing requests to finish during a grace period I think?

**Comment by WeidiDeng** [comment]
Speaking of request interruption, I think my [previous approach](https://github.com/quic-go/quic-go/pull/4181) to interrupt a stream had the same problem (the quic connection is forcefully closed). I'll take a look at that and graceful shutdown when I have time.

**Comment by mholt** [comment]
Thanks Weidi, that'd be great :+1:

**Pull request merged**
