### PR TITLE
reverseproxy: Support grpc-web -> grpc bridge

### PR DESCRIPTION
**Pull request by mholt**
Related to #3997

This is spike code. I have not tested it. In theory, it should bridge grpc-web to grpc. Someone please try it out?

The upstream lib for this has kind of an awkward API (like, why are [functions like `IsGrpcWebRequest()` methods on a server type](https://pkg.go.dev/github.com/improbable-eng/grpc-web/go/grpcweb?utm_source=godoc#WrappedGrpcServer.IsGrpcWebRequest)?) but it looked simple enough to hack this together real quick.

@tetra12 could you please try this?

Also, @coolaj86 if you are interested.

Even if we get this working, I'm not 100% sure this will end up in this repo. It might become a plugin.

### CODE REVIEW

**Comment by francislavoie** [comment]
You can grab a build artifact from here https://github.com/caddyserver/caddy/actions/runs/2684481111

**Comment by tetra12** [comment]
@mholt Nah, didn't work out. Here's what I have

Caddyfile:
```bash
{
  debug
  # auto_https disable_certs

  servers {
    protocol {
      # We need to enable h2c in order to use grpc without TLS.
      # ref: https://caddy.community/t/caddy-grpc-h2c-passthrough/11780
      allow_h2c
    }
  }
}

http://localhost:5052 {

  reverse_proxy h2c://192.168.1.93:50051 {
    transport http {
      dial_timeout 5s
    }
  }
}

```

Log output:
```bash
DEBUG   http.handlers.reverse_proxy     selected upstream✔  101{"dial": "192.168.1.93:50051", "total_upstreams": 1}

DEBUG   http.handlers.reverse_proxy     upstream roundtrip  101{"upstream": "192.168.1.93:50051", "duration": 64.043839627, "request": {"remote_ip": "::1", "remote_port": "55780", "proto": "HTTP/1.1", "method": "OPTIONS", "host": "localhost:5052", "uri": "/greeter.Greeter/SayHello", "headers": {"Access-Control-Request-Headers": ["content-type,x-grpc-web"], "Sec-Fetch-Dest": ["empty"], "X-Forwarded-Proto": ["http"], "X-Forwarded-Host": ["localhost:5052"], "X-Forwarded-For": ["::1"], "Accept": ["*/*"], "Accept-Language": ["en-US,en;q=0.9"], "Access-Control-Request-Method": ["POST"], "User-Agent": ["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"], "Origin": ["http://localhost:9000"], "Sec-Fetch-Site": ["same-site"], "Sec-Fetch-Mode": ["cors"], "Accept-Encoding": ["gzip, deflate, br"], "Referer": ["http://localhost:9000/"]}}, "error": "stream error: stream ID 3; PROTOCOL_ERROR; received from peer"}
2022/07/18 13:50:43.302 ERROR   http.log.error  stream error: stream ID 3; PROTOCOL_ERROR; received from peer   {"request": {"remote_ip": "::1", "remote_port": "55780", "proto": "HTTP/1.1", "method": "OPTIONS", "host": "localhost:5052", "uri": "/greeter.Greeter/SayHello", "headers": {"Access-Control-Request-Headers": ["content-type,x-grpc-web"], "Accept-Encoding": ["gzip, deflate, br"], "Accept-Language": ["en-US,en;q=0.9"], "Sec-Fetch-Site": ["same-site"], "Sec-Fetch-Dest": ["empty"], "User-Agent": ["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"], "Referer": ["http://localhost:9000/"], "Access-Control-Request-Method": ["POST"], "Origin": ["http://localhost:9000"], "Sec-Fetch-Mode": ["cors"], "Connection": ["keep-alive"], "Accept": ["*/*"]}}, "duration": 64.0442512, "status": 502, "err_id": "h9v0x076x", "err_trace": "reverseproxy.statusError (reverseproxy.go:1217)"}
```

**Comment by tetra12** [comment]
@mholt Let me bake some hello world project with both backend and frontend, so that you could put your hand on that

**Comment by tetra12** [comment]
@mholt @francislavoie  Pls take a look :eyes: into my demo [project](https://github.com/tetra12/grpcweb-proxy). You can reproduce/debug/test Caddy config with my demo back and front.

Have a lot of fun :wink:

**Comment by mholt** [comment]
Thanks for setting up the demo project! That should help quite a bit. I'll try to get around to this, but I encourage other developers to dive in and see what is going on before I have a chance, as that will be faster.

**Comment by tetra12** [comment]
@mholt 
Here's what I got with this project: `"error": "stream error: stream ID 3; PROTOCOL_ERROR; received from peer"}`
I built `caddy` from the branch `grpc-web`

Full log:
```shell
2022/07/19 10:03:53.463 DEBUG   http.handlers.reverse_proxy     selected upstream       {"dial": "192.168.1.93:50051", "total_upstreams": 1}
2022/07/19 10:04:58.494 DEBUG   http.handlers.reverse_proxy     upstream roundtrip      {"upstream": "192.168.1.93:50051", "duration": 65.030756976, "request"
: {"remote_ip": "::1", "remote_port": "55822", "proto": "HTTP/1.1", "method": "OPTIONS", "host": "localhost:5052", "uri": "/greeter.Greeter/SayHello", "header
s": {"Sec-Fetch-Site": ["same-site"], "Accept-Encoding": ["gzip, deflate, br"], "User-Agent": ["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, lik
e Gecko) Chrome/103.0.5060.53 Safari/537.36"], "Origin": ["http://localhost:5173"], "X-Forwarded-Proto": ["http"], "X-Forwarded-Host": ["localhost:5052"], "Ac
cept": ["*/*"], "Access-Control-Request-Headers": ["content-type,x-grpc-web"], "Access-Control-Request-Method": ["POST"], "Sec-Fetch-Dest": ["empty"], "Sec-Fe
tch-Mode": ["cors"], "Accept-Language": ["en-US,en;q=0.9"], "Referer": ["http://localhost:5173/"], "X-Forwarded-For": ["::1"]}}, "error": "stream error: strea
m ID 3; PROTOCOL_ERROR; received from peer"}
2022/07/19 10:04:58.494 ERROR   http.log.error  stream error: stream ID 3; PROTOCOL_ERROR; received from peer   {"request": {"remote_ip": "::1", "remote_port"
: "55822", "proto": "HTTP/1.1", "method": "OPTIONS", "host": "localhost:5052", "uri": "/greeter.Greeter/SayHello", "headers": {"Connection": ["keep-alive"], "
Origin": ["http://localhost:5173"], "Sec-Fetch-Site": ["same-site"], "Accept": ["*/*"], "Access-Control-Request-Headers": ["content-type,x-grpc-web"], "User-A
gent": ["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"], "Sec-Fetch-Mode": ["cors"], "Accept-Enco
ding": ["gzip, deflate, br"], "Accept-Language": ["en-US,en;q=0.9"], "Access-Control-Request-Method": ["POST"], "Sec-Fetch-Dest": ["empty"], "Referer": ["http
://localhost:5173/"]}}, "duration": 65.03116185, "status": 502, "err_id": "9fg1fyerd", "err_trace": "reverseproxy.statusError (reverseproxy.go:1217)"}
^Cmake: *** [GNUmakefile:17: runfront] Interrupt
```

I also prepared TCP dumps for a single GPRC call for both native GRPC and GRPC-WEB with this project. 
You can check :eyes: dumps here: [pcap.zip](https://github.com/caddyserver/caddy/files/9140084/pcap.zip)

**Comment by tetra12** [comment]
I'm trying to make it work with Envoy. My grpcweb doesn't work as well. It seems l have an issue with my Web client. I'll keep you updated :roll_eyes:

**Comment by mholt** [comment]
Thanks for the update @tetra12 -- really appreciate this while I get caught up on a few other things. Interesting that it doesn't work with Envoy either... Please keep us posted!

**Comment by tetra12** [comment]
@mholt I finally made it work with Envoy :+1:! now I can easily generate proto stubs for TypeScript and Golang and use Envoy to reverse proxy and match protocols :100: . See the docs for the [demo](https://github.com/tetra12/grpcweb-proxy)

I wasn't able to make it work with Caddy thou :roll_eyes: For `caddy-2.5.2-alpine` my requests just hung and fail with the protocol error by timeout. For your feature-branch `grpc-web`, I'm getting `Protocol Error` reported above.

Leaving you to debug Caddy with a working example with Envoy

Have a lot of fun :smile:

**Comment by mholt** [comment]
@tetra12 Cool, thank you for verifying. Will look into it when we have a chance. But ultimately, someone with more gRPC/gRPC-web experience will be better for this!

**Comment by mholt** [comment]
@tetra12 I had trouble getting the demo to work; I'll open issues on your repo with questions/difficulties I had.

**Comment by tetra12** [comment]
Hi @mholt I responded there. You need to install the Protobuf Compiler first. I updated the README

**Comment by mholt** [comment]
@tetra12 

This branch works for me (using your demo). Setup:

gRPC backend listening on `:50051`

Caddy on `:5452` with this Caddyfile (modified slightly from yours, but only the listening port and backend host -- all other config the same!):

```
{
  debug

  servers {
    protocol {
      # We need to enable h2c in order to use grpc without TLS.
      # ref: https://caddy.community/t/caddy-grpc-h2c-passthrough/11780
      allow_h2c
    }
  }
}

http://localhost:5452

reverse_proxy h2c://127.0.0.1:50051 {
  transport http {
    dial_timeout 5s
  }
}
```

VITE listening on `:5173`.

In other words: `Browser :5173 --> Caddy :5452 --> backend :50051`

I open `localhost:5173` (VITE) in my browser and see this in the backend's output:

```
2022/07/28 17:01:19 Received: Friend
```


Caddy log:

```
2022/07/28 23:01:19.816	DEBUG	http.handlers.reverse_proxy	selected upstream	{"dial": "127.0.0.1:50051", "total_upstreams": 1}
2022/07/28 23:01:19.816	DEBUG	http.handlers.reverse_proxy	upstream roundtrip	{"upstream": "127.0.0.1:50051", "duration": 0.000631719, "request": {"remote_ip": "127.0.0.1", "remote_port": "36816", "proto": "HTTP/1.1", "method": "POST", "host": "localhost:5452", "uri": "/greeter.Greeter/SayHello", "headers": {"X-Grpc-Web": ["1"], "Sec-Fetch-Dest": ["empty"], "Sec-Fetch-Mode": ["cors"], "Accept-Language": ["en-US,en;q=0.5"], "Accept-Encoding": ["gzip, deflate, br"], "Referer": ["http://localhost:5173/"], "Cache-Control": ["no-cache"], "User-Agent": ["Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"], "Accept": ["application/grpc-web-text"], "Sec-Fetch-Site": ["same-site"], "X-Forwarded-For": ["127.0.0.1"], "X-Forwarded-Proto": ["http"], "X-Forwarded-Host": ["localhost:5452"], "Pragma": ["no-cache"], "Origin": ["http://localhost:5173"], "Content-Type": ["application/grpc"]}}, "headers": {"Content-Type": ["application/grpc"]}, "status": 200}
```

There are no errors in the browser console.

Note that it's using HTTP/1.1 to the frontend. I'm not sure if that's expected, but it seems like it's working?

If I switch to the master branch of Caddy, I see protocol errors.

If I do `cd back/client && go run main.go -addr :5452` (so that the validation program goes through Caddy instead of directly to grpc backend), I get this output:

```
$ go run main.go -addr :5452
2022/07/28 17:16:29 Greeting: Hello world
```
```
2022/07/28 17:16:29 Received: world
```

As far as I can tell, this is working.

**Comment by tetra12** [comment]
@mholt I'm happy :smile: that you came up with a working solution for a demo. However, this branch is still not working in our test env. I built a fresh `caddy` binary with the `grpcweb` branch and used the following Caddyfile:
```bash
example.com {
  tls email@example.com

  route /pock/* {
      uri strip_prefix /pock
      reverse_proxy h2c://0.0.0.0:5451 
  }

  route /drev/* {
      uri strip_prefix /drev
      reverse_proxy h2c://0.0.0.0:5452
  }

  root * /srv/example
  route {
    try_files {path} {path}/ /index.html
    file_server
  }
}
```

Now my website is timing out `curl` requests, giving the following error :disappointed: :
```bash
2022/07/29 17:45:10.939 INFO    tls.issuance.acme.acme_client   trying to solve challenge       {"identifier": "example.com", "challenge_type": "tls-alpn-01", "c
a": "https://acme-v02.api.letsencrypt.org/directory"}
2022/07/29 17:45:22.752 ERROR   tls.issuance.acme.acme_client   challenge failed        {"identifier": "example.com", "challenge_type": "tls-alpn-01", "problem":
 {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "x.x.x.x: Timeout during connect (likely firewall problem)", "instance": "", 
"subproblems": []}}
2022/07/29 17:45:22.752 ERROR   tls.issuance.acme.acme_client   validating authorization        {"identifier": "example.com", "problem": {"type": "urn:ietf:param
s:acme:error:connection", "title": "", "detail": "x.x.x.x: Timeout during connect (likely firewall problem)", "instance": "", "subproblems": []}, "orde
r": "https://acme-v02.api.letsencrypt.org/acme/order/652729016/111255177896", "attempt": 2, "max_attempts": 3}
```

No issues with firewall/website if I use the `caddy:v2.5.2-alpine` docker :roll_eyes:

**Comment by tetra12** [comment]
Same for `http` without `TLS`. It simply doesn't come up

**Comment by mholt** [comment]
@tetra12 That looks unrelated (thankfully) -- it means that a firewall or network misconfiguration is preventing the CA from validating your site, and can't issue you a certificate.

So make sure that ports 80 and 443 are open to the public and that they go directly to Caddy.

**Comment by tetra12** [comment]
@mholt As I wrote, firewall is off and the production docker works okay. At least it serves the static site without GRPC.
I can give you a time limited access. It's a preprod server, so not for everyone. Can I reach you privately? Telegram, Slack, WhatsApp are ok

**Comment by mholt** [comment]
@tetra12 Sure, but first I want to be sure that all DNS/firewall/external issues are resolved first, because normally I don't give help in private for free.

If the CA is unable to reach your server, then there's definitely a firewall or DNS or network problem that needs to be fixed first. It means Caddy can't get a cert for your site, and I need some evidence that things are all working and that it is in fact this branch that is broken. Because right now the evidence I have is that your network is misconfigured and this branch is working.

**Comment by mholt** [comment]
@tetra12 To be clear, I don't mean to come across like I'm fighting you on this or anything. I'm grateful for the demo which helped me verify things are working (at least for me). So that's why I want to dig down on this one and figure things out... I've done this enough times to know I don't want to spend time barking up the wrong tree first. That's all. :innocent:

**Comment by tetra12** [comment]
@mholt Thanks. I assembled a docker image from this branch to compare apples to apples. My traffic was again routed properly :smiley:  altho I still do not understand what is the difference :roll_eyes: 

And yes, it works ! My `grpcweb` frontend now does its job :100: 

This is  a valuable feature :heart: and is enabled by default in `Envoy`. So I recommend you to merge it to allow `grpcweb` use in both web and native apps :muscle: 

Thanks for your great support and for building and maintaining `Caddy`. I'll do my best to sponsor you and support this project in a longer run :nerd_face: :dollar: :moneybag:

**Comment by mholt** [comment]
Great! I am so relieved. Thanks for providing a demo and helping me get it running.

> This is a valuable feature heart and is enabled by default in Envoy. So I recommend you to merge it to allow grpcweb use in both web and native apps muscle

I want to, but I want to see how generally useful this is first. Wrapping an entire handler with an upstream dependency that's a bit opaque to me is a bit scary (especially to do this by default for all requests!) and it's basically a hard-no on that. We really try to avoid things like that because of potential problems that get out of our control. gRPC-web does seem to be fairly niche -- and I know, to one whose use case it is, it is never niche... but in the broad scheme of the Web, it is not used by for a majority of users IMO.

But I think what I will do is properly implement this feature as a handler module, rather than spiking it out in the reverse proxy like this. Then if a plugin is very popular and useful, or I am convinced the cost and maintenance burden of bringing it in by default is very low, we can always bring it into the standard distribution.

I'll tag you in the new repo so you can try it out!

>

**Comment by mholt** [comment]
It appears @tetra12 has deleted their GitHub account and all comments. That is unfortunate, as usually GitHub leaves the comments but puts the username as @ghost.

We have lost valuable historical discussion today, which makes me sad, as following the path of this feature's development will be difficult.

I have the demo repo cloned if anyone is interested in it.

**Comment by mholt** [comment]
Here is a link to the Caddy plugin that I created based on this experimental branch: **https://github.com/mholt/caddy-grpc-web**

I verified that it works using the demo repo supplied above.

If you'd like to convert gRPC-Web requests to normal gRPC, use the plugin. Thank you for everyone who made this possible! (Even if they did disappear. They will be missed...)

**Comment by alantbarlow** [comment]
Great job on this plugin, I still need to figure out how to get it implemented and test it out but it sounds awesome. This feature was the main thing making me need Envoy instead. Having an all gRPC backend makes this plugin required at the proxy level.

**Comment by mholt** [comment]
@alantbarlow I'm glad you are looking at Caddy, that's great news!

I want to address some of your feedback. I appreciate you took the time to write it.

> I was just a little disappointed that it isn't officially being supported by Caddy.

We can get to that point, but our typical process for stuff like this is to start it as a separate plugin and see how important/useful it is. Technically speaking, all plugins are equal: plugins from other repos are just as "first-class" as plugins in other repos. The only difference is which repository they're in.

Once we bring a plugin into our standard distribution, it's a huge commitment and maintenance burden. One problem with this one is that none of our core maintainers -- including me -- has a solid grasp of gRPC or its inner workings, let alone grpc-web. I don't use gRPC. I only threw this together because there's a library for it and after looking at its API I figured it would only take a few minutes to implement. (It took several hours, half of that was just setting up the test rig.) I know that gRPC uses HTTP/2 frames and often needs streaming configuration. But we would need a maintainer on our team who we can reliably call upon to build and maintain the grpc-web bridge feature if we were to "officially" support it. Another possible option is a company to sponsor the project for this feature. I can take the necessary time to learn it and maintain it, just like I have with several other features in Caddy. So, financial support or a commitment to contribute would be helpful here.

One other thing to consider is that the authors of the grpc-web library we're using recommended that we _not_ rely on this as a standard feature in Caddy: https://github.com/improbable-eng/grpc-web/issues/1117#issuecomment-1200334616 -- the library is in "maintenance mode" (which I guess means, still undergoing development, "works for us" kind of thing?) and they don't want to be expected to have a perfect, high-performing, bug-free implementation --  which I understand and respect.

That brings us to the next point: we do try to limit new dependencies in Caddy at this stage... they have been the source of some of our greatest headaches and most confusing hangups. A significant bug in a dependency can take longer to resolve since it's not really in our control, unless we want to assume total maintenance burden for it. Plus, builds take longer and sometimes dependencies prevent compiling entirely (see the [antlr debacle](https://github.com/caddyserver/caddy/issues/4331)).

That all being said, if the grpc-web plugin is a compelling enough feature that it causes enough companies to switch to Caddy and it proves to be useful enough to our user base -- and if someone with deep gRPC experience / then I can totally envision us proposing to bring it into the standard distribution. It may take months, or it may happen very quickly. It's up to you, the users, really: use Caddy, sponsor the project, and/or contribute to maintain it. That is how we will make grpc-web part of the standard Caddy distribution!

> I would love to see Caddy as a direct replacement for Envoy, but that would require this to be built-in like it is on Envoy.

Why is that? I would be interested in hearing more about your requirements.

Did you know that Caddy plugins are literally "built-in" no matter which repository they live in? All Caddy plugins are compiled into the native binary, so whether it's in this repo or that one, it's all the same! You can even click-click on our [Download page](https://caddyserver.com/download) to get just the build you require.

> Also the discoverability of caddy being an Envoy replacement needs to be improved. Envoy is currently the go-to proxy to work with gRPC because it was the first ones to implement this. Currently the Caddy documentation has limited information on how it works with gRPC. That, along with the lack of tutorials, makes it hard to discover the Caddy's true capabilities in this regard.

That's probably true! I never really advertised Caddy as such because I know Envoy is popular for its gRPC support. But now we have a plugin that does it, so maybe it's time to do so. (You'll notice that plugin has only been published for, like, a week. Very new!)

You may know that gRPC is just HTTP/2 frames, and Caddy has always supported HTTP/2. It even supports H2C (HTTP/2 over cleartext) and can shuttle gRPC just fine. So, implicitly, an HTTP/2 server and proxy should also support gRPC. Maybe we need to make that clear if people don't understand what gRPC is, that's a good idea! Perhaps I will add more "gRPC" and "grpc-web" keywords to our website.

**Comment by alantbarlow** [comment]
@mholt, I'd like to thank you for the detailed response. 

> Technically speaking, all plugins are equal: plugins from other repos are just as "first-class" as plugins in other repos.

I was just worried about it not being as discoverable or not being maintained properly as a repo published by caddy. But I completely understand waiting to see if the demand is there for it first. gRPC itself is not as well known, I just think there really needs to be an alternative to Envoy. I love how Caddy handles HTTPS by default and Envoy does not even offer a way to do something similar.

> Why is that? I would be interested in hearing more about your requirements. Did you know that Caddy plugins are literally "built-in" no matter which repository they live in?

You are completely right, it doesn't really matter if it's a plugin or built in as long as it works the same. As for my requirements Im just wanting my entire backend to use gRPC and allow Caddy to work in-between the browser and my backend to convert  any REST API calls into gRPC ones.

> You may know that gRPC is just HTTP/2 frames, and Caddy has always supported HTTP/2. It even supports H2C (HTTP/2 over cleartext) and can shuttle gRPC just fine.

I am unexperienced at this stuff myself and am still experimenting with it but I wanted to make sure all traffic is handled through TLS (HTTPS). I believe this means we are required to use H2 instead of H2C. Do you happen to know if this works well with Caddy? I just wanted to make sure since you didn't mention it here.

**Comment by mholt** [comment]
@alantbarlow Thanks for the follow-up!

> I was just worried about it not being as discoverable or not being maintained properly as a repo published by caddy.

Totally understand that -- I promise that as long as your company with interest in gRPC-web sponsors Caddy at a Business/Business+ tier or higher, the gRPC-web module will be well-maintained.

>  I love how Caddy handles HTTPS by default

It's cool, huh :smiley:

> You are completely right, it doesn't really matter if it's a plugin or built in as long as it works the same. As for my requirements Im just wanting my entire backend to use gRPC and allow Caddy to work in-between the browser and my backend to convert any REST API calls into gRPC ones.

Perfect. Yeah, I would see the example config in the plugin's README. It should have all you need. One line of config to bridge gRPC-web and another to do the proxying.

> I am unexperienced at this stuff myself and am still experimenting with it but I wanted to make sure all traffic is handled through TLS (HTTPS). I believe this means we are required to use H2 instead of H2C. Do you happen to know if this works well with Caddy? I just wanted to make sure since you didn't mention it here.

Absolutely -- Caddy uses HTTPS+HTTP/2 automatically, you don't have to worry or think about it! Just make sure to configure Caddy with your real domain name (after you've pointed your A/AAAA records at it):

```
{
    order grpc_web before reverse_proxy
}

example.com

grpc_web
reverse_proxy 127.0.0.1:5050
```

That's all you need for the most minimal config.

**Comment by tetra12** [comment]
@mholt Hello my friend, I'm back :100: :smile: GitHub has marked my account as a spammer and couldn't resolve that for three weeks :roll_eyes: 

I'm happily using the Caddy branch with `grpc-web` support in my pre prod env :muscle: 

Is there any chat room for Caddy devs? :thinking: Keep in touch!

**Comment by mholt** [comment]
@tetra12 Back from the spamban! Awesome :smile: 

Glad to hear you are using it successfully, thanks for the update!

Sometimes people chat on Discord, but it's not really an official place. We do have an official forum: https://caddy.community -- which we prefer since it's searchable and archivable, etc.

**Pull request closed without merging**
