### PR TITLE
Add support for fsnotify plugin

### PR DESCRIPTION
**Pull request by awoodbeck**
### 1. What does this change do, exactly?
This PR, in conjunction with https://github.com/awoodbeck/caddyfile-fsnotify, adds the ability to monitor the Caddyfile and its imported files for changes.  If changes are detected, Caddy is signaled to reload, realizing the changes to the Caddyfile and/or imports.

The changes to Caddy's code base were as unobtrusive as I could make them.  I took care not to break the API with the exception of changing `[]ServerBlock` to `ServerBlocks` in order to facilitate the compilation of a unique file list.  The `ServerBlocks` object is passed along in a new `EventHook` named `CaddyfileParsedEvent`.  The caddyfile-fsnotify loader receives the `ServerBlocks` from the event and uses it to register those files with fsnotify.  The loader then watches for fsnotify events, sending a `syscall.SIGUSR1` to Caddy as appropriate.

I have not exhaustively tested the caddyfile-fsnotify plugin, but it passed my initial QA.  There are edge cases with the loader I'd like to explore.  The Caddy-specific changes all include test coverage and the entire test suite passes.  Hopefully these changes can at least push this longstanding issue forward.

### 2. Please link to the relevant issues.
#1806 

### 3. Which documentation changes (if any) need to be made because of this PR?
I'm not aware of any, though I admittedly spent more time looking at the code than the docs.

### 4. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by awoodbeck** [comment]
Also, it may be necessary to vendor https://github.com/fsnotify/fsnotify in caddy, but I'm not entirely sure how to proceed with a Caddyfile loader's dependencies.

**Comment by mholt** [comment]
Thanks for the PR, we will look at it as soon as we can.

**Comment by awoodbeck** [comment]
I'm not sure why AppVeyor is using Go 1.11 despite merging in the changes from master that updated the yaml file to use Go 1.12. I won't have time to look at this any time soon. I'll leave the PR open in case someone wants to make AppVeyor happy and/or review the code.

**Comment by mholt** [comment]
We just have to wait for AppVeyor to update their image. :(

**Comment by joeblew99** [comment]
azure pipelines now :)

**Comment by mholt** [comment]
Caddy 2 will make this feature much easier to implement, since configuration is not forced through the Caddyfile anymore. If this PR is to be merged, I would like to devote efforts to making this work in Caddy 2 instead. Since it has a REST API and supports various config modules, it should be pretty easy to make this work in Caddy 2: just use fsnotify to watch the Caddyfile for changes, and if it changes, call Load(). Might be a grand total of 100 lines of code (including module registration)?

Would you be interested in that?

**Comment by awoodbeck** [comment]
I'll familiarize myself with the v2 code base when I have an opportunity.

**Pull request closed without merging**
