### PR TITLE
chore: Bump otel to v1.21.0.

### PR DESCRIPTION
**Pull request by dlorenc**
This requires a few coordinated bumps to get right.

There are a few CVEs in otel that flag scanners, they're probably not applicable here in caddy but the bump helps keep the entire Go ecosystem moving forward anyway.

### CODE REVIEW

**Comment by mohammed90** [comment]
I'm failing to find confirmation one way or another. Is the update and release connected to resolving some vulnerability? Or is it just routine update?

**Comment by dlorenc** [comment]
> I'm failing to find confirmation one way or another. Is the update and release connected to resolving some vulnerability? Or is it just routine update?

Both kind of! There have been a few CVEs patched in otel, they almost definitely don't apply to caddy's usage though. This is mostly just a routine update.

**Review by mohammed90 — APPROVED** [review]
Fair enough. Thanks!

**Comment by dlorenc** [comment]
Thanks for merging!

**Comment by dkarlovi** [comment]
@mohammed90 scanners pick up [GHSA-rcjv-mgp8-qvmr](https://github.com/advisories/GHSA-rcjv-mgp8-qvmr) in Caddy 2.7.5 which is the latest available release so a new release might be considered since this has been merged and probably fixes it?

```NAME                                                           INSTALLED  FIXED-IN  TYPE       VULNERABILITY        SEVERITY 
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp  v0.42.0    0.44.0    go-module  GHSA-rcjv-mgp8-qvmr  High```

**Comment by francislavoie** [comment]
This is already merged.

Scanners will always have false positives. We can't spend our time chasing scanners with new releases, especially when the vulnerabilities don't apply to Caddy anyway.

Please build from the master branch if you must have a build with these changes. Otherwise please be patient, we'll release when we're ready to.

**Comment by dlorenc** [comment]
We have a build published at cgr.dev/chainguard/caddy which has these fixes applied, feel free to use that in the meantime! I sent this PR after releasing ours.

**Pull request merged**
