### PR TITLE
caddytls: Add Caddyfile support for `propagation_timeout`

### LINKED ISSUE #4177: add propagation_timeout support in caddyfile
For some slow DNS providers there is a need for supporting `propagation_timeout` to `UnmarshalCaddyfile`

### PR DESCRIPTION
**Pull request by kmpm**
- Closes #4177

### CODE REVIEW

**Comment by francislavoie** [comment]
Please add a Caddyfile adapt test https://github.com/caddyserver/caddy/tree/master/caddytest/integration/caddyfile_adapt

**Review by mholt — APPROVED** [review]
Awesome, thanks for the test case!

**Comment by mholt** [comment]
@francislavoie Should we merge this into master or the 2.5 branch?

**Comment by francislavoie** [comment]
There's no breaking change here, just adds a config property that wasn't there before, so it's no problem if it lands in 2.4.2 👍

**Review by mholt — APPROVED** [review]
Thank you!

**Pull request merged**
