### PR TITLE
cmd: `caddy fmt` return code is 1 if not formatted

### LINKED ISSUE #5294: Allow returning 1 if lint fails
Right now we have

```shell
Usage:
  caddy fmt [flags]

Flags:
      --diff        Print the differences between the input file and the formatted output
  -h, --help        help for fmt
      --overwrite   Overwrite the input file with the results
```

I originally thought `caddy fmt` will return `1` if failed like most other linters. It turns out not. It returns formatted content instead.
If we don't want to change the behavior of `caddy fmt`, it would be great to provide another flag to allow returning `1` for failure. Thanks! 😃

### PR DESCRIPTION
**Pull request by u5surf**
* Fixes #5294
* return exit 1 with an error message

### CODE REVIEW

**Comment by mholt** [comment]
Awesome, thanks for this patch.

I was just thinking, our Caddyfile adapter does print a warning if the input isn't formatted, and the output is a little more useful:

https://github.com/caddyserver/caddy/blob/223cbe3d0b50487117c785f0755bb80a9ee65010/caddyconfig/caddyfile/adapter.go#L66-L93

Do you think we could incorporate this? Maybe we export that function and use it in `caddy fmt` to give the user more information.

**Comment by u5surf** [comment]
> https://github.com/caddyserver/caddy/blob/223cbe3d0b50487117c785f0755bb80a9ee65010/caddyconfig/caddyfile/adapter.go#L66-L93
> 
> Do you think we could incorporate this? Maybe we export that function and use it in `caddy fmt` to give the user more information.

@mholt Hi, thanks reviewing and sorry for late. I was exported and used `caddyfile.FormattingDifference`.

**Review by mholt — APPROVED** [review]
Awesome, LGTM. Thanks for the contribution!

**Comment by u5surf** [comment]
@mholt  Hi, could you confirm to be able to merge it? I seems that it might had been lost in your sight after approving it🙏

**Review by mholt — APPROVED** [review]
Oops! Yes, sorry. Thank you for the contribution again :blush:

**Pull request merged**
