### PR TITLE
Trying to figure out what path's being used on Windows

### PR DESCRIPTION
**Pull request by hairyhenderson**
Just trying to help debug #2782 ... maybe this'll help 😂

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by Mohammed90** [comment]
Mere logging won't show because we're piping the test output to a file to generate the test report. Sorry. You'll have to fiddle with the `azure-pipelines.yml` file.

**Comment by hairyhenderson** [comment]
@Mohammed90 it did show!

```
parse_test.go:608: file path is "C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\TestImportedFilesIgnoreNonDirectiveImportTokens612079831"
```

**Comment by francislavoie** [comment]
Seems like a Caddyfile parser bug!

**Comment by mholt** [comment]
Oh -- awesome, thanks for the progress!

**Comment by mholt** [comment]
Thankfully I was able to reproduce this on a Mac by putting a `\` in the filename

**Comment by francislavoie** [comment]
For ref, fixed in https://github.com/caddyserver/caddy/pull/2782/commits/d8bb6574a59ff7d401010a71bad9a75527b05b7c

**Pull request closed without merging**
