### PR TITLE
update quic-go to v0.14.0

### PR DESCRIPTION
**Pull request by marten-seemann**
v0.14.0 supports draft-24.

### CODE REVIEW

**Comment by marten-seemann** [comment]
draft-25 will be intended for deployment, so the QUIC working group can collect some real-world data. It will probably ship early next year.

Do you have any instrumentation in Caddy that could yield some useful results in that regard?

**Comment by mholt** [comment]
Great, that's good to hear.

> Do you have any instrumentation in Caddy that could yield some useful results in that regard?

We used to via telemetry, but then everyone freaked out about it so we don't have it anymore, sadly.

**Comment by marten-seemann** [comment]
So we’ll have QUIC support based on the hunch that it will be faster, but won’t have any data to verify that it actually is?
That makes me sad.

**Comment by mholt** [comment]
Correct 😞

**Pull request merged**
