### PR TITLE
chore: Update quic-go for go 1.17 support

### PR DESCRIPTION
**Pull request by assistcontrol**
Quic-go is somewhat obnoxious in that it must be updated every time a new go is released. This should fix the caddy build on go 1.17.

### CODE REVIEW

**Comment by francislavoie** [comment]
Thanks!

I think you may need to run `go mod tidy`. See the linter error.

**Comment by assistcontrol** [comment]
> Thanks!
> 
> I think you may need to run `go mod tidy`. See the linter error.

Oops! Done.

**Comment by francislavoie** [comment]
Thanks! Looks like that fixed it.

**Review by mholt — APPROVED** [review]
Cool, thanks very much!

**Pull request merged**
