### PR TITLE
ci: Upgrade to Go 1.15

### PR DESCRIPTION
**Pull request by francislavoie**

### CODE REVIEW

**Comment by francislavoie** [comment]
@mholt I was just curious whether we could try CI on unstable Go versions, and it seems to work... but the tests fail:

```
github.com/lucas-clemente/quic-go/internal/handshake.init.2()
	/home/runner/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.17.3/internal/handshake/unsafe.go:26 +0x569
FAIL	github.com/caddyserver/caddy/v2/modules/caddyhttp/headers	0.042s
?   	github.com/caddyserver/caddy/v2/modules/caddyhttp/map	[no test files]
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState
```

Is this something we can fix while keeping backwards-compat?

**Comment by francislavoie** [comment]
The binaries aren't much smaller - 2MB on linux, 3MB on mac. :thinking:

**Comment by mholt** [comment]
Should be? Just looking from the error message it comes from a file that appears to use the unsafe package, so there's probably some voodoo that needs updating. @marten-seemann would know! I'm sure they'll support Go 1.15 once it's released...

**Comment by mholt** [comment]
@marten-seemann Would you be able to ping us when there's a new release that's compatible with Go 1.15? (We're getting test failures on Go 1.15 in the quic-go lib)

**Comment by marten-seemann** [comment]
@mholt Yes, definitely. Will be some time later this week. I was planning to cut a new release of quic-go soon anyway - there've been a bunch of bug fixes and - which is important for Caddy - improvements to the QPACK compression efficiency.

**Comment by francislavoie** [comment]
Thanks @marten-seemann! I think that issue looks to be fixed with the latest release.

There is this new test failure though:

```
modules/caddyhttp/reverseproxy/fastcgi/client_test.go:252:24: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
modules/caddyhttp/reverseproxy/fastcgi/client_test.go:269:24: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL	github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy/fastcgi [build failed]
```

**Comment by mholt** [comment]
Cool, that error is a new feature of the Go 1.15 compiler.

Anyway, thanks Marten and Francis!

**Pull request merged**
