### PR TITLE
Re-remove admin fuzz target from azure-pipelines.yml

### PR DESCRIPTION
**Pull request by Mohammed90**
## 1. What does this change do, exactly?

Fixing a git-oopsie on my behalf. Oddly enough, Github didn't report the line being re-added in the previous PR.

## 2. Please link to the relevant issues.

N/A

## 3. Which documentation changes (if any) need to be made because of this PR?

N/A

## 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by mholt** [comment]
Ah, is this why all the targets on the last fuzz are in a "failed" state? (fuzzit isn't showing the logs to me for some reason, just infinitely loading)

**Comment by Mohammed90** [comment]
Nope, this landed before the scheduled run. The failure is due to something else, and I also have the same issue with the indefinite loading.

**Comment by mholt** [comment]
@yevgenypats - wondering if you could help us figure out what is going on that the logs aren't showing up in our dashboards?

**Comment by yevgenypats** [comment]
hey @mholt looks like this was a partial problem of the github/creation-account bug. I think this works now. I duplicated one of the jobs and looks like it running you can do the same for the others. https://app.fuzzit.dev/orgs/caddyserver-gh/targets/caddyfile-adapter/pyAgwv2oTCf3WUoXvtt4

**Comment by Mohammed90** [comment]
Thanks, @yevgenypats! That's a beautiful sight

**Comment by yevgenypats** [comment]
@Mohammed90 sure! feel free to ping again if you hit any more issues:)

**Pull request merged**
