### PR TITLE
Fix `string does not match ~[]E` error

### LINKED ISSUE #5674: Custom Caddy build with module relying on `httpcaddyfile` doesn't compile
After upgrading to `v2.7.0` and running CI with Go 1.20.7, I get the following error:

```
Error: ../../../go/pkg/mod/github.com/caddyserver/caddy/v2@v2.7.0/caddyconfig/httpcaddyfile/httptype.go:358:24: string does not match ~[]E
```

Also see: https://github.com/hslatman/caddy-crowdsec-bouncer/actions/runs/5744901364/job/15572008214?pr=18#step:5:167

I see the same behavior on my mac.

The change seems to have been introduced in https://github.com/caddyserver/caddy/commit/5c51c1db2ce450a3fa003834097ad010b3844673.

### PR DESCRIPTION
**Pull request by hslatman**
Fixes #5674

### CODE REVIEW

**Comment by mholt** [comment]
What is this exactly? I do not get this error, nor does our CI, and builds succeeded.

**Comment by hslatman** [comment]
Yea, I was kind of surprised myself too.

I hit this error when building Caddy with one of my modules. Another person seems to have hit the same issue with a custom module: #5673

**Review by mholt — APPROVED** [review]
Huh. Alrighty then.

LGTM. I'm not sure why we need the exp package here anyway. Thanks

**Comment by francislavoie** [comment]
Does the import need updating? (Run go mod tidy)

**Comment by hslatman** [comment]
> Does the import need updating? (Run go mod tidy)

Doesn't look like it. Still one `slices` usage.

**Comment by mholt** [comment]
Weird that only this occurrence needs changing then.

As I do not get this error, nor does our CI, I'm trusting you on this 😊

**Comment by hslatman** [comment]
Here's a reproducer on the playground: https://go.dev/play/p/NsaynrOjz9i

**Comment by mholt** [comment]
Is that using the same commit of x/exp that is in our go.mod?

**Comment by francislavoie** [comment]
Oh, I guess it needs to be `slices.Sort[[]string](s)` i.e. with the `[]`. Did go 1.20 not error on that? Strange.

**Comment by hslatman** [comment]
> Oh, I guess it needs to be `slices.Sort[[]string](s)` i.e. with the `[]`. Still don't understand why it didn't fail for us before though.

That does compile on the playground 🙂

**Comment by mholt** [comment]
If the playground always uses the latest commits, ours is not using the latest commit of x/exp. That might be the difference, somehow?

**Comment by hslatman** [comment]
Maybe this commit is related: https://github.com/golang/go/commit/0a48e5cbfabd679eecdec1efa731692cd6babf83

**Pull request merged**
