### PR TITLE
caddytls: Configure trusted CAs from PEM files

### LINKED ISSUE #3563: [FEATURE][v2]: Add support to load client authentication CA certs from file
Right now we need to hardcode the `trusted_ca_certs` in base64 format in the config. Just as we are able to load certificates from files in the `apps.tls.certificates.load_files`, it would be nice to do the same for the `trusted_ca_certs` when using client authentication. 

```json
"tls_connection_policies": [{			
    "client_authentication": {
        "trusted_ca_certs": [""],
        "trusted_leaf_certs": [""],
        "mode": ""
    },
}]
```

### PR DESCRIPTION
**Pull request by mholt**
Closes #3563

@danlsgiga would you be able to give this a shot? I just whipped this up real quick and it's a pretty straightforward change. Let me know if this is helpful for you.

(I don't yet have Caddyfile support implemented. Do you need that?)

### CODE REVIEW

**Comment by mholt** [comment]
Test failure seems sporadic and unrelated. Hmm.

**Comment by danlsgiga** [comment]
I can surely validate it by EOW ;) Thanks tons for pushing this!

**Comment by danlsgiga** [comment]
Beautiful! This is working just fine in my integration environment! ;) Consider it ready to merge from my end and thanks once again!

**Comment by mholt** [comment]
Awesome, thanks so much for confirming!

**Pull request merged**
