### PR TITLE
httpcaddyfile: Add global option for `storage_clean_interval`

### PR DESCRIPTION
**Pull request by francislavoie**
Followup to https://github.com/caddyserver/caddy/commit/42b7134ffa3bf3e9e86514c82407979c2627a5ab

### CODE REVIEW

**Review by mholt — APPROVED** [review]
This looks good. Thanks for the contribution! I'm sure someone will appreciate it. /cc @jackellis :wink:

**Comment by JackEllis** [comment]
Woah. So is this buildable from that UI on the website @mholt / @francislavoie? I’ve got to update my guides if so 😎

**Comment by francislavoie** [comment]
Not quite yet, but it will be with our v2.4.0 stable release.

**Comment by JackEllis** [comment]
@francislavoie Very cool. I'll update my video & article when done :)

**Pull request merged**
