### PR TITLE
cmd: Export the TLS storage last modified time as well.

### PR DESCRIPTION
**Pull request by jum**

### CODE REVIEW

**Comment by francislavoie** [comment]
Please explain why this change is necessary.

And please don't forget to sign the CLA.

**Comment by mholt** [comment]
IIRC, CertMagic may use the LastMod time to determine the most recent key in a list. I don't think this change is bad, and might actually be useful/correct, so that all keys are not restored to the same LastMod date.

**Comment by mholt** [comment]
@jum if the CLA is signed in the next couple hours I can merge this in and release it with v2.7.6.

**Comment by mholt** [comment]
I don't think so, you have to sign in with GitHub to agree. Here's the link: https://cla-assistant.io/caddyserver/caddy?pullRequest=5968

**Review by mholt — APPROVED** [review]

**Comment by jum** [comment]
> Wait are you at sea!? Like on a cruise?

Yes indeed, back in cell phone coverage today and have signed the thing.

**Pull request merged**
