### PR TITLE
implement brotli compression

### PR DESCRIPTION
**Pull request by paolobarbolini**
This PR adds the option to compress responses with brotli when the client supports it.

### CODE REVIEW

**Comment by mholt** [comment]
Thanks for the contribution!

Any reason this has to be included as a default plugin though? (I'm of the impression that brotli is slower at compressing than gzip, thus resources should be pre-compressed before serving responses.)

**Comment by mholt** [comment]
Thanks for all your work on this.

This has been added to Caddy 2, however we found that the encoder is extremely slow. Like, waaay slow causing network requests to hang. It's still available in Caddy 2 but its use will probably be discouraged in favor of pre-compressing assets with brotli until encoder performance improves. As such, it probably shouldn't be a standard module (it may not be bundled in Caddy 2 by default either; we'll see).

**Comment by nanmu42** [comment]
May be give [github.com/google/brotli/go/cbrotli](https://pkg.go.dev/github.com/google/brotli/go/cbrotli?tab=doc) a try?

**Comment by mholt** [comment]
No, because it uses cgo. We need a pure-Go brotli encoder.

**Comment by Azareal** [comment]
https://github.com/valyala/fasthttp/issues/798 There have been some big perf improvements over the past week, you may want to take another look at it when the release comes out.

**Pull request closed without merging**
