### PR TITLE
support function map for custom template of browse

### PR DESCRIPTION
**Pull request by snowcrumble**
I have a requirement to use github.com/Masterminds/sprig/v3.hasSuffix function in my custom static browse template file.

### CODE REVIEW

**Comment by francislavoie** [comment]
This is related to https://github.com/caddyserver/caddy/issues/3637

I think we'd rather do this "right" and have the logic that provides the functions to `file_server browse` and to `templates` be the same.

Do you think you could try to do that instead? It's more work, but it would solve an existing issue we have.

Thanks!

**Comment by snowcrumble** [comment]
Thanks for prompt reply. 

I'm new to caddy and I just looked #3637, then I scan related codes and I found there are two kinds of functions,  sprig's and templateContext's. The requirements of both issues is support functions in FileServer. To avoid problem of packages circle dependencies, we may create a new package for this functions.  What I confused is whether the templateContext's functions is useful in `FileServer`, cause a FileServer seems like need no `Req *http.Request` and `Args []interface{}` fields. My point is if it's not useful, the `github.com/Masterminds/sprig/v3` package is the "new" the package, so my changes is a resolution for this requirements. What do you think?

**Comment by mholt** [comment]
> Ok, we needs to refactor! To avoid problem of packages circle dependencies, we may create a new package for this functions.

Why would it be circular? The `caddyhttp/fileserver` package already imports the `caddyhttp/templates` package. And what you're looking to add is a templates feature to the file server, right? So I don't think that would be a problem, unless I'm misunderstanding something.

**Comment by francislavoie** [comment]
@snowcrumble do you still plan to continue work on this?

**Comment by mholt** [comment]
Closing due to inactivity. Willing to reopen later if interest resurfaces!

**Pull request closed without merging**
