### PR TITLE
core: MkdirAll appDataDir in InstanceID with 0o700

### PR DESCRIPTION
**Pull request by akovalenko**
appDataDir components should be searchable (u+x) when they are created, or else Caddy is unable to start with an empty HOME.

### CODE REVIEW

**Comment by akovalenko** [comment]
Fixes #6341

**Comment by mholt** [comment]
Thank you for the contribution! I'm still having trouble reproducing the original issue but as soon as we figure that out I'll merge this. (I actually feel this is right but I want to understand why I don't have the problem.)

**Review by mholt — APPROVED** [review]
While I'm still not able to reproduce this nor do I really understand who this affects, it's clearer to me now that this is more correct. Thanks for the patch.

**Comment by manselmi** [comment]
@akovalenko Thank you for this PR!  I was also affected by this and thought I was loosing it…

**Pull request merged**
