### PR TITLE
reverseproxy: Rewrite requests and responses for websocket over http2

### PR DESCRIPTION
**Pull request by WeidiDeng**
Supports reverse proxying h2 websockets to backends. Fix [5565](https://github.com/caddyserver/caddy/issues/5565).

Requires upstream support, but can be tested with `xcaddy build reverse-proxy-h2-websocket --replace golang.org/x/net=github.com/WeidiDeng/net@websocket-http2`

### CODE REVIEW

**Comment by bt90** [comment]
I'm not 100% sure but a regular HTTP/2 GET request should contain the new setting parameter as outlined in [RFC8441 Section 3](https://datatracker.ietf.org/doc/html/rfc8441#section-3)?

```
[0-0] == Info: [HTTP/2] [0] ingress: read 45 bytes
[0-0] == Info: [HTTP/2] [0] <- FRAME[SETTINGS, len=36]
[0-0] == Info: [HTTP/2] [0] MAX_CONCURRENT_STREAMS: 250
[0-0] == Info: [HTTP/2] [0] ENABLE_PUSH: TRUE
[0-0] == Info: [HTTP/2] [0] notify MAX_CONCURRENT_STREAMS: 250
[0-0] == Info: [HTTP/2] [0] -> FRAME[SETTINGS, len=18]
[0-0] == Info: [HTTP/2] [0] -> FRAME[SETTINGS, ack=1]
[0-0] == Info: [HTTP/2] [0] -> FRAME[WINDOW_UPDATE, incr=1048510465]
[0-0] => Send SSL data, 5 bytes (0x5)
0000: 17 03 03 00 5a                                  ....Z
[0-0] => Send SSL data, 1 bytes (0x1)
0000: 17                                              .
[0-0] == Info: [HTTP/2] [0] egress: wrote 73 bytes
[0-0] == Info: [HTTP/2] cf_connect() -> 0, 1,
[0-0] == Info: using HTTP/2
[0-0] == Info: [HTTP/2] [1] OPENED stream for https://xxxxxxx.xxx/
```

Tested via curl:

```sh
curl --trace request.dump --trace-config http/2 https://example.com
```

**Comment by WeidiDeng** [comment]
i'm not sure about curl debug dump. But I tested this with my Chrome and it works. The setting frame is send at the start of a new http2 connection, so it's sent regardless of the method client uses.

Even without my patch, golang http2 sends the following settings:

image

The output doesn't list all of them.

**Comment by bt90** [comment]
Successfully tested in Firefox :+1: 

Bildschirmfoto vom 2024-10-05 11-38-26

**Comment by WeidiDeng** [comment]
Upstream merged in [9a51899](https://github.com/golang/net/commit/9a518991035b3a8f23c03004d4db041a7fa6c06f). Waiting for the next release.

**Review by mholt — APPROVED** [review]
Thanks for working on this Weidi! Cool feature. I am not sure I 100% fully understand every line of this, but after a scan I don't see any red flags that stick out to me.

**Comment by WeidiDeng** [comment]
golang/x/net v0.32.0 is [out](https://github.com/golang/net/releases/tag/v0.32.0).

**Comment by bt90** [comment]
Is this a simple version bump which could be done in this PR or are there any side effects?

**Comment by WeidiDeng** [comment]
It's in another [pr](https://github.com/caddyserver/caddy/pull/6728).

**Comment by francislavoie** [comment]
So this is ready to merge @WeidiDeng ?

**Comment by WeidiDeng** [comment]
Yes  @francislavoie

**Review by mholt — APPROVED** [review]
Thanks Weidi. Let's give it a shot!

**Comment by JeDaYoshi** [comment]
I updated to latest `master` which included this commit, and it broke WebSocket reverse-proxying towards an HTTP/1.1 backend for me on Firefox.
`The connection to wss://[...] was interrupted while the page was loading.`

**Comment by bt90** [comment]
See #6733

**Comment by WeidiDeng** [comment]
@JeDaYoshi try `xcaddy build encode-connect` to see if it's fixed, or use the following request matchers

```
@not_h2_ws not {
    header :protocol *
    method CONNECT
    protocol http/2
}
encode @not_h2_ws zstd gzip
```

**Comment by JeDaYoshi** [comment]
I should check PRs/issues properly before commenting things out.. My apologies.

@WeidiDeng `encode-connect` / #6738 seems to be working for me.

**Pull request merged**
