### PR TITLE
ci: don't exit early on error in remote CI machine

### PR DESCRIPTION
**Pull request by mohammed90**
GitHub Actions shell scripts are loaded with `set -e`, which tells the shell to exit at any error. The impact on our flow is missing the deletion step of the code for every failed CI run on the remote machine. This PR fixes it so No Files Left Behind.

### CODE REVIEW

**Comment by mholt** [comment]
Ah, so this'll help prevent disk space depletion? Or if these are ephemeral instances do we need to do the cleanup?

**Comment by mohammed90** [comment]
> Ah, so this'll help prevent disk space depletion?

Yep, but it's just a copy of the repo at the subject commit, not that much.

> Or if these are ephemeral instances do we need to do the cleanup?

It isn't an ephemeral machine. It's the IBM machine.

**Comment by dunglas** [comment]
Maybe should this be done only on IBM machines to prevent running useless steps on ephemeral containers in other cases?

**Comment by mohammed90** [comment]
> Maybe should this be done only on IBM machines to prevent running useless steps on ephemeral containers in other cases?

It is only on the IBM machine. It's in the s390x-test job. That job only runs on a specific machine.

**Review by dunglas — APPROVED** [review]

**Pull request merged**
