### PR TITLE
ci: Build and test on Go 1.17, bump minimum to 1.16

### PR DESCRIPTION
**Pull request by francislavoie**
Used https://github.com/caddyserver/caddy/pull/4024 as a template. Pretty much the same change, different versions.

### CODE REVIEW

**Comment by francislavoie** [comment]
FYI just before merging, the repo should be updated to make the 1.17 jobs required, and make the 1.15 job no longer required.

**Comment by francislavoie** [comment]
To be considered: should we start building for Windows ARM64, or at least add it to the cross-build test?

**Review by Mohammed90 — APPROVED** [review]
The build is successful and nothing in the release notes (https://golang.org/doc/go1.17) impacts the go.{mod,sum} files to where the project won't build. Thanks for tackling this, Francis!

**Review by mholt — APPROVED** [review]
Required CI checks have been updated to shift out 1.15 for 1.17.

@francislavoie We have had several requests for Windows ARM 64, so we should consider building for it I think. Doesn't have to be in this PR though.

**Pull request merged**
