### PR TITLE
update README.md to be HTML5 compliance

### PR DESCRIPTION
**Pull request by BaldrVivaldelli**
This pull request updates the HTML markup from version 4 to version 5. It replaces deprecated attributes and elements with modern equivalents, enhancing accessibility and semantic meaning. The migration also ensures compliance with current web standards, improving the overall performance and maintainability of the code.

### CODE REVIEW

**Comment by francislavoie** [comment]
Pretty sure `<div>` doesn't work in Github Markdown. See https://github.com/BaldrVivaldelli/caddy/blob/master/README.md, nothing is centered.

**Comment by BaldrVivaldelli** [comment]
Download the pr and check it out

**Comment by BaldrVivaldelli** [comment]
> Download the pr and check it out. The vscode, and also the idea, said its deprecated. Maybe its because my IDE.

**Comment by francislavoie** [comment]
The purpose is for rendering in Github, we don't really care how it looks in VSCode.

**Pull request closed without merging**
