### PR TITLE
chore: Build with Go 1.20, keep minimum at 1.18 for now

### LINKED ISSUE #4294: HTTP3 + `strict_sni_host` always results in `403` status
I use `curl -I --http3 https://localhost/index`

when strict_sni_host off, status is 200 from reverse_proxy
when strict_sni_host on, status is 403 from caddy

my Caddyfile:

```
{
	auto_https disable_redirects

	servers {
		protocol {
			experimental_http3
			strict_sni_host
		}
	}
}

localhost {
	reverse_proxy localhost:3000
}
```

### PR DESCRIPTION
**Pull request by francislavoie**
As a nice side-effect, this also fixes #4294 via upgrading quic-go

### CODE REVIEW

**Comment by francislavoie** [comment]
@mholt we'll need to update the CI required job names

**Comment by francislavoie** [comment]
Blocked on quic-go releasing a version that builds on 1.20 (or we could pin to a commit, idk)

**Comment by francislavoie** [comment]
Hmm... what the heck:

```
=== RUN   TestSanitizedPathJoin
    caddyhttp_test.go:90: Test 8: SanitizedPathJoin('/a/b', '/..%2fbar') =>  '\a\bar' (expected '\a\b\bar')
    caddyhttp_test.go:90: Test 9: SanitizedPathJoin('/a/b', '/%2e%2e%2fbar') =>  '\a\bar' (expected '\a\b\bar')
    caddyhttp_test.go:90: Test 10: SanitizedPathJoin('/a/b', '/%2e%2e%2f%2e%2e%2f') =>  '\\' (expected '\a\b\')
--- FAIL: TestSanitizedPathJoin (0.00s)
```

**Comment by francislavoie** [comment]
With help from the Go team, they pointed out that we weren't really using the right function for cleaning the path. See https://github.com/golang/go/issues/56336#issuecomment-1416214885

**Comment by francislavoie** [comment]
We still have races on integration tests. 

`TestAutoHTTPRedirectsWithHTTPListenerFirstInAddresses`

```
    caddytest.go:99: failed to load config: {"error":"loading config: loading new config: http app module: start: listen udp :9443: bind: address already in use"}
```

**Review by mohammed90 — APPROVED** [review]
LGTM! Wanna add a note about the use of `IsLocal` to #5288 or should I?

**Comment by francislavoie** [comment]
Ah right, good point. Yeah, go ahead if you'd like :+1:

**Review by mholt — APPROVED** [review]
Awesome, thanks for the patch!

**Pull request merged**
