### PR TITLE
Add dark color scheme media query

### PR DESCRIPTION
**Pull request by radiden**
Adds a dark color scheme if the user's browser prefers one.

Tried to keep to the original's design as well as I could, any propositions are welcome.

### CODE REVIEW

**Comment by simaotwx** [comment]
Personally, I would make the dotted lines more transparent and the background colors a bit darker.
Other than that, looks really good to me!

image

**Comment by mholt** [comment]
This is cool! I agree it could use a little polish with the lines and textbox. It feels almost too high contrast at the moment.

**Comment by radiden** [comment]
Thank you for your feedback! I have implemented the changes.

**Comment by francislavoie** [comment]
@radiden do you mind sharing a screenshot of how it looks with your changes?

**Comment by simaotwx** [comment]
@radiden I tested it locally. Here's a screenshot:
image

I would change following things:

```
@media (prefers-color-scheme: dark) {
  .meta {
    border-bottom: 1px solid #212121;
  }
  #filter {
    border: 1px solid #212121;
  }
  tr {
    border-bottom: 1px dashed rgba(255, 255, 255, 0.12);
  }
}

```

@francislavoie what do you think?
Would look like this:
image

**Comment by francislavoie** [comment]
I agree, thanks @simaotwx!

**Comment by simaotwx** [comment]
You're welcome :smile:

**Comment by radiden** [comment]
Thank you @simaotwx! It looks amazing now. Attaching a screenshot of how it looks with your tweaks again.

screenshot

**Comment by simaotwx** [comment]
I'm glad you like it! Looks good to me now! Thank you @radiden

**Review by francislavoie — APPROVED** [review]

**Review by mholt — APPROVED** [review]
Beautiful! Thanks.

**Comment by dausruddin** [comment]
Is it possible to force light or dark theme and ignore users' preferred settings without modifying the source?

**Comment by francislavoie** [comment]
Yes, you can provide your own template file, and modify it to your liking.

You can copy the template from https://github.com/radiden/caddy/blob/master/modules/caddyhttp/fileserver/browsetpl.go and save it to a file, modify it, then specify the path to the template file in the `file_server` directive's `browse` option. https://caddyserver.com/docs/caddyfile/directives/file_server

**Comment by dausruddin** [comment]
Thank you! Your solution works :)

**Pull request merged**
