### PR TITLE
goreleaser: add s390x and ppc64le builds for linux

### PR DESCRIPTION
**Pull request by grooverdan**
dan@fstn4-p1:~/go/src/github.com/caddyserver/caddy/cmd/caddy$ file ./caddy 
./caddy: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.10.0, BuildID[sha1]=1fc956e7b143268aec43dd6850e6af65562ed412, not stripped

dan@fstn4-p1:~/go/src/github.com/caddyserver/caddy/cmd/caddy$ ./caddy version
(devel)

dan@fstn4-p1:~/go/src/github.com/caddyserver/caddy/cmd/caddy$ ./caddy build-info
path: github.com/caddyserver/caddy/v2/cmd/caddy
main: github.com/caddyserver/caddy/v2 (devel) 
dependencies:
cloud.google.com/go v0.54.0 h1:3ithwDMr7/3vpAMXiH+ZQnYbuIsh+OPhUPMFC9enmn0=
...

Builds and runs seamlessly here (ppc64le, haven't tested s390x).

### CODE REVIEW

**Comment by mholt** [comment]
Thanks -- do you actually have a common/critical use case for Caddy on these architectures? We're trying to add only architectures that will be needed by more than, like, 4 people.

**Comment by grooverdan** [comment]
Hey Matthew,

As Red Hat released their [OCP-4.2](https://docs.openshift.com/container-platform/4.2/installing/installing_ibm_z/installing-ibm-z.html#ibm-z-network-connectivity_installing-ibm-z) for Z recently and [POWER OCP](https://docs.openshift.com/container-platform/3.11/install/prerequisites.html#hardware) has been there for a while and continues to be developed shows a need for container based cloud service. IBM's 34B$ acquisition of Red Hat will continue delivering a cloud capable platform on all its hardware products. IBM's customers do want a set of quality products like caddy on their hardware on an equal basis. IBM customers of Z/POWER running clouds is significantly more than 4 and while their exact requirements aren't always disclosed, premium web servers undoubtedly form part of this.

Some preventive delivery of products through the support of the open source communities ensures that when asked/looked, the product is there and ready. As a pure go project caddy is well equipped to deliver this with minimal maintenance. There is already ongoing development of golang for Power and Z hardware on Linux to ensure the supply side of this continues to provide quality.

I recognise that I'm giving a cold call PR to enable this functionality sometime comes across as a webcrawler approach to ecosystem enablement however you can ask for help in resolving issues.

I appreciate the opportunity to describe how important caddy can be for cloud/container users of all IBM hardware (>4). I'd really appreciate a small grace in getting a multiarchitecture product available in advance on an absolute list of users ready to go. If the stats don't add up later or the maintenance burden increase, I'll hold no grudges against its removal.

**Comment by hairyhenderson** [comment]
@mholt FWIW, I think this is a decent idea, and if this is merged, I can very easily add support for these platforms to the official Docker image.

**Comment by mholt** [comment]
I am willing to merge this after the 2.0 release.

**Comment by grooverdan** [comment]
Thank you @mholt, @Mohammed90, @hairyhenderson and everyone else. You are a very pleasurable community to work with.

**Comment by hairyhenderson** [comment]
Syntax seems to have been invalid:

```console
$ TAG=$(git describe --abbrev=0) goreleaser release --skip-publish --rm-dist --skip-validate
   • releasing...     
   • loading config file       file=.goreleaser.yml
   ⨯ release failed after 0.00s error=yaml: unmarshal errors:
  line 38: cannot unmarshal !!seq into string
  line 41: cannot unmarshal !!seq into string
```

I'm working on a PR right now to fix this 😉

**Pull request merged**
