### PR TITLE
fileserver: Fix browse name_dir_first sorting

### PR DESCRIPTION
**Pull request by diamondburned**
This pull request fixes browse's default template to make `name_dir_first` sorting work.

The fix is basically a minor typo fix, changing `namedirfirst` in the template to `name_dir_first` to reflect `sortByNameDirFirst = "name_dir_first"`.

### CODE REVIEW

**Comment by francislavoie** [comment]
I think the better fix would be to change the `sortByNameDirFirst` variable's value to `namedirfirst`, because some users will have copied the template to customize it. Changing the variable would also fix it for those users, whereas changing the template in Caddy would only fix it for users who didn't copy the template.

**Comment by francislavoie** [comment]
@diamondburned Do you have time to address my comment? Thanks!

**Comment by diamondburned** [comment]
> @diamondburned Do you have time to address my comment? Thanks!

I've made this change, though I still have some second thoughts about it, mostly because the `browse` template that I wrote ended up using `name_dir_first` for the form, so existing templates would likely have to make the fix once this is merged.

**Comment by francislavoie** [comment]
Well you're the first person whose reported it, so I have high doubts anyone else would have fixed it in the same way you did.

I'm not so concerned for people who may have fixed it in their own apps and not reported the issue, because that's not being a good user of open source software.

I'm more concerned about users who copied the template and changed _other_ things but left that the same, which will be the vast majority of people who copied templates in total. Like probably everyone except you in that group of people.

Thanks for reporting and it for the fix! 😀

**Review by francislavoie — APPROVED** [review]

**Pull request merged**
