### PR TITLE
v1: Allow empty files to be imported

### PR DESCRIPTION
**Pull request by bhcleek**
* add tests for an empty file
* return nil from `lexer.load` when the file is empty

This is #3414 for v1, too.

### CODE REVIEW

**Comment by francislavoie** [comment]
Can you confirm the tests run locally?

CI is kinda busted on the v1 branch, so you can probably ignore that, as long as the tests pass locally.

**Comment by bhcleek** [comment]
Yeah, the tests pass locally. I verified that the tests fail in the commit that adds them and then the tests pass in the second commit.

**Comment by bhcleek** [comment]
@mholt it would probably be surprising to users to have this fixed on v1, upgrade to v2 and have this regress. Can I convince you to bring it into v2, too?

**Comment by mholt** [comment]
@bhcleek It's a pretty niche requirement, yours is the only use case I've heard of, and it doesn't use v2.

Let's wait and see if there are compelling reasons to put it into v2 as well. (I can't find it, but again, I seem to recall users reporting problems with empty files due to some misconfig in their system or environment, and reporting an error was a good thing. I might be wrong but my sense is tingling.)

**Pull request merged**
