### PR TITLE
reverse_proxy: apply keep-alive setting for h2c requests

### PR DESCRIPTION
**Pull request by WeidiDeng**
Fix [6342](https://github.com/caddyserver/caddy/issues/6342).

### CODE REVIEW

**Comment by mholt** [comment]
Thanks Weidi! As I understand it, this depends on an upstream patch first?

**Comment by WeidiDeng** [comment]
Yes, or else h2c will stop working if keep alive is disabled. For now it's buggy behaviour, but it works 🤷 .

**Comment by WeidiDeng** [comment]
Just wait for the release of [golang/x/net](https://github.com/golang/net/commit/9617c6335bca5e4e80949a5b1dbe43273260e8a3). It's fixed in the master.

**Comment by mholt** [comment]
Great! Will do :smile:

**Comment by mholt** [comment]
Great - thanks for the ping! And the patch :)

**Pull request merged**
