### PR TITLE
cli: Change command structure, add help subcommand (#328)

### PR DESCRIPTION
**Pull request by aca**
## 1. What does this change do, exactly?
Changed command structure to generate cli guide in formatted way.
Provides usage message and help message for each command.
Copied documents from wiki. Maybe we can make it in more 'automated way'.
But I think It will be too complicated for now.

```
$ caddy (or 'caddy help')
Caddy, The HTTP/2 Web Server with Automatic HTTPS.

Usage: 

    caddy <command> [<args>]

Available commands:

    adapt-config  Adapts a configuration to Caddy's native JSON config structure
    environ       Prints the environment as seen by caddy
    list-modules  Prints the modules that are installed
    reload        Gives the running Caddy instance a new configuration
    run           Starts the Caddy process, blocks indefinitely
    start         Starts the Caddy process, blocks until server initiated
    stop          Gracefully stops the running Caddy process
    version       Prints the version

Use "caddy help [command]" for more information about a command.
```
```
$ caddy help start
usage: caddy start [--config <path>] [--config-adapter <name>]

Starts the Caddy process, optionally bootstrapped with an initial
config file. Blocks until server is successfully running (or fails to run),
then returns. On Windows, the child process will remain attached to the
terminal, so closing the window will forcefully stop Caddy. See run for more
details.

Full documentation available on 
https://github.com/caddyserver/caddy/wiki/v2:-Documentation
```

## 2. Please link to the relevant issues.
#328 

## 3. Which documentation changes (if any) need to be made because of this PR?
Needs to add "help" subcommand.

### CODE REVIEW

**Comment by aca** [comment]
@mholt 
I tried not to but I ended up making command structure to generate formatted output.
Maybe too much?. Should I just add help subcommand?.

**Comment by mholt** [comment]
Ooo, nice! I can't wait to look this over. I'm going to sleep but I'll look at this shortly. :+1:

**Comment by aca** [comment]
> The help subcommand should itself be a command in the list/map of other subcommands.

I think you mean we should make a "help" subcommand just like other subcommands. (correct me if my understanding is wrong)
There is some circular initialization problem in current implementation. I'll try to fix it.

> Our CLI docs should only provide just enough in...

I also think it is better to focus on online documents. I'll try rephrasing, but I'm not native english speaker. Might need help for this.

> Any particular reason we aren't using the command's FlagSet? ...

I also think it will be great. I marked it 'TODO' https://github.com/aca/caddy/blob/cff8fb673bc981bd45e8567a24886ec254273fb5/cmd/main.go#L70
I just wanted to make sure you are ok with this kind of changes.

I'll try to fix it. Just needs little more time (too busy at work..)

**Comment by mholt** [comment]
> I'll try rephrasing, but I'm not native english speaker. Might need help for this.

No problem, I will be happy to tweak the text before merging.

**Comment by mholt** [comment]
I'm working on this today and tomorrow; will be pushing some tweaks and then merging it in.

**Comment by mholt** [comment]
@aca This pull request was very good. It was a big change, thank you for investing the time in it!

After going through your changes in great detail, I got some inspiration and made what I feel are improvements. They're pretty significant, but I feel better about this overall. I love the templates you made for the help text; I kept them but didn't use the templates package this time.

I'm going to go through and work on the CLI more tomorrow, including adding examples and making the help text more helpful in-situ.

Thanks for this! It's a great improvement that I'm pleased to roll out with the next beta! I hope you'll contribute again.

**Pull request merged**
