### PR TITLE
fileserver: Fix handling of symlink sizes in directory listings

### LINKED ISSUE #4411: 2.4.6 regression: presence of symlink breaks file_server browse
It seems that if a symlink exists in a directory, that directory's contents can't be viewed with the browser.  The error is 404.  It happens with valid and broken symlinks.  2.4.5 does not have this issue.

### PR DESCRIPTION
**Pull request by jjlin**
Fixes #4411.

### CODE REVIEW

**Comment by mcguirepr89** [comment]
Hello, @jjlin
>  Also, it would probably be better to move this discussion over to #4415 since your issue is really with that specific implementation.
 
> It's a bit difficult to determine what's really going wrong without access to your environment.

I'm happy to provide remote access to this environment -- simply provide an email address for correspondence and I will gladly allow access for further investigation. (NoMachine is already installed on the machine for remote access).

> Could you maybe pare down your directory structure and config to create a minimal reproducible example? 

If you would prefer I put together a minimal reproducible example over the actual environment, I can do that instead.

**Comment by jjlin** [comment]
@mcguirepr89 You can email me at `<firstname>.<lastname>@gmail.com`.

**Comment by mcguirepr89** [comment]
@jjlin deserves a great deal of gratitude for this patience with me -- I did not build this using the correct branch. Thank you so much for your time and I do apologize again for taking it needlessly.

My best regards,
Patrick

**Comment by mcguirepr89** [comment]
I can verify that fix-symlink-size resolved my issue

**Review by mholt — APPROVED** [review]
Thank you for the patch :)

**Pull request merged**
