### PR TITLE
metrics: move `metrics`  up, outside `servers`

### LINKED ISSUE #6604: with per_host in metrics, how about compatible with old version
current caddyfile is using:
{
	servers {
		metrics {
		
		}
	}
}

if i switch to caddy@master with per_host in metrics, then above config will cause panic!! because missing :port (ie servers :80, servers :443 )

### PR DESCRIPTION
**Pull request by mohammed90**
This change moves the metrics configuration from per-server level to a single config knob within the `http` app. Enabling `metrics` in any of the configured servers inside `http` enables metrics for all servers.

Fix #6604

### CODE REVIEW

**Review by francislavoie — APPROVED** [review]

**Comment by aa-shalin** [comment]
any idea when this will be merged? I ran into this issue after i was advised to use the [beta version of Caddy](https://github.com/caddyserver/caddy/issues/6481#issuecomment-2414510538)

**Review by mholt — APPROVED** [review]

**Comment by erikschul** [comment]
This looks wrong to me.

I argue that it's reasonable to want to enable a metrics route for a specific server (e.g. `:9000`), and not serve it on all servers (including public ones). Metrics generally aren't made publicly available.

**Comment by francislavoie** [comment]
This isn't about serving metrics it's about enabling metrics.

**Comment by erikschul** [comment]
Okay; if it's technically complicated, maybe a better approach is to keep the metrics internal to `:2019/metrics` and then use
```
route /metrics {
    reverse_proxy localhost:2019/metrics
}
```
wherever you want to expose it?

**Comment by francislavoie** [comment]
I think you're confused. There's a `metrics` _http handler_ and a `metrics` _global option_. The former is to _server_ the metrics (from any endpoint you want, none by default obviously, except for the admin endpoint) and the latter is to _enable HTTP metrics_. This PR is about moving the global option _only_.

**Comment by mohammed90** [comment]
> Okay; if it's technically complicated, maybe a better approach is to keep the metrics internal to `:2019/metrics` and then use
> 
> ```
> route /metrics {
>     reverse_proxy localhost:2019/metrics
> }
> ```
> 
> wherever you want to expose it?

You're confusing 2 things: enabling HTTP handling metrics collection and exposure/serving on the admin endpoint, and exposing metrics on an endpoint other than the admin endpoint. Enabling metrics here (in this PR), means enabling the  HTTP traffic metrics collection. They're exposed only on admin endpoint (default: `:2019/metrics`). To expose metrics on an endpoint other than the admin endpoint, you'd use the [`metrics` handler](https://caddyserver.com/docs/caddyfile/directives/metrics).

Previously (before this PR), enabling HTTP metrics collection was done by adding the key `metrics` in the JSON inside a particular "server" (see the empty `metrics` object on this page: https://caddyserver.com/docs/json/apps/http/). Image for posterity:

image

This is misleading because metrics were always enabled for all servers, plus a bunch of other issues. The fix requires lifting the `metrics` object to be direct descendant of `http` (outside `servers`) because the collection of HTTP metrics is either enabled for all servers or none. `server` in this context means a logical group of listeners with unified behavioral pattern, not referring to Caddy as a whole. If you want HTTP metrics, it's enabled on the HTTP app, not "per server", so this PR is correct.



> wherever you want to expose it?

Use the [`metrics` handler](https://caddyserver.com/docs/caddyfile/directives/metrics) for this. 



> I think what confuses me is the line `s.Metrics = nil`.
> because I would think that this means that the metrics are disabled for each server?

That's not the correct interpretation, not that it was ever possible anyways. Nil-ing the field doesn't change the behavior. The line you're looking at is about adapting the old configuration to the new one. Once we copied the configuration, the older data is no longer meaningful because it's not used. We only need it there for existing users who haven't changed their config. We don't want to suddenly break them, so I added a translation.



> a) the individual server configuration is no longer possible (deleted)

It never was. There's a label for the server name to track which "server" it's part of. As a caddyfile user, you'll rarely have to deal with the notion of server, unless you serve sites on multiple ports other than 80/443.

> b) the global configuration enables metrics globally, overwriting the setting with the last value of the iteration:

Nothing is lost anyways. The field `PerHost` is only introduced in 2.9.0-beta. The lines you're looking at ensure that if the user still used the older field, and they happen to set `per_host` to `true` in any of their servers, the value is carried globally.

**Comment by erikschul** [comment]
Thanks @mohammed90  for the explanation! I'm new to the project but I hope I'll find ways to contribute as I get more involved. Thanks again!

**Pull request merged**
