### PR TITLE
Fix: unix build in v2

### PR DESCRIPTION
**Pull request by Dreamacro**
## 1. What does this change do, exactly?

Add some missing import to fix build on my macOS

## 2. Please link to the relevant issues.

None

## 3. Which documentation changes (if any) need to be made because of this PR?

None

## 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by mholt** [comment]
Huh, thanks!

/cc @tobya - FYI

**Comment by tobya** [comment]
hmmm.  Do we need to set up CI builds on azure for this branch.  Should they not be automatic?

**Comment by mholt** [comment]
We do, although I haven't been able to get it to work yet. I just wanted to let you know so that you can make sure the program compiles before you push. :+1:

**Comment by tobya** [comment]
I found this https://github.com/mitchellh/gox which should make it easier to check cross compiles

**Pull request merged**
