### PR TITLE
update the fuzzer target name for the address parser

### PR DESCRIPTION
**Pull request by Mohammed90**
## 1. What does this change do, exactly?

The func to parse the network address was `ParseListenerAddress`. It was changed at some point to `ParseNetworkAddress`. This PR updates the name on the fuzz target so it's more descriptive and easily tracked.

## 2. Please link to the relevant issues.

N/A

## 3. Which documentation changes (if any) need to be made because of this PR?

N/A

## 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by Mohammed90** [comment]
Umm... @mholt `modules\caddyhttp\reverseproxy\httptransport.go:123:12: undefined: http2
modules\caddyhttp\reverseproxy\httptransport.go:123: undefined: http2 in http2.ConfigureTransport` ?

**Comment by mholt** [comment]
Nevermind, sorry, my git-fu is failing; I forgot to commit an import statement. Try again with the latest.

**Comment by Mohammed90** [comment]
Nope. It also fails in CI on the v2 branch (check the README badge). Is the http2 supposed to be a named import? I checked the file on the repo here too, and `http2` seems missing, whatever it is.

https://github.com/caddyserver/caddy/blob/v2/modules/caddyhttp/reverseproxy/httptransport.go

**Comment by Mohammed90** [comment]
Perfect

**Pull request merged**
