### PR TITLE
reverseproxy: Set origreq in active health check

### LINKED ISSUE #5281: Can I use the php-fpm ping (via unix socket) as heathcheck ?
My Caddyfile (v2.6.2) :
```
localhost

route {
    root * /srv/app/public
    php_fastcgi unix//var/run/php/php-fpm.sock {
        health_uri /ping
    }
}
```

The error :

```json
"msg":"active health check panicked",
"error":"interface conversion: interface {} is nil, not http.Request
```

<details>
<summary>full log</summary>

```json
{"level":"error","ts":1672826972.5459127,"logger":"http.handlers.reverse_proxy.health_checker.active","msg":"active health check panicked","error":"interface conversion: interface {} is nil, not http.Request","stack":"goroutine 374 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).doActiveHealthCheckForAllHosts.func1.1()\n\tgithub.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/reverseproxy/healthchecks.go:180 +0xe9\npanic({0x1a2baa0, 0xc00016a690})\n\truntime/panic.go:884 +0x212\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy/fastcgi.Transport.buildEnv({{0x1cae8ea, 0x10}, {0xc0006fa500, 0x1, 0x4}, 0x0, 0x0, 0xb2d05e00, 0x0, 0x0, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go:276 +0x14e5\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy/fastcgi.Transport.RoundTrip({{0x1cae8ea, 0x10}, {0xc0006fa500, 0x1, 0x4}, 0x0, 0x0, 0xb2d05e00, 0x0, 0x0, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go:126 +0x125\nnet/http.send(0xc000261400, {0x7fa1f2908bb0, 0xc00018b880}, {0x1c09440?, 0x4caa01?, 0x2dc30e0?})\n\tnet/http/client.go:251 +0x5f7\nnet/http.(*Client).send(0xc000860e70, 0xc000261400, {0x0?, 0xc00054f2d8?, 0x2dc30e0?})\n\tnet/http/client.go:175 +0x9b\nnet/http.(*Client).do(0xc000860e70, 0xc000261400)\n\tnet/http/client.go:715 +0x8fc\nnet/http.(*Client).Do(...)\n\tnet/http/client.go:581\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).doActiveHealthCheck(0xc0009ed860, {0x0, {0xc0009eb120, 0x4}, {0xc0009eb125, 0x19}, {0x0, 0x0}, {0x0, 0x0}}, ...)\n\tgithub.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/reverseproxy/healthchecks.go:295 +0x7dd\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).doActiveHealthCheckForAllHosts.func1(0xc000871380)\n\tgithub.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/reverseproxy/healthchecks.go:220 +0xa1e\ncreated by github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).doActiveHealthCheckForAllHosts\n\tgithub.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/reverseproxy/healthchecks.go:175 +0x38\n"}
```

</details>

<details>
<summary>php fpm-config</summary>

```ini
[www]
listen = /var/run/php/php-fpm.sock
listen.mode = 0666
ping.path = /ping
```

</details>

### PR DESCRIPTION
**Pull request by mholt**
Fix #5281 - hopefully :)

Can you test this out, @maidmaid? There are CI artifacts you can download to make it easier.

### CODE REVIEW

**Comment by maidmaid** [comment]
Hi @mholt, thank you very much ! I don't see any artifacts to download for the test. Where are they ?

**Comment by francislavoie** [comment]
Artifacts are at the bottom of the page here: https://github.com/caddyserver/caddy/actions/runs/3840083975

Or you can build it yourself with `xcaddy build 1ad624d0` (the commit hash of the latest commit on this pull request).

**Comment by maidmaid** [comment]
It seems the same error is occurring :

```
ERROR	http.handlers.reverse_proxy.health_checker.active	active health check panicked	{"error": "interface conversion: interface {} is *http.Request, not http.Request", "stack": "goroutine 29 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).doActiveHealthCheckForAllHosts.func1.1()\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy/healthchecks.go:180 +0xe9\npanic({0x18d4300, 0xc0002d6870})\n\truntime/panic.go:884 +0x212\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy/fastcgi.Transport.buildEnv({{0x1b34ea0, 0x10}, {0xc00035b100, 0x1, 0x4}, 0x0, 0x0, 0xb2d05e00, 0x0, 0x0, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go:276 +0x14e5\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy/fastcgi.Transport.RoundTrip({{0x1b34ea0, 0x10}, {0xc00035b100, 0x1, 0x4}, 0x0, 0x0, 0xb2d05e00, 0x0, 0x0, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go:126 +0x125\nnet/http.send(0xc000115600, {0x7f556637b888, 0xc0001d6850}, {0x1a96760?, 0x4c9701?, 0x2b5c800?})\n\tnet/http/client.go:251 +0x5f7\nnet/http.(*Client).send(0xc0003657d0, 0xc000115600, {0x0?, 0x40d95f?, 0x2b5c800?})\n\tnet/http/client.go:175 +0x9b\nnet/http.(*Client).do(0xc0003657d0, 0xc000115600)\n\tnet/http/client.go:715 +0x8fc\nnet/http.(*Client).Do(...)\n\tnet/http/client.go:581\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).doActiveHealthCheck(0xc000421a00, {0x0, {0xc00041eda0, 0x4}, {0xc00041eda5, 0x19}, {0x0, 0x0}, {0x0, 0x0}}, ...)\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy/healthchecks.go:298 +0x8cd\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).doActiveHealthCheckForAllHosts.func1(0xc0005b13e0)\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy/healthchecks.go:220 +0xa1e\ncreated by github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).doActiveHealthCheckForAllHosts\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy/healthchecks.go:175 +0x38\n"}
```

I used `caddy_Linux_go1.18_276c2f2` and `caddy_Linux_go1.19_276c2f2` artifacts.

**Comment by francislavoie** [comment]
And you're 100% sure you're using the correct build? Run `caddy version` to verify. Make sure you restarted the service, not just reloaded, if you're using systemd, to use the new binary. Just a sanity a check.

**Comment by maidmaid** [comment]
I add the downloaded caddy binary in a container while the docker build. It seems correctly added :

```
/srv/app # caddy version
276c2f2cea8c239157e8c1a7989bc3bed34b9074 (04 Jan 23 17:12 UTC)
```

If you are interested, I can attach here a small Dockerfile which you can reproduce the error with.

**Comment by maidmaid** [comment]
Here, the reproducer. Just put the caddy binary in the same folder than the Dockerfile.

<details>
<summary>Dockerfile</summary>

```Dockerfile
#syntax=docker/dockerfile:1.4

FROM php:8.2-fpm-alpine AS app_php
RUN mkdir -p /var/run/php

COPY caddy /usr/sbin/caddy
RUN chmod +x /usr/sbin/caddy

ADD https://github.com/just-containers/s6-overlay/releases/download/v3.1.2.1/s6-overlay-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v3.1.2.1/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz

COPY <<EOF /etc/services.d/caddy/run
#!/command/with-contenv sh
caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
EOF
RUN chmod +x /etc/services.d/caddy/run

COPY <<EOF /etc/services.d/php-fpm/run
#!/command/with-contenv sh
php-fpm
EOF
RUN chmod +x /etc/services.d/php-fpm/run

COPY <<EOF /usr/local/etc/php-fpm.d/zz-docker.conf
[global]
daemonize = no

[www]
listen = /var/run/php/php-fpm.sock
listen.mode = 0666
ping.path = /ping
EOF

COPY <<EOF /etc/caddy/Caddyfile
localhost
log
route {
    root * /srv/app/public
    php_fastcgi unix//var/run/php/php-fpm.sock {
        health_uri /ping
    }
}
EOF

ENTRYPOINT ["/init"]

```

</details>

<details>
<summary>build + run</summary>

```
$ export COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1
$ docker build . -t caddy-heathcheck-php
(...)
$ docker run --rm -it caddy-heathcheck-php sh
(...)
2023/01/06 18:44:07.225	ERROR	http.handlers.reverse_proxy.health_checker.active	active health check panicked	{...}
```

</details>

**Comment by mholt** [comment]
Thank you! Stupidly I forgot to dereference the request. Give this a try once CI finishes :)

**Review by maidmaid — APPROVED** [review]
```
INFO	http.handlers.reverse_proxy.health_checker.active	host is up	{"host": "localhost"}
```

:tada:

**Review by francislavoie — APPROVED** [review]

**Comment by maidmaid** [comment]
Thank you very much @mholt and @francislavoie !

**Pull request merged**
