### PR TITLE
ci: force fetch the upstream tags in CI

### PR DESCRIPTION
**Pull request by Mohammed90**

### CODE REVIEW

**Review by francislavoie — APPROVED** [review]
:see_no_evil:

**Review by mholt — APPROVED** [review]
I never been so ready to hit APPROVE so much in my life

button

**Comment by mholt** [comment]
Linking upstream issue here too: https://github.com/actions/checkout/issues/290#issuecomment-680260080

**Comment by mholt** [comment]
Oh wow you already merged it.

GitHub's UI is slow to update. Thanks!!

**Pull request merged**
