### PR TITLE
ci: Cache the GOCACHE directory to speed up builds and tests

### PR DESCRIPTION
**Pull request by francislavoie**
I'm thinking caching GOCACHE might speed up builds in CI... let's see.

### CODE REVIEW

**Comment by francislavoie** [comment]
Maybe this is a dumb idea, but it definitely has a pretty noticeable speedup.

What do you guys think?

**Comment by mholt** [comment]
Wow that is way faster. The results are still correct I imagine?

**Comment by francislavoie** [comment]
I would assume so. I don't really want to assume that there's no side effects though.

**Comment by mholt** [comment]
Alrighty, well, I'm willing to give it a go! Will let Mohammed review first when he has a chance.

**Comment by francislavoie** [comment]
Hmm. @Mohammed90 can we try with just CI first then enable it for GoReleaser later? I don't want to risk breaking releases (especially since v2.0 stable is the next one coming) just for a speed increase.

**Pull request merged**
