### PR TITLE
chore: compile without nosql's support for Postgres and MySQL

### PR DESCRIPTION
**Pull request by dunglas**
I had issues with nosql that only supports old versions of Badger while upgrading [Mercure](https://mercure.rocks) dependencies: https://github.com/dunglas/mercure/pull/960. While working on this, I figured out that we could disable compilation of Badger support for nosql (already done by Caddy), but also of MySQL and Postgres.

This reduce the build time and the binary size.
This also has the nice side effect of fixing https://github.com/caddyserver/caddy/issues/6613 because this dependency will not be included in the binary at all anymore.

When https://github.com/caddyserver/caddy/pull/6097 will be finished, we may need to add back support for MySQL and Postgres, but that's not sure because the new version of nosql may provide adapters in separate modules, that users will cherry-pick (that would be the best option IMHO). 

Closes https://github.com/caddyserver/caddy/issues/6613.

### CODE REVIEW

**Comment by francislavoie** [comment]
Yeah I agree we should do this for now. I really don't like that it's necessary. I hope Smallstep modularizes it sooner rather than later so this isn't necessary. (FYI @hslatman @azazeal, just so you know that it also affects Caddy's plugin authors as well)

**Comment by mohammed90** [comment]
I don't mind this at the moment, until upstream refactoring is finalized and the #6097 is complete sometime in the future.

**Review by mholt — APPROVED** [review]

**Comment by francislavoie** [comment]
Looking at the CI artifacts, it doesn't seem like the build output reduced in size at all (or at least is within 100kb difference).

**Comment by francislavoie** [comment]
Hmm, tried building locally with the tags and:

```
$ go build -tags=nobadger,nomysql,nopgx                                           
$ ls -la caddy
56650655

$ go build -tags=nobadger
$ ls -la caddy                                                         
59840067
```

So it seems to be about 3MB smaller actually. Maybe I'm being misled by these: (before: https://github.com/caddyserver/caddy/actions/runs/11467177533, after: https://github.com/caddyserver/caddy/actions/runs/11468346497)

**Pull request merged**
