### PR TITLE
chore: Adjustments to CI caching

### PR DESCRIPTION
**Pull request by francislavoie**

### CODE REVIEW

**Comment by mohammed90** [comment]
I think we need actions/setup-go#366, otherwise the cache gets clobbered by the multiple runners, no?

**Comment by francislavoie** [comment]
I don't think so. I looked at the source, and their cache key is `OS name + Go version + go.sum`. We would only need that if we used different OS versions I think.

**Comment by mohammed90** [comment]
> 

Ok, cool!

**Review by mohammed90 — APPROVED** [review]
Thanks for picking this up, Francis!

**Pull request merged**
