### PR TITLE
ci: fix the integration test `TestLeafCertLoaders`

### PR DESCRIPTION
**Pull request by mohammed90**
Reported in:
https://github.com/caddyserver/caddy/pull/6108#issuecomment-1979773494

### CODE REVIEW

**Comment by mohammed90** [comment]
Vulncheck complains because it resolved to Go1.22.0, while the issues are fixed in go1.22.1.

**Review by mholt — APPROVED** [review]
Aha thanks

**Comment by mholt** [comment]
Wait I thought we fixed govulncheck -- and this is up to date with master...

**Comment by mholt** [comment]
Oh, I just saw your comment (had to refresh the page)

**Comment by mholt** [comment]
Thank you!!

**Pull request merged**
