### PR TITLE
http: suppress flushing if the response is being buffered

### PR DESCRIPTION
**Pull request by WeidiDeng**
Fix [6144](https://github.com/caddyserver/caddy/issues/6144).

### CODE REVIEW

**Comment by francislavoie** [comment]
Riiight that makes sense. I did notice the other day we were missing FlushError but I didn't make the connection that this could be the fix. Thanks! You find the clever solutions 😊

**Review by mholt — APPROVED** [review]
Oh wow! Nice patch. Thanks Weidi. Always appreciate it when you come to the rescue :blush:

**Comment by mholt** [comment]
@WeidiDeng For some reason, CLA Assistant isn't happy -- can you double-check that your commit email matches your GitHub email?

**Comment by Baba1435** [comment]
Geçen gün FlushError'ı kaçırdığımızı fark ettim ama bunun düzeltme olabileceği bağlantısını kuramadım.

**Pull request merged**
