### PR TITLE
Allow Caddyfile configuration of arbitrary loggers, add new replace log filter

### PR DESCRIPTION
**Pull request by kujenga**
This PR follows up on discussion in https://github.com/caddyserver/caddy/issues/3958 about adding more functionality to the Caddyfile. I also added in another commit for a small new "replace" filter aimed at the same goal as I wrote up in the original ticket, providing more tools to remove sensitive data from logs.

Closes https://github.com/caddyserver/caddy/issues/3958

### CODE REVIEW

**Comment by francislavoie** [comment]
Mmm, no, I don't think this is right. We don't want to modify the `log` directive, we want to introduce a global option.

**Comment by kujenga** [comment]
Hm, I do see why you say that, I was thinking something similar when looking at what actual configs for this would be.

Might be a bit of a refactor to avoid duplicating the parsing logic, since I think we do want to share most/all of it between the two? I'll give it a try

**Comment by mholt** [comment]
I've been giving this some thought, and am coming to the conclusion that Caddy's existing log emission facilities are too complex already.

I think this kind of logic belongs in a log _processing_ facility. There are plenty of external tools for processing logs that will do stuff like this.

I also see value in having something like that built into Caddy. And, I think it'd make a perfect Caddy app, called `log`, which ingests logs and processes them. Its input would be the raw stream of bytes, and then it could parse, filter, etc, all sorts of logs.

**Comment by francislavoie** [comment]
I think I'll close this for now, since the impl isn't what we want. You can open a new PR if you decide to tackle configuring logging with globals.

**Pull request closed without merging**
