### PR TITLE
feat: use automaxprocs for better perf in containers

### PR DESCRIPTION
**Pull request by dunglas**
Proposal: Automatically set `GOMAXPROCS` to match Linux container CPU quota using https://github.com/uber-go/automaxprocs.
This should improve the performance of Caddy in containers: https://github.com/golang/go/issues/33803

### CODE REVIEW

**Comment by mholt** [comment]
Thanks! I had no idea about this. (The Go issue looks very popular though.) Willing to accept this, but thinking it should probably wait until after the Caddy 2.8 feature freeze? What do we think?

At the outset, this looks like a feature/optimization, and introduces a new dependency. But I could see this being a bug fix if Caddy is actually experiencing noticeably higher latency in containers.

**Comment by dunglas** [comment]
IMHO it could wait for Caddy 2.8. People can always set the environment variable manually in the meantime.

The latest (binary) release of Mercure includes this patch, for the record. We'll see if it causes any issues.

**Comment by mholt** [comment]
Gotcha. We'll wait for now then, but let us know how it goes with your users, and if it looks stable and helpful, I'll consider advancing it up!

**Comment by dunglas** [comment]
I improved log handling. It now uses zap and avoids the non-structured message.

**Comment by mholt** [comment]
Thanks for this. I'd be good with trying it. Want to clean up the lint errors (just reorder/regroup the imports) and then we can merge it?

**Review by mholt — APPROVED** [review]
LGTM now! We'll experiment to see how this works.

**Pull request merged**
