### PR TITLE
fileserver: do not double-escape paths

### PR DESCRIPTION
**Pull request by mohammed90**
Fixes the issue specified in https://github.com/caddyserver/caddy/issues/4329#issuecomment-976957226.

### CODE REVIEW

**Comment by mohammed90** [comment]
@bmichotte  and @ueffel, please check if the patch resolves your issue and doesn't break new stuff.

**Comment by ueffel** [comment]
```shell
$ ./caddy version
v2.4.7-0.20211126140144-80fbec0102d5 h1:mdBZC644zlsG4dWbTG3YcsU34linp0ODDoMfaogqSB0=
```

It does not seem to be fixed. 
image

I think the escaping [here](https://github.com/caddyserver/caddy/blob/80fbec0102d59ac2dd0ec2a3304c8f5c3c6b520e/modules/caddyhttp/fileserver/browsetplcontext.go#L46) is causing the double encoding. This bit:

```go
u := url.URL{Path: url.PathEscape(name)}
```

**Comment by mohammed90** [comment]
> 

Now I can see why. While we're escaping it in that line, the template also calls [the `html` function from the text/template package of stdlib](https://pkg.go.dev/text/template@master#hdr-Functions):

https://github.com/caddyserver/caddy/blob/6f9b6ad78e6b9a40afbf12e53017e39abee90a6d/modules/caddyhttp/fileserver/browse.html#L390-L396

The documentation of the function is:

> html
	Returns the escaped HTML equivalent of the textual
	representation of its arguments. This function is unavailable
	in html/template, with a few exceptions.


I've updated the code. This effectively reverts the buggy earlier PR but keeps the tests, which were passing anyways.

**Review by francislavoie — APPROVED** [review]
Seems good 👍

**Pull request merged**
