### PR TITLE
V2: implement a caddy module that doing the UDP/TCP proxy [WIP]

### PR DESCRIPTION
**Pull request by colinaaa**
still work in progress

---
name: Pull request
about: Propose changes to the code
title: 'implement the UDP/TCP proxy like caddy.net in v1'
labels: ''
assignees: ''
---

## 1. What does this change do, exactly?

Implement a caddy v2 module to do the UDP/TCP proxy

## 2. Please link to the relevant issues.

https://github.com/caddyserver/caddy/issues/2879

## 3. Which documentation changes (if any) need to be made because of this PR?

this is a new module so a lot of documents should be added.

## 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by mholt** [comment]
Cool! I'll take a look at this soon -- probably after the Go meetup on Tuesday is finished, since I'm working on the presentation for that...

**Comment by davidmehren** [comment]
Any plans on continuing here? Or would work on #3006 supersede this PR?

**Comment by mholt** [comment]
@davidmehren If I understand correctly, I think that is asking for something different: packet details exposed to the application layer; this PR implements a specific application.

**Comment by mholt** [comment]
If it's alright, I am going to close this PR until it has more activity and/or is more ready for review.

If there is still interest in finishing this project, feel free to continue discussion, I just want to keep open PRs actionable. Thanks!

**Comment by unixfox** [comment]
Oh that's quite unfortunate, I was waiting for this feature to be included into caddy v2 because I wanted to stop using [caddy-net](https://github.com/unixarchive/caddy-net) from caddy v1.

**Comment by mholt** [comment]
@unixfox You're welcome to pick up the PR where it left off or start your own, of course!

**Comment by mholt** [comment]
@unixfox @colinaaa @davidmehren FYI, I have already implemented a very flexible and capable `layer4` app for Caddy 2, and will be publishing it soon. It's really cool :)

**Comment by mholt** [comment]
For anyone finding this in a search, the information about Project Conncept can be found here: https://github.com/mholt/conncept

**Pull request closed without merging**
