### PR TITLE
caddytls: Implement remote IP connection matcher

### PR DESCRIPTION
**Pull request by mholt**
I'm not sure this is a good idea as a replacement for auth, but I think this could still be useful. See https://caddy.community/t/best-solution-for-mixing-lan-and-cloudflare-authenticated-origin-pulls/12139/8

### CODE REVIEW

**Comment by mholt** [comment]
I know this implementation using `NotRanges` might be disappointing, @francislavoie, but I realized that the connection policy matchers aren't really designed to be composed like the HTTP request matchers (conn policy matchers are only a list, whereas HTTP request matchers are a list of maps of lists). So I just went ahead with the simplest possible implementation to negate IP ranges.

**Comment by francislavoie** [comment]
That's ok 👍

**Comment by wazerstar** [comment]
Hey was this nuked again? I'm actually in this boat now, want to use same domain and when on lan with origin destination would avoid getting out on cloudflare and back in again before reaching internal.

**Comment by francislavoie** [comment]
@wazerstar this isn't the right place to ask questions. Please ask on the forums instead, and fill out the help topic template: https://caddy.community

**Pull request merged**
