### PR TITLE
Implemented the zerossl API to issue ssl certificates

### LINKED ISSUE #6064: Implement ZeroSSL API
Right now, the ZeroSSL issuer only uses the ZeroSSL API to generate EAB for a user's email address. Then it proceeds to use ACME.

This is useful for most people with free accounts, but those with paid accounts won't be able to reap the benefits of their higher limits, etc (because ZeroSSL's software stack is more flexible when using the API). Paid users need to use the API to be able to access all the features they're paying for.

Should be pretty simple to implement: https://zerossl.com/documentation/api/

It will need to be opt-in, as simply providing an API key can be done by free account users as well, and if we use the API for them we'd quickly break their deployments if they're not prepared to pay for the API. So maybe a bool option to toggle on the use of the API.

Anyone can take this up, or I will get around to it soon (working through a backlog to start the year!)

### PR DESCRIPTION
**Pull request by armadi1809**
Closes #6064

### CODE REVIEW

**Comment by armadi1809** [comment]
@mholt This is my initial attempt to implement the ZeroSSL API to issue new certs. I am sure it will require further adjustments so any feedback here would be great 😅  Also, what do you think is the best/easiest way to test this thoroughly and make sure it's working as intended?

**Comment by mholt** [comment]
Just circling back, sorry again for the delay.

I did a quick scan and the overall approach looks right: use ACME unless the API is explicitly enabled. I still need to read through the API code and the API docs and see how that goes, and test it out. I have an account with ZeroSSL that will let me test this, so maybe I'll just do that (unless you'd really like to -- in that case I can request you get special access to be able to do so).

**Comment by armadi1809** [comment]
That would work, you can test it and I'll take it back from there based on your feedback. Thank you!

**Comment by mholt** [comment]
(Still on my list! Sorry!)

**Comment by gustawdaniel** [comment]
I experiencing this error on production. Is there any workaround?

Should I replace caddy with letsencrypt or better wait for this update?

**Comment by francislavoie** [comment]
What issue @gustawdaniel? This is a new feature.

Please open a topic on the forums if you need help https://caddy.community

**Comment by mholt** [comment]
@armadi1809 Hey Aziz, I went ahead and built on your work in https://github.com/caddyserver/zerossl -- and from there I'll integrate the API use in Caddy/CertMagic :)

Thanks for the kickstart!! I gave you credit in the commit.

**Comment by mholt** [comment]
Next steps will be to probably move the ZeroSSLIssuer into CertMagic, so CM users can also use ZeroSSL easily. Then to make the ZeroSSLIssuer in Caddy a simple wrapper over the CM one, kind of like ACMEIssuer is.

**Pull request closed without merging**
