### PR TITLE
improve fmt warning message

### LINKED ISSUE #4416: 2.4.6: caddyfile with brackets can not be formatted
Hi There :) I'm running caddy with docker. After a version update to v2.4.6, My configuration no longer works.

My caddy version:
```
$ caddy version
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
```

runtime environment:
Ubuntu 20.04 LTS
an oracle VPS (ampere  arm64 processor)

a simple config for replication:
```
localhost:2016 {
	respond "Goodbye, world!"
}
```

run the following command
```
docker run --rm -v `realpath .`/test.caddyfile:/etc/caddy/Caddyfile caddy
```

caddy v2.4.6 gave me this error:
```
{"level":"warn","ts":1636742970.6282396,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":1}
```

However, with version v2.2.1:
```
{"level":"info","ts":1636743148.6654737,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
```

Is it something with my configuration or a regression bug with caddy (I hope not)?

### PR DESCRIPTION
**Pull request by 12f23eddde**
Closes #4416 
This PR only modifies "caddy fmt" warning message. The former one may cause confusion, and this mod might save several hours for someone else.

### CODE REVIEW

**Comment by mholt** [comment]
The only qualm I have with this suggestion is that `caddy fmt` isn't just about a consistent style, sometimes it can fix bugs in the Caddyfile, for example missing a space where one is expected. It's not required, but it's more than just a style preference.

I'm really hoping nobody spends hours trying to figure out how to run `caddy fmt` though, if it takes more than a minute or two, there's something else wrong I think, and I'm not sure it's this warning string.

**Comment by francislavoie** [comment]
IMO I think the warning string is confusing because it doesn't mention that `caddy fmt` is a command. Many users on the forums come to ask what it's about.

I think we could clarify, but I agree this PR's wording might not be the right one.

**Comment by mholt** [comment]
How about `run the 'caddy fmt' command to fix formatting inconsistencies in the Caddyfile`

**Comment by francislavoie** [comment]
Or maybe: `Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies` ?

**Comment by 12f23eddde** [comment]
Thank you for your response to a newbie OSS developer! I think you got it right.

**Comment by 12f23eddde** [comment]
Sorry for my newbie question :) To clean up the commit history, I rebased this branch with the upstream head, squashed the commits, and force-pushed. But I'm not quite sure how caddy does it (I've heard that force push is discouraged by some other projects, and if it is the case, what should I do?)

**Comment by francislavoie** [comment]
We use GitHub's squash and merge button at the end usually. So it doesn't matter too much how PR authors end up organizing their branches in the end. What you did is fine 👍

**Review by francislavoie — APPROVED** [review]
Thanks!

**Review by mholt — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
