### PR TITLE
fileserver: browse: do not encode the paths in breadcrumbs and page title

### LINKED ISSUE #4409: 2.4.6 regression: file_browser displays path unencoded
**Use case:**
I'm using Caddy to publish school lesson's videos & images via file_server. Here is config:

```
:80
bind 0.0.0.0

root * /var/www/html
file_server browse {
  hide "#snapshot" "@eaDir" *.db
}
```

In version 2.4.5 the name of current folder was displayed correctly on top of the page (the breadcrumb).

**Bug:**
However, in version 2.4.6 it is displayed unencoded. I suspect it caused by security patch and is probably needed. But can the path be correctly encoded and displayed in the UI?

The URL's are changed, too.

The page <title> is unencoded, too

Here are 2 screenshots of 2.4.5 vs 2.4.6:

## **Space in the name of the folder:**
Space

## **Russian characters:**
RussianChars

### PR DESCRIPTION
**Pull request by mohammed90**
Breadcrumbs use the `.Name` field as the visual item while `.Path` is the data-oriented item. Earlier implementation used the URL path as-is, which could have been in escaped format. This PR un-escapes the URL path to use as for the `.Name`.

Fixes #4409

### CODE REVIEW

**Comment by francislavoie** [comment]
@SlavikCA would you be able to build from this branch to confirm the fix? Thanks!

**Review by francislavoie — APPROVED** [review]
Seems good to me!

**Comment by mholt** [comment]
@SlavikCA Can you confirm this fixes it for you?

**Comment by SlavikCA** [comment]
Thank you very much!

Yes, just tested  and both page title and breadcrumbs looks good now.

**Pull request merged**
