### PR TITLE
add support for a ca.local to provide self signed certs

### PR DESCRIPTION
**Pull request by sarge**
This adds support for small step certificate authority on the same machine.

In the case where small step is not configured locally it will provision a local small step configuration. This will include the password in plain text, this is unavoidable I believe.

Specifying the `ca.local` is a special case it will use the local small step configuration.

Caddyfile

```
test1.sarge.com:9443 {
  tls {
    ca ca.local
  }
}
```

Some minor nitpicks - small step added a dependency on `newrelic`.
A random warning is generated by certmagic when attempting to delete expired certificates.

### CODE REVIEW

**Comment by mholt** [comment]
Awesome -- I will take a look at this soon! (Happy new year.)

**Comment by sarge** [comment]
Considering replacing `ca.local` with `local` to reduce the stutter
```
test1.sarge.com:9443 {
  tls {
    ca local
  }
}
```

@mholt those build errors I don't think are due to my change

**Comment by mholt** [comment]
@sarge Are you in our dev Slack? I couldn't find you -- want an invite? Then if you want to bounce ideas off or just have some quicker feedback about anything, it can be easier. Let me know if you want an invite, and which email to send to.

FYI I haven't forgotten about this PR, in fact I'm quite excited for this feature, but I really have to get the Caddyfile just right ASAP, and then this might come next depending on how funding stuff works out.

**Comment by sarge** [comment]
@mholt sure can you send an invite to sargent.mark[@gggmailcom] - intentional typo

**Comment by mholt** [comment]
@sarge Just so you know, I'm beginning a deeper dive into this project, with a broader scope of design and purpose... I may refer to this PR but overall I think my work with Smallstep will supersede this PR.

**Comment by sarge** [comment]
All good😊

**Comment by sarge** [comment]
Closing in favour of a deeper small step integration

**Pull request closed without merging**
