### PR TITLE
v2: Refactor reverse proxy and add FastCGI support

### LINKED ISSUE #2679: v2: HTTP proxy module
Finish up Caddy 2's HTTP proxy.

- Pluggable protocols (FastCGI for instance)
- Migrate (almost?) all the features of the v1 proxy directive
- Consider https://github.com/caddyserver/caddy/pull/2507/files#diff-70219fd88fe3f36834f474ce6537ed26R762 to see if/how that should be implemented
- And also https://github.com/caddyserver/caddy/pull/2564
- Any open issues related to the proxy, esp. those with a v2 milestone should be considered as well.

### LINKED ISSUE #2722: Fastcgi for Caddy v2
## 1. What would you like to have changed?

I would really like Caddy v2 to be able to send fastcgi scripts to handlers via fastcgi interface, just like Caddy v1.
Hence fastcgi implementation would be awesome.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

In order for Caddy v2 to become the go-to webserver for the GO community, in my opinion being able to host sites based on cgi scripts is a must-have feature for Caddy v2.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

None at the moment, because Caddy v2 does not yet support third party modules/plugins.

## 4. Please link to any relevant issues, pull requests, or other discussions.

https://caddy.community/t/fastcgi-with-caddy-v2/6123

### PR DESCRIPTION
**Pull request by mholt**
## 1. What does this change do, exactly?

Refactors the reverse proxy so that the transport is modular, along with adding many new features and bringing features over that exist in v1.

Please help try it out!

## 2. Please link to the relevant issues.

Closes #2722, #2701, and mostly closes #2679.

## 3. Which documentation changes (if any) need to be made because of this PR?

Add documentation for the reverse proxy.

Here's a full config so far (using the HTTP transport as opposed to FastCGI here):

```json
{
    "handler": "reverse_proxy",
    "transport": {
        "protocol": "http",
        "tls": {
            "root_ca_pool": ["..."],
            "client_certificate_file": "...",
            "client_certificate_key_file": "...",
            "insecure_skip_verify": false,
            "handshake_timeout": "2s"
        },
        "keep_alive": {
            "enabled": true,
            "max_idle_conns": 1500,
            "max_idle_conns_per_host": 50,
            "idle_timeout": "2m"
        },
        "compression": true,
        "max_conns_per_host": 100,
        "dial_timeout": "2s",
        "response_header_timeout": "10s",
        "expect_continue_timeout": "5s",
        "max_response_header_size": 1024,
        "write_buffer_size": 4096,
        "read_buffer_size": 4096
    },
    "circuit_breaker": { },
    "load_balancing": {
        "selection_policy": {
            "policy": "header",
            "header_name": "Server-ID"
        },
        "try_duration": "10s",
        "try_interval": "250ms"
    },
    "health_checks": {
        "active": {
            "path": "/ok",
            "port": 1234,
            "interval": "10s",
            "timeout": "2s",
            "max_size": 1024,
            "expect_status": 200,
            "expect_body": ".*foobar.*"
        },
        "passive": {
            "max_fails": 3,
            "fail_duration": "1m",
            "unhealthy_request_count": 100,
            "unhealthy_status": [500, 502],
            "unhealthy_latency": "5s"
        }
    },
    "upstreams": [
        {
            "dial": "localhost:7777"
        }
    ]
}
```

## 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by Henrocker** [comment]
@tobya Would you be able to share the config which you used for testing?

Thanks!

**Comment by tobya** [comment]
This is what currently works.  There are some issues.  i had some with cookie values but I'm unsure exactly what that was.  We would appreciate any feedback etc.  Also I have no rewrites so if you php requires those you'll need to add.

Note in this you need to put in your route twice, though there is a fix for this from @mholt which I havent yet tried, this is very much work in progress.  I will update this once new config is working.

Also once you build fastcgi branch, you will need to start like this
> caddy run -config=c:\mydir\caddyfile

````
{
  "apps": {
    "http": {
      "servers": {
        "php_test": {
          "listen": [
            ":8080"
          ],
          "routes": [
            {
              "handle": [
                {
                  "handler": "vars",
                  "root": "C:\\BCSDEV\\www\\Z\\bcsstudents_gitp4"
                }
              ]
            },
            {
              "match": [
                {
                  "file": {
                    "try_files": [
                      "{http.request.uri.path}/index.php"
                    ]
                  }
                }
              ],
              "handle": [
                {
                  "handler": "rewrite",
                  "uri": "{http.matchers.file.relative}"
                }
              ]
            },
            {
              "match": [
                {
                  "path": [
                    "*.php"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "reverse_proxy",
                  "transport": {
                    "protocol": "fastcgi",
                    "split_path": ".php"
                  },
                  "upstreams": [
                    {
                      "dial": "localhost:11223"
                    }
                  ]
                }
              ],
              "terminal": true
            },
            {
              
              "handle": [
                {
                  "handler": "file_server",
                  "root": "C:\\BCSDEV\\www\\Z\\bcsstudents_gitp4"
                }
              ]
            }
          ]
        }
      }
    }
  }
}
````

**Comment by mholt** [comment]
@Henrocker This config _should_ work, without you having to repeat the site root:

```
{
	"apps": {
		"http": {
			"servers": {
				"php_test": {
					"listen": [
						":8080"
					],
					"routes": [
						{
							"handle": [
								{
									"handler": "vars",
									"root": "YOUR_SITE_ROOT"
								},
								{
									"handler": "subroute",
									"routes": [
										{
											"match": [
												{
													"file": {
														"try_files": [
															"{http.request.uri.path}/index.php"
														]
													}
												}
											],
											"handle": [
												{
													"handler": "rewrite",
													"uri": "{http.matchers.file.relative}"
												}
											]
										},
										{
											"match": [
												{
													"path": [
														"*.php"
													]
												}
											],
											"handle": [
												{
													"handler": "reverse_proxy",
													"transport": {
														"protocol": "fastcgi",
														"split_path": ".php"
													},
													"upstreams": [
														{
															"dial": "YOUR_FASTCGI_BACKEND"
														}
													]
												}
											],
											"terminal": true
										},
										{
											"handle": [
												{
													"handler": "file_server"
												}
											]
										}
									]
								}
							]
						}
					]
				}
			}
		}
	}
}
```

Now, each PHP app has slightly different requirements, so you may need to adjust this.

I'll be working on Caddyfile integration today, so you won't have to mess with the JSON for this stuff all the time.

Still, I need to know if this works for most PHP apps. So please let me know! Thanks @tobya for all your help yesterday.

**Comment by Henrocker** [comment]
Thank you both @mholt and @tobya, and yes: I'm glad to have the Caddyfile config adapter for Caddy v2 in the future ;-)

Will report back!

**Comment by Henrocker** [comment]
Does Caddy v2 on fastcgi branch already support unix sockets for upstreams?

**Comment by mholt** [comment]
@Henrocker 

> Does Caddy v2 on fastcgi branch already support unix sockets for upstreams?

Yes: `{"dial": "unix//path/to/socket"}`

**Comment by Henrocker** [comment]
Okay, so I've set Caddy v2 up, but I face some issues..

My setup:

```
$ tree /etc/v2caddy/
/etc/v2caddy/
├── caddy
├── Caddyfile
└── html
    ├── index.html
    └── index.php

1 directory, 4 files
```
Config:

```
$ cat /etc/v2caddy/Caddyfile
{
        "apps": {
                "http": {
                        "servers": {
                                "php_test": {
                                        "listen": [
                                                ":8080"
                                        ],
                                        "routes": [
                                                {
                                                        "handle": [
                                                                {
                                                                        "handler": "vars",
                                                                        "root": "/etc/v2caddy/html"
                                                                },
                                                                {
                                                                        "handler": "subroute",
                                                                        "routes": [
                                                                                {
                                                                                        "match": [
                                                                                                {
                                                                                                        "file": {
                                                                                                                "try_files": [
                                                                                                                        "{http.request.uri.path}/index.php"
                                                                                                                ]
                                                                                                        }
                                                                                                }
                                                                                        ],
                                                                                        "handle": [
                                                                                                {
                                                                                                        "handler": "rewrite",
                                                                                                        "uri": "{http.matchers.file.relative}"
                                                                                                }
                                                                                        ]
                                                                                },
                                                                                {
                                                                                        "match": [
                                                                                                {
                                                                                                        "path": [
                                                                                                                "*.php"
                                                                                                        ]
                                                                                                }
                                                                                        ],
                                                                                        "handle": [
                                                                                                {
                                                                                                        "handler": "reverse_proxy",
                                                                                                        "transport": {
                                                                                                                "protocol": "fastcgi",
                                                                                                                "split_path": ".php"
                                                                                                        },
                                                                                                        "upstreams": [
                                                                                                                {
                                                                                                                        "dial": "unix//run/php/php7.3-fpm.sock"
                                                                                                                }
                                                                                                        ]
                                                                                                }
                                                                                        ],
                                                                                        "terminal": true
                                                                                },
                                                                                {
                                                                                        "handle": [
                                                                                                {
                                                                                                        "handler": "file_server"
                                                                                                }
                                                                                        ]
                                                                                }
                                                                        ]
                                                                }
                                                        ]
                                                }
                                        ]
                                }
                        }
                }
        }
}
```

Received error:

```
$ ./caddy run -config=/etc/v2caddy/Caddyfile
2019/09/06 19:49:45 Caddy 2 admin endpoint listening on localhost:2019
2019/09/06 19:49:45 [INFO][cache:0xc000132f00] Started certificate maintenance routine
2019/09/06 19:49:45 Caddy 2 serving initial configuration
2019/09/06 19:49:54 [ERROR] [GET /index.html] {id=bz8akbtz6} fileserver.(*FileServer).ServeHTTP (staticfiles.go:98): HTTP 404: stat index.html: no such file or directory
2019/09/06 19:50:00 [ERROR] [GET /index.php] {id=hz0qhf11v} reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:272): HTTP 502: dialing backend: dial tcp: address /run/php/php7.3-fpm.sock: missing port in address
```

Not sure, why Caddy wants a port after a unix socket...

And visiting my page under HTTP port 8080 returns a 404 Error when specifying no URI, a blank white page when specifying _index.php_, and a 404 error again when doing _index.html_.

Do you have any ideas?
Thank you!

**Comment by mholt** [comment]
@Henrocker Ah, I think I found the bug that leads to the dialing error. I just pushed that fix. Could you pull the latest and see if the dialing error goes away?

I'm also working with @francislavoie to help debug the 404 error you're seeing.

**Comment by Henrocker** [comment]
The fix works partially:

If I type _http://my.domain:8080/index.php_, I can see my external IP-Address, but if a omit the URI or type _/index.html_, I get a 404 error.

My setup, as well as my configs didn't change.

**Comment by mholt** [comment]
@Henrocker Good, actually it sounds like the fix worked perfectly for what it was supposed to fix - the dialing error. :)

Still working on the 404s. Will have an update soon I think.

**Comment by Henrocker** [comment]
@mholt Alright! In the meantime, I am going to experiment with different php use cases and scripts to see if they work as expected :-)

**Comment by mholt** [comment]
@Henrocker Thanks! I just pushed a change which I'm hoping resolves at least some of the issues, though I'm not confident that it is a finished fix. You can remove any use of `{http.var.root}` in your config. (It was renamed to `{http.vars.root}` just now to be consistent, but I also made it the default, so you don't need it anymore. You DO however still need the "vars" handler to actually set the root path.)

**Comment by Henrocker** [comment]
Cool! After commit 4bd9496:

Setup:
```
$ tree /etc/v2caddy/
/etc/v2caddy/
├── caddy
├── Caddyfile
├── html
│   ├── index.html
│   └── index.php
└── oldCaddy

1 directory, 5 files
```

Config:
```
{
        "apps": {
                "http": {
                        "servers": {
                                "php_test": {
                                        "listen": [
                                                ":8080"
                                        ],
                                        "routes": [
                                                {
                                                        "handle": [
                                                                {
                                                                        "handler": "vars",
                                                                        "root": "/etc/v2caddy/html"
                                                                },
                                                                {
                                                                        "handler": "subroute",
                                                                        "routes": [
                                                                                {
                                                                                        "match": [
                                                                                                {
                                                                                                        "file": {
                                                                                                                "try_files": [
                                                                                                                        "{http.request.uri.path}/index.php"
                                                                                                                ]
                                                                                                        }
                                                                                                }
                                                                                        ],
                                                                                        "handle": [
                                                                                                {
                                                                                                        "handler": "rewrite",
                                                                                                        "uri": "{http.matchers.file.relative}"
                                                                                                }
                                                                                        ]
                                                                                },
                                                                                {
                                                                                        "match": [
                                                                                                {
                                                                                                        "path": [
                                                                                                                "*.php"
                                                                                                        ]
                                                                                                }
                                                                                        ],
                                                                                        "handle": [
                                                                                                {
                                                                                                        "handler": "reverse_proxy",
                                                                                                        "transport": {
                                                                                                                "protocol": "fastcgi",
                                                                                                                "split_path": ".php"
                                                                                                        },
                                                                                                        "upstreams": [
                                                                                                                {
                                                                                                                        "dial": "unix//run/php/php7.3-fpm.sock"
                                                                                                                }
                                                                                                        ]
                                                                                                }
                                                                                        ],
                                                                                        "terminal": true
                                                                                },
                                                                                {
                                                                                        "handle": [
                                                                                                {
                                                                                                        "handler": "file_server"
                                                                                                }
                                                                                        ]
                                                                                }
                                                                        ]
                                                                }
                                                        ]
                                                }
                                        ]
                                }
                        }
                }
        }
}
```

Logs:
```
$ ./caddy run -config=/etc/v2caddy/Caddyfile
2019/09/06 21:07:32 Caddy 2 admin endpoint listening on localhost:2019
2019/09/06 21:07:32 [INFO][cache:0xc0000af040] Started certificate maintenance routine
2019/09/06 21:07:32 Caddy 2 serving initial configuration
2019/09/06 21:08:07 [ERROR] [GET /index] {id=bewe2cyhc} fileserver.(*FileServer).ServeHTTP (staticfiles.go:102): HTTP 404: stat /etc/v2caddy/html/index: no such file or directory
2019/09/06 21:08:13 [ERROR] [GET /index1.html] {id=5e68c5u4k} fileserver.(*FileServer).ServeHTTP (staticfiles.go:102): HTTP 404: stat /etc/v2caddy/html/index1.html: no such file or directory
2019/09/06 21:08:17 [ERROR] [GET /.html] {id=jv6jmat55} fileserver.(*FileServer).ServeHTTP (staticfiles.go:102): HTTP 404: stat /etc/v2caddy/html/.html: no such file or directory
```

- http://localhost:8080/index.php **WORKS**
- http://localhost:8080/index.html **WORKS**
- http://localhost:8080/ **BLANK PAGE and no logs in stderr**

Regarding the last one with the blank page.. in my understanding looking at the config, the line 
```
try_files": [
                  "{http.request.uri.path}/index.php"
]"
```
should make sure to have a look into the html directory if a file called index.php exists and if yes run it when no uri was specified, right? Or do you have any idea why I get a blank page with no specific uri?

**Comment by mholt** [comment]
@Henrocker See how far this newest commit gets you! File matching ("try_files") now enforces the trailing forward slash, if present, to match directories, or without it, to match files only. Kind of like how v1 works. Thanks for helping us get this right. Keep me posted

**Comment by Henrocker** [comment]
Now with the same setup as above and including 97ace2a:

- http://localhost:8080/index.php WORKS as expected
- http://localhost:8080/index.html WORKS as expected
- http://localhost:8080/ (with slash at the end) & http://localhost:8080 (omitting the last slash) both outputs source of index.php in plaintext and seems like it does not sent the php script to fastcgi upstream.

nouri

Nothing interesting in the logs.

**Comment by francislavoie** [comment]
Thanks to @mholt help, got it working for a Laravel app :tada: 

My config:

<details><pre><code>{
    "apps": {
        "http": {
            "servers": {
                "php_test": {
                    "listen": [
                        ":80"
                    ],
                    "routes": [
                        {
                            "handle": [
                                {
                                    "handler": "vars",
                                    "root": "/var/www/public"
                                },
                                {
                                    "handler": "subroute",
                                    "routes": [
                                        {
                                            "match": [
                                                {
                                                    "header_regexp": {
                                                        "Connection": {
                                                            "pattern": "Upgrade"
                                                        }
                                                    }
                                                },
                                                {
                                                    "header": {
                                                        "Upgrade": [
                                                            "websocket"
                                                        ]
                                                    }
                                                }
                                            ],
                                            "handle": [
                                                {
                                                    "handler": "reverse_proxy",
                                                    "upstreams": [
                                                        {
                                                            "dial": "websockets:6001"
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            "match": [
                                                {
                                                    "file": {
                                                        "try_files": [
                                                            "{http.request.uri.path}",
                                                            "index.php"
                                                        ]
                                                    }
                                                }
                                            ],
                                            "handle": [
                                                {
                                                    "handler": "rewrite",
                                                    "uri": "{http.matchers.file.relative}",
                                                    "rehandle": true
                                                }
                                            ]
                                        },
                                        {
                                            "match": [
                                                {
                                                    "path": [
                                                        "*.php"
                                                    ]
                                                }
                                            ],
                                            "handle": [
                                                {
                                                    "handler": "reverse_proxy",
                                                    "transport": {
                                                        "protocol": "fastcgi",
                                                        "split_path": ".php"
                                                    },
                                                    "upstreams": [
                                                        {
                                                            "dial": "php-fpm:9000"
                                                        }
                                                    ]
                                                }
                                            ],
                                            "terminal": true
                                        },
                                        {
                                            "handle": [
                                                {
                                                    "handler": "file_server"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        }
    }
}
</code></pre></details>

If you don't use websockets, you can omit the first block in `"routes"`

**Comment by mholt** [comment]
In summary, then, for a generic PHP app through a fastcgi responder:

```
{
    "apps": {
        "http": {
            "servers": {
                "php_test": {
                    "listen": [
                        ":80"
                    ],
                    "routes": [
                        {
                            "handle": [
                                {
                                    "handler": "vars",
                                    "root": "YOUR_SITE_ROOT_HERE"
                                },
                                {
                                    "handler": "subroute",
                                    "routes": [
                                        {
                                            "match": [
                                                {
                                                    "file": {
                                                        "try_files": ["{http.request.uri.path}", "index.php"]
                                                    }
                                                }
                                            ],
                                            "handle": [
                                                {
                                                    "handler": "rewrite",
                                                    "uri": "{http.matchers.file.relative}",
                                                    "rehandle": true
                                                }
                                            ]
                                        },
                                        {
                                            "match": [
                                                {
                                                    "path": ["*.php"]
                                                }
                                            ],
                                            "handle": [
                                                {
                                                    "handler": "reverse_proxy",
                                                    "transport": {
                                                        "protocol": "fastcgi",
                                                        "split_path": ".php"
                                                    },
                                                    "upstreams": [
                                                        {
                                                            "dial": "YOUR_FASTCGI_RESPONDER_HERE"
                                                        }
                                                    ]
                                                }
                                            ],
                                            "terminal": true
                                        },
                                        {
                                            "handle": [
                                                {
                                                    "handler": "file_server"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        }
    }
}
```

I wouldn't guarantee that this'll work for all PHP apps, of course, but it should be enough to get anyone else started with the basics!

Will be merging the reverse proxy soon after a little more cleanup.

**Comment by Henrocker** [comment]
@mholt Yes, this should work for basic php apps.

Could your config perhaps also fix my issue described in the update section here: https://github.com/caddyserver/caddy/pull/2737#issuecomment-528991653?

**Comment by francislavoie** [comment]
I think it should. Differences are there's 2 things in try_files, and rehandle is set to true.

**Comment by Henrocker** [comment]
Okay, so one last time:

Setup:
```
$ tree /etc/v2caddy/
/etc/v2caddy/
├── caddy
├── Caddyfile
└── html
    ├── index1.html
    └── index.php

1 directory, 4 files
```

Config:
```
{
    "apps": {
        "http": {
            "servers": {
                "php_test": {
                    "listen": [
                        ":8080"
                    ],
                    "routes": [
                        {
                            "handle": [
                                {
                                    "handler": "vars",
                                    "root": "/etc/v2caddy/html"
                                },
                                {
                                    "handler": "subroute",
                                    "routes": [
                                        {
                                            "match": [
                                                {
                                                    "file": {
                                                        "try_files": ["{http.request.uri.path}", "index.php"]
                                                    }
                                                }
                                            ],
                                            "handle": [
                                                {
                                                    "handler": "rewrite",
                                                    "uri": "{http.matchers.file.relative}",
                                                    "rehandle": true
                                                }
                                            ]
                                        },
                                        {
                                            "match": [
                                                {
                                                    "path": ["*.php"]
                                                }
                                            ],
                                            "handle": [
                                                {
                                                    "handler": "reverse_proxy",
                                                    "transport": {
                                                        "protocol": "fastcgi",
                                                        "split_path": ".php"
                                                    },
                                                    "upstreams": [
                                                        {
                                                            "dial": "unix//run/php/php7.3-fpm.sock"
                                                        }
                                                    ]
                                                }
                                            ],
                                            "terminal": true
                                        },
                                        {
                                            "handle": [
                                                {
                                                    "handler": "file_server"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        }
    }
}
```

Logs:
```
$ ./caddy run -config=/etc/v2caddy/Caddyfile
2019/09/06 22:14:34 Caddy 2 admin endpoint listening on localhost:2019
2019/09/06 22:14:34 [INFO][cache:0xc0000af090] Started certificate maintenance routine
2019/09/06 22:14:34 Caddy 2 serving initial configuration
```

- http://localhost:8080/index.php **WORKS**
- http://localhost:8080/index1.html **WORKS**
- http://localhost:8080/ & http://localhost:8080 **WORKS** by showing index.php
**BUT:** - https://localhost:8080/PathOrFileThatDoesNotExist.Rubbish runs the index.php script and does not return a 404, which it should, I believe.

**Comment by francislavoie** [comment]
> BUT: - https://localhost:8080/PathOrFileThatDoesNotExist.Rubbish runs the index.php script and does not return a 404, which it should, I believe.

Right, so my config was written to explicitly pass anything that isn't a static file to `index.php` to allow my PHP app to do its own routing.

Maybe you want to remove `"split_path": ".php"` so that it doesn't do that (just guessing, still not entirely sure how to navigate the v2 config yet)

**Comment by mholt** [comment]
I think @Henrocker just needs to remove "index.php" from the try_files matcher for rewrite. Currently, if the requested file doesn't exist, it will rewrite to index.php thus be handled by fastcgi. So removing that should fix it, I think.

**Comment by Henrocker** [comment]
@mholt If I do so, then everything works except when visiting http://localhost:8080/ or http://localhost:8080, I get 404 errors again.

**Comment by mholt** [comment]
Ah, so there has to be a rewrite to handle the case of using PHP index files.

**Comment by Henrocker** [comment]
My current Caddyfile looks like this:

```
{
    "apps": {
        "http": {
            "servers": {
                "php_test": {
                    "listen": [
                        ":8080"
                    ],
                    "routes": [
                        {
                            "handle": [
                                {
                                    "handler": "vars",
                                    "root": "/etc/v2caddy/html"
                                },
                                {
                                    "handler": "subroute",
                                    "routes": [
                                        {
                                            "match": [
                                                {
                                                    "file": {
                                                        "try_files": ["{http.request.uri.path}", "{http.request.uri.path}/", "{http.request.uri.path}/index.php"]
                                                    }
                                                }
                                            ],
                                            "handle": [
                                                {
                                                    "handler": "rewrite",
                                                    "uri": "{http.matchers.file.relative}",
                                                    "rehandle": true
                                                }
                                            ]
                                        },
                                        {
                                            "match": [
                                                {
                                                    "path": ["*.php"]
                                                }
                                            ],
                                            "handle": [
                                                {
                                                    "handler": "reverse_proxy",
                                                    "transport": {
                                                        "protocol": "fastcgi",
                                                        "split_path": ".php"
                                                    },
                                                    "upstreams": [
                                                        {
                                                            "dial": "unix//run/php/php7.3-fpm.sock"
                                                        }
                                                    ]
                                                }
                                            ],
                                            "terminal": true
                                        },
                                        {
                                            "handle": [
                                                {
                                                    "handler": "file_server"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        }
    }
}
```

And is working as expected!! :)

- Having both index.php and index.html in the html folder and passing no uri in the url: index.php is selected and sent to fastcgi upstream (shows me my IP address correctly) ✅
- Having index.html and index1.php with no uri passed to Caddy, index.html is selected. ✅
- Having index.php and index1.html without the uri passed, index.php is selected and I can manually add /index1.html and /index.php and it works. ✅

**Comment by Henrocker** [comment]
I tried to setup my own draw.io webapp from [github.com/jgraph/drawio](https://github.com/jgraph/drawio) and the setup is the following:
```
 tree /etc/v2caddy/ -L 3
/etc/v2caddy/
├── caddy
├── Caddyfile
└── html
    ├── draw
    │   ├── about.html
    │   ├── app.html
    │   ├── cache.manifest
    │   ├── disableUpdate.js
    │   ├── draw.war
    │   ├── dropbox.html
    │   ├── electron.js
    │   ├── export2.html
    │   ├── export3.html
    │   ├── favicon.ico
    │   ├── github.html
    │   ├── gitlab.html
    │   ├── images
    │   ├── img
    │   ├── index.html
    │   ├── js
    │   ├── math
    │   ├── META-INF
    │   ├── mxgraph
    │   ├── newDiagramCats
    │   ├── offline.html
    │   ├── onedrive2.html
    │   ├── onedrive3.html
    │   ├── onedrive.html
    │   ├── open.html
    │   ├── package.json
    │   ├── plugins
    │   ├── resources
    │   ├── shapes
    │   ├── shortcuts.svg
    │   ├── stencils
    │   ├── styles
    │   ├── templates
    │   ├── WEB-INF
    │   └── yarn.lock
    ├── index1.php
    └── index.html

16 directories, 25 files
```

Now when I visit _http://localhost/draw_, I get only the index.html to load but all the images, scripts from subfolders of folder _draw_ can't be loaded, because Caddy tries to load them from root directory, e.g:

1st request (in _/draw/index.html_) is correct, but second request looks like this: _http://localhost/images/image1.png_ which is incorrect, because the image is located under draw/image/image1.png.

When I visit _http://localhost/draw/_ (slash at the end), everything works fine and the images are loaded correctly from the subfolder images under draw folder.

**Comment by mholt** [comment]
@Henrocker That's usually because paths given in the markup (HTML) are relative, like "styles/grapheditor.css", which, relative to a path like "/draw", means "/styles/grapheditor.css" because there's no way the browser knows that "/draw" is actually a directory.

So if the paths are relative in the HTML, your server needs to accommodate and do the trailing slash. This is what Caddy v1 does -- it canonicalizes URIs with a rewrite automatically so that paths to a directory are redirected to have a trailing slash. However, this also breaks/confuses a lot of people. So, in Caddy 2, you have to configure that redirect yourself from "/draw" to "/draw/".

Maybe this will be common enough that I could make the redirect automatic and on by default, but configurable in the file server, what do you think? (In v1, it's not configurable.)

**Comment by Henrocker** [comment]
Personally, I really like the behaviour of Caddy v1 because it's convenient and didn't break any webapp I've setup so far.

Can you tell me how to turn this redirect on not specifically for draw in that example, but for all directories Caddy v2 finds in my webroot (and subfolders)?

**Comment by mholt** [comment]
I think in nginx this has to be configured manually, but I agree that it's common enough that Caddy can do it for you in the file server (and make it configurable). However, that's a separate issue that's not related to the reverse proxy, so it sounds like you got it working! Great!

Feel free to open another issue about the trailing slash redirects if you'd like.

**Comment by francislavoie** [comment]
I decided to write up a quick Caddyfile version of the config I posted here https://github.com/caddyserver/caddy/pull/2737#issuecomment-528993700 

Won't work yet, but I guess it's the "once this PR is done, this should probably work" config.

<details><pre><code>:80

root * /var/www/public

matcher websockets {
    header_regexp Connection Upgrade
    header Upgrade websocket
}
reverse_proxy match:websockets websockets:6001

matcher rewrite {
    file {
        try_files {path} index.php
    }
}
rewrite match:rewrite {http.matchers.file.relative}

matcher php {
    path *.php
}
fastcgi match:php php-fpm:9000 {
    split_path .php
}

encode gzip

file_server
</code></pre></details>

**Comment by tobya** [comment]
I think it is essential that caddy considers `/draw` a directory without the trailing slash.   If this doesnt happen it  breaks a HUGE amount of websites.

The only reason not to treat `/draw` the same as `/draw/` is because some people have a fetish for "clean" URLs.  In my opinion this is not sufficient reason to break the Web.

**Comment by mholt** [comment]
@tobya I'm not sure I follow. (Is your comment on the right issue? This is a PR for the reverse proxy + fastcgi support, not directories and url paths.)

**Comment by francislavoie** [comment]
@tobya see https://github.com/caddyserver/caddy/issues/2741

**Comment by mholt** [comment]
The Caddyfile integration does not yet handle the rewrites involved with serving PHP apps (but they can still be specified explicitly in the Caddyfile and it will work), but all the main pieces are here now. Will be merging this in soon, and incremental improvements can come thereafter.

**Comment by Henrocker** [comment]
Does that mean I can test with @francislavoie's Caddyfile excluding `matcher rewrite {`?

Anyway, thanks for your (very) quick efforts to integrate this into Caddy v2.

**Comment by mholt** [comment]
@Henrocker Yep! Well, almost.

- `split_path` is just `split` in the Caddyfile (like v1)
- There is not stand-alone `fastcgi` directive, instead it's:
```
reverse_proxy match:php php-fpm:9000 {
    transport fastcgi {
        split .php
    }
}
```

However, for the Caddyfile stuff, it's all untested at this point. So try it out and let us know how it goes!

My hope is that soon (this week?) we can build in a way to enable common PHP configurations without having to specify the 'rewrite' and 'php' matchers explicitly as in @francislavoie's example. But for right now, they'd be necessary.

The 'websocket' matcher and proxy his example shows isn't necessary though (unless your app requires that specifically).

**Comment by mholt** [comment]
Docs are updated: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httphandlersreverse_proxy

Also for the Caddyfile usage (so far): https://github.com/caddyserver/caddy/wiki/v2:-Documentation#reverse_proxy

**Comment by francislavoie** [comment]
I updated my example above, will review the new docs as soon as I can :smile:

**Comment by tobya** [comment]
> @tobya I'm not sure I follow. (Is your comment on the right issue? This is a PR for the reverse proxy + fastcgi support, not directories and url paths.)

I was refering to https://github.com/caddyserver/caddy/pull/2737#issuecomment-529115073

I think a webserver has to assume that /draw is a directory not a file

**Comment by mholt** [comment]
@tobya I still don't quite follow what you mean by "assume that /draw is a directory" but let's take it up in that issue rather than sidetrack this one

**Comment by mholt** [comment]
Thank you everyone for your help!! Please continue to test it and file issues; we will continue working on things as they arise.

**Pull request merged**
