### PR TITLE
Replace strings.Index usages with strings.Cut

### PR DESCRIPTION
**Pull request by WilczynskiT**
fixed https://github.com/caddyserver/caddy/issues/4928

### CODE REVIEW

**Review by mholt — CHANGES_REQUESTED** [review]
Thank you for opening a PR!

I think the purpose of using `strings.Cut()` is to split a string into two pieces. `strings.Index()` is still the right function to see if a substring can be found.

There are some uses of `Index()` that still seem simpler than using `Cut()`, IMO.

I think we'd only want to keep the changes in listeners.go, load.go, and addresses.go. The others seem to be more complicated or not quite the right fit.

There may also be some occurrences of `SplitN()` that we could replace with `Cut()`, if we are splitting only into 2 pieces.

**Comment by WilczynskiT** [comment]
@mholt Okey, thank you for review ;) I changed it. I will look at the `SplitN()` and will create new ticket to do it

**Comment by francislavoie** [comment]
> I will look at the SplitN() and will create new ticket to do it

Please just do it in this PR, it'll be easier to review all in one place.

**Comment by WilczynskiT** [comment]
Okey, I added the changes and signed the CLA. So it is ready to continue the review.

**Review by mholt — APPROVED** [review]
This LGTM!

Thank you for the contribution @WilczynskiT :smiley:

**Pull request merged**
