### PR TITLE
fastcgi: Improve fastcgi SCRIPT_FILENAME generation

### PR DESCRIPTION
**Pull request by longsleep**
This change change the logic how the SCRIPT_FILENAME for fastcgi is
created. IndexFiles are now checked in the matches rule's root instead
of the sites root. In addition a new optional sub-directive 'without'
is added to fastcgi, which allows stripping prefix paths from the
generated SCRIPT_FILENAME.

```
fastcgi /blog/ 127.0.0.1:9000 php {
  without /blog/
  root /usr/share/some-blog-software
}
```

Requests to `/blog/` or `/blog/index.php` will properly find and
load 'index.php' in /usr/share/some-blog-software without any further
rewrites.

### CODE REVIEW

**Comment by longsleep** [comment]
Will add tests once getting positive signals that this change is something you guys consider worth merging.

**Comment by abiosoft** [comment]
Having specific root for fastcgi was deliberate. You can have caddy and fastcgi server running on different hosts.

**Comment by longsleep** [comment]
> Having specific root for fastcgi was deliberate. You can have caddy and fastcgi server running on different hosts.

Sure - behavior is unchanged on that regard.

**Comment by tobya** [comment]
I wonder should `root` here get a name change to something like `alternative_root`?

**Comment by longsleep** [comment]
> I wonder should root here get a name change to something like alternative_root?

Well it's more the `fastcgi_root` - but that's already implied since it's inside the fastcgi directive. But u agree that it could be clearer. Might be a good idea to change while retraining backwards compatibility.

**Comment by mholt** [comment]
@longsleep Thanks for this PR. 

> Will add tests once getting positive signals that this change is something you guys consider worth merging.

I think at this point, the efforts are better spent in making this work in Caddy 2 (it's on the v2 branch). We don't quite have fastcgi support migrated yet, but when we do, I'd like your help verifying that SCRIPT_FILENAME is correct. Would you be willing to help with that?

(Closing this PR for now, further discussion is welcome.)

**Comment by longsleep** [comment]
> Would you be willing to help with that?

Sure - will check Caddy 2 and see what needs to be done there. Will open another PR/Issue if required. Thanks!

**Pull request closed without merging**
