### PR TITLE
ci: publish build artifacts

### PR DESCRIPTION
**Pull request by Mohammed90**
@francislavoie suggeted we publish the pipeline build artifacts so we get access to per-commit binaries. Here'e the attempt to do just that.

### CODE REVIEW

**Comment by Mohammed90** [comment]
You'll see here it says "Artifacts: 4 Published":

https://dev.azure.com/mholt-dev/Caddy/_build/results?buildId=876&view=results

And you'll find them at this page when you click on it:

https://dev.azure.com/mholt-dev/Caddy/_build/results?buildId=876&view=artifacts&type=publishedArtifacts

**Comment by francislavoie** [comment]
Awesome!! This way we can tell people to download those binaries to test features on PRs or on the v2 branch without them needing to build from source (unless they need plugins or whatever)

**Comment by mholt** [comment]
Ohh this will be super cool! What a neat idea!! Thanks @Mohammed90!

**Comment by Mohammed90** [comment]
Any remarks before merging?

**Pull request merged**
