### PR TITLE
ci: Enable caching of go modules

### PR DESCRIPTION
**Pull request by francislavoie**
From https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds

### CODE REVIEW

**Comment by francislavoie** [comment]
Well, the build is actually not any faster with caching. 🤔

It caches ~160MB, and it takes just as long to copy and untar than to just `go get`. It's only faster by a few seconds at best, totally within the margin of error.

Do we care to merge this? @mholt @Mohammed90

**Comment by mholt** [comment]
Huh, you're right... I was just comparing your second CI run here with some previous ones and... it's not much faster, if at all.

Since it doesn't appear to help, let's skip this one, I guess?

**Comment by francislavoie** [comment]
I'd say let's just go with the simplicity of no cache. Curious to hear @Mohammed90's thoughts before closing.

**Comment by Mohammed90** [comment]
Same experience as #2821. I thought it'd probably do better, but no.

**Pull request closed without merging**
