### PR TITLE
fileserver: update css

### PR DESCRIPTION
**Pull request by oarinv**
border-radius will not be covered after hover, 
meta and tr have the same height

### CODE REVIEW

**Comment by mholt** [comment]
Can you please describe what is broken and what this change does? Thanks

**Comment by francislavoie** [comment]
Screenshots for comparison would be helpful.

**Comment by mholt** [comment]
Thanks @oarinv -- I just noticed that in one of your edits you did add screenshots, and I think I see what you mean, at least for the border-radius; but did you mean to close this PR?

**Comment by oarinv** [comment]
> 谢谢@oarinv-- 我刚刚注意到，在您的一项编辑中，您确实添加了屏幕截图，我想我明白您的意思，至少对于边框半径而言；但你的意思是关闭这个 PR 吗？

yes

**Comment by oarinv** [comment]
> Thanks @oarinv -- I just noticed that in one of your edits you did add screenshots, and I think I see what you mean, at least for the border-radius; but did you mean to close this PR?

yes

**Pull request closed without merging**
