### PR TITLE
Preserve the query-string for non browse case

### PR DESCRIPTION
**Pull request by jaygooby**
when doing canonical redirect. Under caddy `v2.6.2` the query-string is lost.

This is related to https://github.com/caddyserver/caddy/pull/5253 which does the same thing when browsing is enabled, but does not fix it for the non-browsing case.

Test like this:

```
mkdir -p /tmp/caddy/example
echo "hello" >  /tmp/caddy/example/index.html

caddy file-server --root /tmp/caddy

curl "http://127.0.0.1/example?query=retained"
<a href="/example/">Permanent Redirect</a>.
```

with the fix in place, the query-string is correctly preserved:

```
curl "http://127.0.0.1/example?query=retained"
<a href="/example/?query=retained">Permanent Redirect</a>.
```

### CODE REVIEW

**Comment by francislavoie** [comment]
`origReq` should not be manipulated directly. That can cause side effects. Instead, the URL should be cloned, and that clone can be manipulated.

**Comment by jaygooby** [comment]
I’m happy to work on this, to get the correct behaviour. Are there a set of test cases that show requests that can cause open redirects?

**Comment by mholt** [comment]
Hi Jay, I'll take a look at this as soon as I can and try to figure something out together :)

**Comment by jaygooby** [comment]
Thanks @mholt I'm a golang newbie. `origReq` is assigned from the request, and then I'm returning a string representing the final URL, so it didn't seem like it would be dangerous operation 😅

**Comment by mholt** [comment]
We might be able to safely append the query string to the `to` variable if there is one.

@jaygooby Armed with the docs for https://pkg.go.dev/net/url#URL, think you can try it out?

**Comment by jaygooby** [comment]
Thanks for the docs link! Yup, I'll give it a go later today

**Comment by mholt** [comment]
Awesome. FWIW if you go to [the git history for that file](https://github.com/caddyserver/caddy/commits/2b8d1b1517f98da775465b59e0372a8d9efbd027/modules/caddyhttp/fileserver/staticfiles.go), this commit shows up:

https://github.com/caddyserver/caddy/commit/8848df9c5d372a559d01512b7a4ef00e38867b55

Where I revert a commit that did attempt to preserve the QS. Here's the background: https://github.com/caddyserver/caddy/issues/4205 (it seems complicated).

**Comment by mholt** [comment]
Sure. Tests don't hurt :)

**Comment by jaygooby** [comment]
OK, have started to get my head around tests. 

I've implemented a basic redirect and Test case 1 from your https://github.com/caddyserver/caddy/issues/4205#issuecomment-863352037 in this [integration test](https://github.com/jaygooby/caddy/blob/redo-redirect-fixes/caddytest/integration/redirect_test.go)

I'll get your test case 2 & 3 implemented too, along with one to test the query string preservation, then I'll try the `to` variable appending to get it passing

**Comment by mholt** [comment]
@jaygooby Thanks for working on this, I'm trying to circle back around very soon and inspect this carefully.

**Comment by mholt** [comment]
Superseded by #6109. Thank you for helping to get this started! Sorry it took me so long.

**Pull request closed without merging**
