### PR TITLE
caddyhttp: reverseproxy: fix hash selection policy

### PR DESCRIPTION
**Pull request by simaotwx**
The tests ran without an issue, so this should be the fix.

Fixes: #4135
Test: go test './...' -count=1

### CODE REVIEW

**Comment by francislavoie** [comment]
We'll definitely need a test that fails _before_ the change to make sure it actually fixes the problem.

**Comment by simaotwx** [comment]
Test case added. It fails before applying my patch and passes afterwards.

**Comment by simaotwx** [comment]
Is it appropriate to reverse the order of the commits? Maybe that would immediately prove that the commit after it fixes the issue.

**Comment by francislavoie** [comment]
No, that's okay! As long as you confirmed it, that's good :+1: 

Thanks!

**Review by francislavoie — APPROVED** [review]

**Comment by simaotwx** [comment]
Alright, perfect. :)

**Review by mholt — APPROVED** [review]
Excellent; thank you so much for the fix and the test case! Please feel free to contribute again.

**Pull request merged**
